
/*<RBHead>
 *************************************************************************
 *                                                                       *
 *                      ROBERT BOSCH GMBH                                *
 *                          STUTTGART                                    *
 *                                                                       *
 *          Alle Rechte vorbehalten - All rights reserved                *
 *                                                                       *
 *************************************************************************  
 *
 *    __   __   ___  ___
 *   /_ / /  / /__  /    /__/
 *  /__/ /__/ __ / /__  /  /
 *
 *
 *************************************************************************
 *    Administrative Information (automatically filled in by eASEE)      *
 *************************************************************************
 *
 * $Filename__:coeng_steng_pub.h$
 *
 * $Author____:NESTORADMINSDOM$
 *
 * $Function__:This version is created by migration tool$
 *
 *************************************************************************
 * $Domain____:SDOM$
 * $User______:WBB2SI$
 * $Date______:14.10.2010$
 * $Class_____:SWHDR$
 * $Name______:coeng_steng_pub$
 * $Variant___:4.4.0$
 * $Revision__:1$
 * $Type______:H$
 * $State_____:AVAILABLE$
 * $Generated_:$
 *************************************************************************
 *
 * $UniqueName:$
 * $Component_:$
 *
 * $FDEF______:$
 *
 *************************************************************************
 * List Of Changes
 *
 * $History
 * 
 * 4.4.0; 1     14.10.2010 WBB2SI
 *   After review: CoEng_StEng more robust: CoVeh_stEngStopOrd replaced, 
 *   CoEng_stStalEngReas OBD conform
 * 
 * 4.4.0; 0     12.10.2010 WBB2SI
 *   CoEng_StEng more robust
 * 
 * 4.3.0; 0     21.05.2010 AUF2FE
 *   Modifications done after review
 * 
 * 4.2.0; 3     28.04.2010 AUF2FE
 *   Modifications done after testing
 * 
 * 4.2.0; 2     15.04.2010 AUF2FE
 *   Remove XDDGQ and XDDSIC
 * 
 * 4.2.0; 1     24.03.2010 AUF2FE
 *   checkin after review by ESV3
 * 
 * 4.2.0; 0     08.01.2010 AUF2FE
 *   Merge DS-GS, Update to ASCET autocode, correction of CoEng_tiNormalOBD 
 *   calculation, general improvement
 * 
 * 4.0.0; 0     18.11.2008 SET2COB
 *   Initial import from Clearcase 
 *      File name: coeng_steng_pub.h
 *      Version: \main\basis\b_CoEng\4
 * 
 * $
 *
 ***************************************************************************************************
 *
 *   T H I S   I S   A   G E N E R A T E D   F I L E   F R O M      A  S  C  E  T
 *
 ***************************************************************************************************
 * Autor:              wbb2si
 * Date:               14.10.2010  12:20:16
 * Modulname:          CoEng_StEng
 * Filename:           coeng_steng_pub.h
 * Filetype:           pubheader
 * Implementation:     Impl
 *
 * $Generated by ASCET-SD: V5.2.2 RB-DGS 2.1
 * Expander:           Generic  CID: 521
 * Codegenerator:      ASCET-SE-RBPT V5.7.7
 * Target:             Generic:MEDC17 [V5.7.7]
 * CgenOptions:
 *             Allow Double bit Size for Division Numerators=true
 *             Generate Round Operation on float to integer Assignment=false
 *             Generate Access Methods for dT (Alternative: use OS dT directly)=false
 *             Temp Vars always 32 bit (integer)=false
 *             Generate Limiters (may be changed locally)=true
 *             Protected Division=false
 *             Use SHIFT Operation on Signed Values instead of DIV Operation=true
 *             Optimize Direct Access Methods (Multiple Levels)=true
 *             Optimize Direct Access Methods (One Level)=true
 *             Add Comment with Generation Information for each Component=false
 *             Add Comment with Implementation Information for each Assignment Statement=true
 *             Add Comment with Specification Source for each Statement=true
 *             Add Implementation Definitions=true
 *             Add parenthesis for readability=true
 *             Allow Limit Service for Assignment Limitation=true
 *             Arithmetic Service Set=rb-services
 *             Auto-inline private methods (Smaller code-size - may be changed locally)=false
 *             Code Generator=Object Based Controller Implementation
 *             Common Subexpression Elimination=true
 *             Compiler=MEDC17 (dummy compiler)
 *             Constant Folding on Arithmetic Operations=true
 *             Constant Folding on Control Flow=true
 *             Constant Folding on Logical Operations=true
 *             Force Parenthesis for Binary Logical Operators=true
 *             Generate Access Macros for=()
 *             Generate Define Directives for Enum Values=true
 *             Generate Map File=false
 *             Generate OS Configuration=false
 *             Generate well-formed switch=true
 *             Hierarchical Code-Generation (may be changed locally)=false
 *             Initialise history variable with zero=true
 *             Inline directive=INLINE_FUNCTION
 *             Maximum bit Length (float)=32
 *             Maximum bit Length (int)=32
 *             Operating System=ERCOSEK
 *             Operator Simplification (general)=true
 *             Operator Simplification with Respect to Intervals=true
 *             Optimize Static Actions (Restricted Modelling)=false
 *             Outline Generated Methods (may be changed locally)=false
 *             Private directive=
 *             Public directive=
 *             Result on Division by Zero=numerator
 *             Target=Generic:MEDC17
 *             Use power of 2 approximations of literals=false
 *             Use SHIFT Operation on Signed Values instead of MUL Operation=true
 *
 ***************************************************************************************************
</RBHead>*/
#ifndef _COENG_STENG_PUB_H
#define _COENG_STENG_PUB_H

/*
***************************************************************************************
* Prototypes
***************************************************************************************
*/

/* process prototypes for COENG_STENG_IMPL */
void CoEng_stEng_Proc(void);
void CoEng_stEng_Proc_Ini(void);
void CoEng_stEng_Proc_IniDrv(void);

/* _COENG_STENG_PUB_H */
#endif
