/********************************************************************************
FILE:         epmcas_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _EPMCAS_MSG_H
#define _EPMCAS_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __EPMCAS_TIEDGE_EXT__
#define __EPMCAS_TIEDGE_EXT__
extern sint32 EpmCaS_tiEdge[];
#endif /* __EPMCAS_TIEDGE_EXT__ */

#ifndef __EPMCRS_CTREVSTRTEXTD_EXT__
#define __EPMCRS_CTREVSTRTEXTD_EXT__
extern sint32 EpmCrS_ctRevStrtExtd;
#endif /* __EPMCRS_CTREVSTRTEXTD_EXT__ */

#ifndef __EPMCAS_NENG_EXT__
#define __EPMCAS_NENG_EXT__
extern sint16 EpmCaS_nEng;
#endif /* __EPMCAS_NENG_EXT__ */

#ifndef __EPMCAS_PHIADAP_EXT__
#define __EPMCAS_PHIADAP_EXT__
extern sint16 EpmCaS_phiAdap[];
#endif /* __EPMCAS_PHIADAP_EXT__ */

#ifndef __EPMCAS_PHICOR_EXT__
#define __EPMCAS_PHICOR_EXT__
extern sint16 EpmCaS_phiCor[];
#endif /* __EPMCAS_PHICOR_EXT__ */

#ifndef __EPMCAS_PHIDIFFAVRGLIM_EXT__
#define __EPMCAS_PHIDIFFAVRGLIM_EXT__
extern sint16 EpmCaS_phiDiffAvrgLim[];
#endif /* __EPMCAS_PHIDIFFAVRGLIM_EXT__ */

#ifndef __EPMCAS_PHIDIFFLIM_EXT__
#define __EPMCAS_PHIDIFFLIM_EXT__
extern sint16 EpmCaS_phiDiffLim[];
#endif /* __EPMCAS_PHIDIFFLIM_EXT__ */

#ifndef __EPMCAS_PHIEDGE_EXT__
#define __EPMCAS_PHIEDGE_EXT__
extern sint16 EpmCaS_phiEdge[];
#endif /* __EPMCAS_PHIEDGE_EXT__ */

#ifndef __EPMCAS_PHIOFSCORR_EXT__
#define __EPMCAS_PHIOFSCORR_EXT__
extern sint16 EpmCaS_phiOfsCorr[];
#endif /* __EPMCAS_PHIOFSCORR_EXT__ */

#ifndef __EPMCAS_PHITEMPCOR_EXT__
#define __EPMCAS_PHITEMPCOR_EXT__
extern sint16 EpmCaS_phiTempCor[];
#endif /* __EPMCAS_PHITEMPCOR_EXT__ */

#ifndef __EPMCRS_CTREVINI_EXT__
#define __EPMCRS_CTREVINI_EXT__
extern sint16 EpmCrS_ctRevIni;
#endif /* __EPMCRS_CTREVINI_EXT__ */

#ifndef __EPMCRS_CTREVSTRT_EXT__
#define __EPMCRS_CTREVSTRT_EXT__
extern sint16 EpmCrS_ctRevStrt;
#endif /* __EPMCRS_CTREVSTRT_EXT__ */

#ifndef __EPM_NENG_EXT__
#define __EPM_NENG_EXT__
extern sint16 Epm_nEng;
#endif /* __EPM_NENG_EXT__ */

#ifndef __EPMCAS_CTEDGEEQUID_EXT__
#define __EPMCAS_CTEDGEEQUID_EXT__
extern sint8 EpmCaS_ctEdgeEquid[];
#endif /* __EPMCAS_CTEDGEEQUID_EXT__ */

#ifndef __EPMCAS_CASI1CTEDGE10MSU8_EXT__
#define __EPMCAS_CASI1CTEDGE10MSU8_EXT__
extern uint8                    EpmCaS_CASI1ctEdge10msU8;
#endif /* __EPMCAS_CASI1CTEDGE10MSU8_EXT__ */

#ifndef __EPMCAS_ALLCASEDGES_EXT__
#define __EPMCAS_ALLCASEDGES_EXT__
extern uint8 EpmCaS_allCaSEdges[];
#endif /* __EPMCAS_ALLCASEDGES_EXT__ */

#ifndef __EPMCAS_NUMSEGSERLST_EXT__
#define __EPMCAS_NUMSEGSERLST_EXT__
extern uint8                    EpmCaS_numSegSerLst;
#endif /* __EPMCAS_NUMSEGSERLST_EXT__ */

#ifndef __EPMCAS_STNENG_EXT__
#define __EPMCAS_STNENG_EXT__
extern uint8                    EpmCaS_stNEng;
#endif /* __EPMCAS_STNENG_EXT__ */

#ifndef __EPMCAS_STPHIDIFFLIM_EXT__
#define __EPMCAS_STPHIDIFFLIM_EXT__
extern uint8 EpmCaS_stphiDiffLim[];
#endif /* __EPMCAS_STPHIDIFFLIM_EXT__ */

#ifndef __EPMCRS_CTINC_EXT__
#define __EPMCRS_CTINC_EXT__
extern uint8                    EpmCrS_ctInc;
#endif /* __EPMCRS_CTINC_EXT__ */

#ifndef __EPMCRS_STSIGMODE_EXT__
#define __EPMCRS_STSIGMODE_EXT__
extern uint8                    EpmCrS_stSigMode;
#endif /* __EPMCRS_STSIGMODE_EXT__ */

#ifndef __EPMRRS_BENGSWOFF_EXT__
#define __EPMRRS_BENGSWOFF_EXT__
extern uint8                    EpmRRS_bEngSwOff;
#endif /* __EPMRRS_BENGSWOFF_EXT__ */

#ifndef __EPMSEQ_NUMINTTYP_EXT__
#define __EPMSEQ_NUMINTTYP_EXT__
extern uint8                    EpmSeq_numIntTyp;
#endif /* __EPMSEQ_NUMINTTYP_EXT__ */

#ifndef __EPMSYN_STRR_EXT__
#define __EPMSYN_STRR_EXT__
extern uint8 EpmSyn_stRR[];
#endif /* __EPMSYN_STRR_EXT__ */

#ifndef __EPM_STOPMODE_EXT__
#define __EPM_STOPMODE_EXT__
extern uint8                    Epm_stOpMode;
#endif /* __EPM_STOPMODE_EXT__ */

#ifndef __EPM_STSYNC_EXT__
#define __EPM_STSYNC_EXT__
extern uint8                    Epm_stSync;
#endif /* __EPM_STSYNC_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_EpmCaS_CASI1ctEdge10msU8 
#define SET_EpmCaS_CASI1ctEdge10msU8 (EpmCaS_CASI1ctEdge10msU8=TRUE)
#endif
#ifndef CLR_EpmCaS_CASI1ctEdge10msU8 
#define CLR_EpmCaS_CASI1ctEdge10msU8 (EpmCaS_CASI1ctEdge10msU8=FALSE)
#endif
#ifndef GET_EpmCaS_CASI1ctEdge10msU8 
#define GET_EpmCaS_CASI1ctEdge10msU8 (EpmCaS_CASI1ctEdge10msU8)
#endif
#ifndef PUT_EpmCaS_CASI1ctEdge10msU8 
#define PUT_EpmCaS_CASI1ctEdge10msU8(val) ((val) ? SET_EpmCaS_CASI1ctEdge10msU8 : CLR_EpmCaS_CASI1ctEdge10msU8)
#endif


#ifndef SET_EpmCaS_numSegSerLst 
#define SET_EpmCaS_numSegSerLst (EpmCaS_numSegSerLst=TRUE)
#endif
#ifndef CLR_EpmCaS_numSegSerLst 
#define CLR_EpmCaS_numSegSerLst (EpmCaS_numSegSerLst=FALSE)
#endif
#ifndef GET_EpmCaS_numSegSerLst 
#define GET_EpmCaS_numSegSerLst (EpmCaS_numSegSerLst)
#endif
#ifndef PUT_EpmCaS_numSegSerLst 
#define PUT_EpmCaS_numSegSerLst(val) ((val) ? SET_EpmCaS_numSegSerLst : CLR_EpmCaS_numSegSerLst)
#endif


#ifndef SET_EpmCaS_stNEng 
#define SET_EpmCaS_stNEng (EpmCaS_stNEng=TRUE)
#endif
#ifndef CLR_EpmCaS_stNEng 
#define CLR_EpmCaS_stNEng (EpmCaS_stNEng=FALSE)
#endif
#ifndef GET_EpmCaS_stNEng 
#define GET_EpmCaS_stNEng (EpmCaS_stNEng)
#endif
#ifndef PUT_EpmCaS_stNEng 
#define PUT_EpmCaS_stNEng(val) ((val) ? SET_EpmCaS_stNEng : CLR_EpmCaS_stNEng)
#endif


#ifndef SET_EpmCrS_ctInc 
#define SET_EpmCrS_ctInc (EpmCrS_ctInc=TRUE)
#endif
#ifndef CLR_EpmCrS_ctInc 
#define CLR_EpmCrS_ctInc (EpmCrS_ctInc=FALSE)
#endif
#ifndef GET_EpmCrS_ctInc 
#define GET_EpmCrS_ctInc (EpmCrS_ctInc)
#endif
#ifndef PUT_EpmCrS_ctInc 
#define PUT_EpmCrS_ctInc(val) ((val) ? SET_EpmCrS_ctInc : CLR_EpmCrS_ctInc)
#endif


#ifndef SET_EpmCrS_stSigMode 
#define SET_EpmCrS_stSigMode (EpmCrS_stSigMode=TRUE)
#endif
#ifndef CLR_EpmCrS_stSigMode 
#define CLR_EpmCrS_stSigMode (EpmCrS_stSigMode=FALSE)
#endif
#ifndef GET_EpmCrS_stSigMode 
#define GET_EpmCrS_stSigMode (EpmCrS_stSigMode)
#endif
#ifndef PUT_EpmCrS_stSigMode 
#define PUT_EpmCrS_stSigMode(val) ((val) ? SET_EpmCrS_stSigMode : CLR_EpmCrS_stSigMode)
#endif


#ifndef SET_EpmRRS_bEngSwOff 
#define SET_EpmRRS_bEngSwOff (EpmRRS_bEngSwOff=TRUE)
#endif
#ifndef CLR_EpmRRS_bEngSwOff 
#define CLR_EpmRRS_bEngSwOff (EpmRRS_bEngSwOff=FALSE)
#endif
#ifndef GET_EpmRRS_bEngSwOff 
#define GET_EpmRRS_bEngSwOff (EpmRRS_bEngSwOff)
#endif
#ifndef PUT_EpmRRS_bEngSwOff 
#define PUT_EpmRRS_bEngSwOff(val) ((val) ? SET_EpmRRS_bEngSwOff : CLR_EpmRRS_bEngSwOff)
#endif


#ifndef SET_EpmSeq_numIntTyp 
#define SET_EpmSeq_numIntTyp (EpmSeq_numIntTyp=TRUE)
#endif
#ifndef CLR_EpmSeq_numIntTyp 
#define CLR_EpmSeq_numIntTyp (EpmSeq_numIntTyp=FALSE)
#endif
#ifndef GET_EpmSeq_numIntTyp 
#define GET_EpmSeq_numIntTyp (EpmSeq_numIntTyp)
#endif
#ifndef PUT_EpmSeq_numIntTyp 
#define PUT_EpmSeq_numIntTyp(val) ((val) ? SET_EpmSeq_numIntTyp : CLR_EpmSeq_numIntTyp)
#endif


#ifndef SET_Epm_stOpMode 
#define SET_Epm_stOpMode (Epm_stOpMode=TRUE)
#endif
#ifndef CLR_Epm_stOpMode 
#define CLR_Epm_stOpMode (Epm_stOpMode=FALSE)
#endif
#ifndef GET_Epm_stOpMode 
#define GET_Epm_stOpMode (Epm_stOpMode)
#endif
#ifndef PUT_Epm_stOpMode 
#define PUT_Epm_stOpMode(val) ((val) ? SET_Epm_stOpMode : CLR_Epm_stOpMode)
#endif


#ifndef SET_Epm_stSync 
#define SET_Epm_stSync (Epm_stSync=TRUE)
#endif
#ifndef CLR_Epm_stSync 
#define CLR_Epm_stSync (Epm_stSync=FALSE)
#endif
#ifndef GET_Epm_stSync 
#define GET_Epm_stSync (Epm_stSync)
#endif
#ifndef PUT_Epm_stSync 
#define PUT_Epm_stSync(val) ((val) ? SET_Epm_stSync : CLR_Epm_stSync)
#endif

#endif
