/********************************************************************************
FILE:         epmhcrs_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _EPMHCRS_MSG_H
#define _EPMHCRS_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __EPMSYN_PHIINT_EXT__
#define __EPMSYN_PHIINT_EXT__
extern sint16 EpmSyn_phiInt;
#endif /* __EPMSYN_PHIINT_EXT__ */

/* -------------- macro defintion of messages --------------------*/

#endif
