/********************************************************************************
FILE:         mrly2med_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _MRLY2MED_MSG_H
#define _MRLY2MED_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __MRLY_ST_EXT__
#define __MRLY_ST_EXT__
extern bool                     MRly_st;
#endif /* __MRLY_ST_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_MRly_st 
#define SET_MRly_st (MRly_st=TRUE)
#endif
#ifndef CLR_MRly_st 
#define CLR_MRly_st (MRly_st=FALSE)
#endif
#ifndef GET_MRly_st 
#define GET_MRly_st (MRly_st)
#endif
#ifndef PUT_MRly_st 
#define PUT_MRly_st(val) ((val) ? SET_MRly_st : CLR_MRly_st)
#endif

#endif
