
/*<RBHead>
 *************************************************************************
 *                                                                       *
 *                      ROBERT BOSCH GMBH                                *
 *                          STUTTGART                                    *
 *                                                                       *
 *          Alle Rechte vorbehalten - All rights reserved                *
 *                                                                       *
 *************************************************************************  
 *
 *    __   __   ___  ___
 *   /_ / /  / /__  /    /__/
 *  /__/ /__/ __ / /__  /  /
 *
 *
 *************************************************************************
 *    Administrative Information (automatically filled in by eASEE)      *
 *************************************************************************
 *
 * $Filename__:mrly_dd.h$
 *
 * $Author____:NESTORADMINSDOM$
 *
 * $Function__:This version is created by migration tool$
 *
 *************************************************************************
 * $Domain____:SDOM$
 * $User______:KUM6COB$
 * $Date______:01.04.2013$
 * $Class_____:SWHDR$
 * $Name______:mrly_dd$
 * $Variant___:1.43.0$
 * $Revision__:0$
 * $Type______:H$
 * $State_____:AVAILABLE$
 * $Generated_:$
 *************************************************************************
 *
 * $UniqueName:$
 * $Component_:$
 *
 * $FDEF______:$
 *
 *************************************************************************
 * List Of Changes
 *
 * $History
 * 
 * 1.43.0; 0     01.04.2013 KUM6COB
 *   Source files are replaced with new version of ASCET(V6.1) generated files.
 *   All SwServices used are updated in Pavast file.
 *   RQONE00140781
 * 
 * 1.40.0; 0     17.06.2009 KDD2FE
 *   Initial import from Nestor 
 *        Object in Nestor : 
 *        Domain :MX17
 *        Class :SWHDR
 *        Object name :MRLY_DD
 *        Variant :20.40
 *        Revision :0
 * 
 * $
 *
 ***************************************************************************************************
 *
 *   T H I S   I S   A   G E N E R A T E D   F I L E   F R O M      A  S  C  E  T
 *
 ***************************************************************************************************
 * Autor:              kum6cob
 * Date:               4/1/2013  12:13:57
 * Modulname:          MRly_DD
 * Filename:           MRly_DD.h
 * Filetype:           header
 * Implementation:     Impl
 *
 * $Generated by ASCET-SD: V6.1.3 RB-DGS 2.1
 * Expander:           Generic  CID: 610
 * Codegenerator:      ASCET-SE-RBPT V6.1.3.59.14
 * Target:             Generic:ME17 with class support [V6.1.3.59.14]
 * CgenOptions:
 *             Allow Double bit Size for Division Numerators=true
 *             Generate Round Operation on float to integer Assignment=false
 *             Generate Access Methods for dT (Alternative: use OS dT directly)=false
 *             Temp Vars always 32 bit (integer)=false
 *             Generate Limiters (may be changed locally)=true
 *             Use SHIFT Operation on Signed Values instead of DIV Operation=true
 *             Optimize Direct Access Methods (Multiple Levels)=true
 *             Protected Vector Indices=false
 *             Optimize Direct Access Methods (One Level)=true
 *             Add Comment with Generation Information for each Component=false
 *             Add Comment with Implementation Information for each Assignment Statement=true
 *             Add Comment with Specification Source for each Statement=true
 *             Add Implementation Definitions=true
 *             Add parenthesis for readability=true
 *             Allow Limit Service for Assignment Limitation=true
 *             Arithmetic Service Set=rb-services
 *             Auto-inline private methods (Smaller code-size - may be changed locally)=false
 *             Casting=Legacy
 *             Code Generator=Object Based Controller Implementation
 *             Compiler=ME17 (dummy compiler)
 *             Division truncation direction=Zero (T-division)
 *             Force Parenthesis for Binary Logical Operators=true
 *             Generate Access Macros for=()
 *             Generate Data Structures=YESALL
 *             Generate Define Directives for Enum Values=true
 *             Generate Map File=false
 *             Generate OS Configuration=false
 *             Generate well-formed switch=true
 *             Hierarchical Code-Generation (may be changed locally)=false
 *             Initialise history variable with zero=true
 *             Inline directive=INLINE_FUNCTION
 *             Integer Bit Size=32
 *             Maximum bit Length (float)=32
 *             Maximum bit Length (int)=32
 *             Operating System=GENERIC_OSEK
 *             Optimize Static Actions (Restricted Modelling)=false
 *             Outline Generated Methods (may be changed locally)=false
 *             Prefix for Component Names=
 *             Private directive=static
 *             Protected against division by zero=false
 *             Protected Division against Signed Overflow=false
 *             Public directive=
 *             Result on Division by Zero=numerator
 *             Target=Generic:ME17 with class support
 *             Use Customized Data Type Names=false
 *             Use power of 2 approximations of literals=false
 *             Use SHIFT Operation on Signed Values instead of MUL Operation=true
 *
 ***************************************************************************************************
</RBHead>*/

#ifndef _MRLY_DD_H
#define _MRLY_DD_H

/*
***************************************************************************************
* Include of User Component Specific Headertext for MRLY_SET_IMPL
***************************************************************************************
*/
#define _MRLY_SET_IMPL_

/* public method prototypes for MRLY_SET_IMPL */
#ifdef _MRLY_SET_IMPL_
void MRLY_SET_IMPL_calc(bit signal);

#endif /* _MRLY_SET_IMPL_ */

#endif /* _MRLY_DD_H */
