/*<RBHead>
 *************************************************************************
 *                                                                       *
 *                      ROBERT BOSCH GMBH                                *
 *                          STUTTGART                                    *
 *                                                                       *
 *          Alle Rechte vorbehalten - All rights reserved                *
 *                                                                       *
 *************************************************************************

 *************************************************************************
 *    Administrative Information (automatically filled in by eASEE)      *
 *************************************************************************
 *
 * $Filename__:srvb_conf.h$
 *
 * $Author____:NESTORADMINSDOM$
 *
 * $Function__:$
 *
 *************************************************************************
 * $Domain____:SDOM$
 * $User______:NSL2COB$
 * $Date______:08.10.2014$
 * $Class_____:SWHDR$
 * $Name______:srvb_conf$
 * $Variant___:1.17.0$
 * $Revision__:1$
 * $Type______:H$
 * $State_____:AVAILABLE$
 * $Generated_:$
 *************************************************************************
 *
 * $UniqueName:$
 * $Component_:$
 *
 *
 *************************************************************************
 * List Of Changes
 *
 * $History
 * 
 * 1.17.0; 1     08.10.2014 NSL2COB
 *   To edit the SRVB_RAINFLOWCOUNTER
 * 
 * 1.17.0; 0     08.10.2014 NSL2COB
 *   To add SrvB_RainflowCounter_S32_B
 * 
 * 1.16.0; 0     26.08.2014 PIR5COB
 *   Updation of the configurations for suzuki specific hysteresis functionality
 * 
 * 1.15.0; 2     25.04.2014 SYA2COB
 *   As the previous revision was updated with customer specific contents, new 
 *   revision is created with platform contents
 * 
 * 1.15.0; 1     22.10.2013 GER5KOR
 *   I:RQONE00161100
 * 
 * 1.15.0; 0     09.01.2013 SYA2COB
 *   To bring back the configuration of FCL:SrvB_Conf \1.15.0;0
 * 
 * 1.14.0; 1     21.12.2011 PUP1COB
 *   RCMS01245053 : 38.1 - BC-Package requests and integration for BC-VehC
 * 
 * 1.14.0; 0     30.03.2010 VKA2FE
 *   Migrated from ClearCase, derived from B_SRVB_Conf.14.0.0
 * 
 * 1.13.0; 0     09.02.2010 VKA2FE
 *   Derived from B_SRVB_Conf.13.0.0
 * 
 * 1.12.0; 0     14.12.2009 VKA2FE
 *   Derived from B_SRVB_Conf.12.0.0
 * 
 * $
 *
 *************************************************************************
 </RBHead>*/

#ifndef _SRVB_CONF_H
#define _SRVB_CONF_H



/*
 ***************************************************************************************************
 * Memory Configuration
 ***************************************************************************************************
 */

/* Macro for code location              */
/* Do not change these macros           */

#define SRVB_LOCATION_CACHED            1
#define SRVB_LOCATION_INLINE            2
#define SRVB_LOCATION_SPRAM             3

/* definition of assemblercode usage in all possible services                                     */
/* values:     0  -  no asseblercode usage in any service                                         */
/*             1  -  all service witch are also written in                                        */
/*                   assembler will be used in assembler                                          */
#define SRVB_IMPL_ASM_ENABLE            1

/* definition for services location configuration                                                 */
/* values:     SRVB_LOCATION_CACHED  -  this service can only be called                           */
/*                                      and is located to the cached segment (0x8*)               */
/*             SRVB_LOCATION_INLINE  -  this service will be inlined (and                         */
/*                                      there is no possibility for calling)                      */
/*             SRVB_LOCATION_SPRAM   -  this service can only be called                           */
/*                                      and is located to the SPRAM segment (0xD4)                */


/**************************************************************************************************/
/* New DGS-SRV services                                                                           */
/**************************************************************************************************/

/**************************************************************************************************/
/* Following services can be set to:                                                              */
/* SRVB_LOCATION_CACHED, SRVB_LOCATION_INLINE or SRVB_LOCATION_SPRAM                              */
/**************************************************************************************************/

#define SRVB_ABS_S32_S16_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_ABS_S32_S32_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_ABS_S32_S8_LOCATION                 SRVB_LOCATION_INLINE
#define SRVB_ABS_S32_U16_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_ABS_S32_U32_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_ABS_S32_U8_LOCATION                 SRVB_LOCATION_INLINE
#define SRVB_ABSDIFF_S32S32_S16_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_ABSDIFF_S32S32_S32_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_ABSDIFF_S32S32_S8_LOCATION          SRVB_LOCATION_INLINE
#define SRVB_ABSDIFF_S32S32_U16_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_ABSDIFF_S32S32_U32_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_ABSDIFF_S32S32_U8_LOCATION          SRVB_LOCATION_INLINE
#define SRVB_ABSDIFF_U32S32_U16_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_ABSDIFF_U32S32_U32_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_ABSDIFF_U32S32_U8_LOCATION          SRVB_LOCATION_INLINE
#define SRVB_ABSDIFF_U32U32_U16_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_ABSDIFF_U32U32_U32_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_ABSDIFF_U32U32_U8_LOCATION          SRVB_LOCATION_INLINE
#define SRVB_ADD_S32S32_S16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_ADD_S32S32_S32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_ADD_S32S32_S8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_ADD_S32S32_U16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_ADD_S32S32_U32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_ADD_S32S32_U8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_ADD_U32S32_S16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_ADD_U32S32_S32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_ADD_U32S32_S8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_ADD_U32S32_U16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_ADD_U32S32_U32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_ADD_U32S32_U8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_ADD_U32U32_S16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_ADD_U32U32_S32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_ADD_U32U32_S8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_ADD_U32U32_U16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_ADD_U32U32_U32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_ADD_U32U32_U8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_AVERAGE_S32S32_S32_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_AVERAGEARRAY_S16_LOCATION           SRVB_LOCATION_INLINE
#define SRVB_AVERAGEARRAY_S32_LOCATION           SRVB_LOCATION_INLINE
#define SRVB_AVERAGESLIDING_S16_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_AVERAGESLIDING_S32_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_COUNTER_U16_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_COUNTER_U32_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_COUNTER_U8_LOCATION                 SRVB_LOCATION_INLINE
#define SRVB_COUNTERU16SET_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_COUNTERU32SET_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_COUNTERU8SET_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_DIV_S32S32_S16_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_S32S32_S32_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_S32S32_S8_LOCATION              SRVB_LOCATION_SPRAM
#define SRVB_DIV_S32S32_U16_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_S32S32_U32_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_S32S32_U8_LOCATION              SRVB_LOCATION_SPRAM
#define SRVB_DIV_S32U32_S16_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_S32U32_S32_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_S32U32_S8_LOCATION              SRVB_LOCATION_SPRAM
#define SRVB_DIV_S32U32_U16_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_S32U32_U32_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_S32U32_U8_LOCATION              SRVB_LOCATION_SPRAM
#define SRVB_DIV_S64S32_S32_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_S64S32_U32_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_S64U32_S32_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_S64U32_U32_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_U32S32_S16_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_U32S32_S32_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_U32S32_S8_LOCATION              SRVB_LOCATION_SPRAM
#define SRVB_DIV_U32S32_U16_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_U32S32_U32_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_U32S32_U8_LOCATION              SRVB_LOCATION_SPRAM
#define SRVB_DIV_U32U32_S16_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_U32U32_S32_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_U32U32_S8_LOCATION              SRVB_LOCATION_SPRAM
#define SRVB_DIV_U32U32_U16_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_U32U32_U32_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_U32U32_U8_LOCATION              SRVB_LOCATION_SPRAM
#define SRVB_DIV_U64S32_S32_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_U64S32_U32_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_U64U32_S32_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_DIV_U64U32_U32_LOCATION             SRVB_LOCATION_SPRAM
#define SRVB_MAX_S16_LOCATION                    SRVB_LOCATION_INLINE
#define SRVB_MAX_S32_LOCATION                    SRVB_LOCATION_INLINE
#define SRVB_MAX_S8_LOCATION                     SRVB_LOCATION_INLINE
#define SRVB_MAX_U16_LOCATION                    SRVB_LOCATION_INLINE
#define SRVB_MAX_U32_LOCATION                    SRVB_LOCATION_INLINE
#define SRVB_MAX_U8_LOCATION                     SRVB_LOCATION_INLINE
#define SRVB_MEMCOPYU16_LOCATION                 SRVB_LOCATION_CACHED
#define SRVB_MEMCOPYU32_LOCATION                 SRVB_LOCATION_CACHED
#define SRVB_MEMCOPYU8_LOCATION                  SRVB_LOCATION_CACHED
#define SRVB_MEMFILLU16_LOCATION                 SRVB_LOCATION_CACHED
#define SRVB_MEMFILLU32_LOCATION                 SRVB_LOCATION_CACHED
#define SRVB_MEMFILLU8_LOCATION                  SRVB_LOCATION_CACHED
#define SRVB_MEMSWAPU16_B_LOCATION               SRVB_LOCATION_CACHED
#define SRVB_MEMSWAPU32_B_LOCATION               SRVB_LOCATION_CACHED
#define SRVB_MEMSWAPU8_B_LOCATION                SRVB_LOCATION_CACHED
#define SRVB_MIN_S16_LOCATION                    SRVB_LOCATION_INLINE
#define SRVB_MIN_S32_LOCATION                    SRVB_LOCATION_INLINE
#define SRVB_MIN_S8_LOCATION                     SRVB_LOCATION_INLINE
#define SRVB_MIN_U16_LOCATION                    SRVB_LOCATION_INLINE
#define SRVB_MIN_U32_LOCATION                    SRVB_LOCATION_INLINE
#define SRVB_MIN_U8_LOCATION                     SRVB_LOCATION_INLINE
#define SRVB_MUL_S32S32_S16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_MUL_S32S32_S32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_MUL_S32S32_S8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_MUL_S32S32_U16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_MUL_S32S32_U32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_MUL_S32S32_U8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_MUL_U32S32_S16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_MUL_U32S32_S32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_MUL_U32S32_S8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_MUL_U32S32_U16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_MUL_U32S32_U32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_MUL_U32S32_U8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_MUL_U32U32_S16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_MUL_U32U32_S32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_MUL_U32U32_S8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_MUL_U32U32_U16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_MUL_U32U32_U32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_MUL_U32U32_U8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_MULADD_S32S32S32_S16_LOCATION       SRVB_LOCATION_INLINE
#define SRVB_MULADD_S32S32S32_S32_LOCATION       SRVB_LOCATION_INLINE
#define SRVB_MULADD_U32U32U32_U16_LOCATION       SRVB_LOCATION_INLINE
#define SRVB_MULADD_U32U32U32_U32_LOCATION       SRVB_LOCATION_INLINE
#define SRVB_MULDIV_S32S32S32_S16_LOCATION       SRVB_LOCATION_SPRAM
#define SRVB_MULDIV_S32S32S32_S32_LOCATION       SRVB_LOCATION_SPRAM
#define SRVB_MULDIV_S32S32S32_U16_LOCATION       SRVB_LOCATION_SPRAM
#define SRVB_MULDIV_U32U32U32_U16_LOCATION       SRVB_LOCATION_SPRAM
#define SRVB_MULDIV_U32U32U32_U32_LOCATION       SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_S32S32_S16_LOCATION      SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_S32S32_S32_LOCATION      SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_S32S32_S8_LOCATION       SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_S32S32_U16_LOCATION      SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_S32S32_U32_LOCATION      SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_S32S32_U8_LOCATION       SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_U32S32_S16_LOCATION      SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_U32S32_S32_LOCATION      SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_U32S32_S8_LOCATION       SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_U32S32_U16_LOCATION      SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_U32S32_U32_LOCATION      SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_U32S32_U8_LOCATION       SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_U32U32_S16_LOCATION      SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_U32U32_S32_LOCATION      SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_U32U32_S8_LOCATION       SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_U32U32_U16_LOCATION      SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_U32U32_U32_LOCATION      SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT_U32U32_U8_LOCATION       SRVB_LOCATION_SPRAM
#define SRVB_PARITYEVEN_S32_B_LOCATION           SRVB_LOCATION_INLINE
#define SRVB_PARITYEVEN_U32_B_LOCATION           SRVB_LOCATION_INLINE
#define SRVB_PARITYODD_S32_B_LOCATION            SRVB_LOCATION_INLINE
#define SRVB_PARITYODD_U32_B_LOCATION            SRVB_LOCATION_INLINE
#define SRVB_SUB_S32S32_S16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_SUB_S32S32_S32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_SUB_S32S32_S8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_SUB_S32S32_U16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_SUB_S32S32_U32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_SUB_S32S32_U8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_SUB_S32U32_S16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_SUB_S32U32_S32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_SUB_S32U32_S8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_SUB_S32U32_U16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_SUB_S32U32_U32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_SUB_S32U32_U8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_SUB_U32S32_S16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_SUB_U32S32_S32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_SUB_U32S32_S8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_SUB_U32S32_U16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_SUB_U32S32_U32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_SUB_U32S32_U8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_SUB_U32U32_S16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_SUB_U32U32_S32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_SUB_U32U32_S8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_SUB_U32U32_U16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_SUB_U32U32_U32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_SUB_U32U32_U8_LOCATION              SRVB_LOCATION_INLINE

/**************************************************************************************************/
/* Following services can be set to: SRVB_LOCATION_CACHED or SRVB_LOCATION_SPRAM                  */
/**************************************************************************************************/

#define SRVB_MEDIAN_S16_LOCATION                 SRVB_LOCATION_CACHED
#define SRVB_MEDIAN_S32_LOCATION                 SRVB_LOCATION_CACHED
#define SRVB_MEDIAN_S8_LOCATION                  SRVB_LOCATION_CACHED
#define SRVB_MEDIAN_U16_LOCATION                 SRVB_LOCATION_CACHED
#define SRVB_MEDIAN_U32_LOCATION                 SRVB_LOCATION_CACHED
#define SRVB_MEDIAN_U8_LOCATION                  SRVB_LOCATION_CACHED
#define SRVB_RAINFLOWCOUNTER_S32_B_LOCATION      SRVB_LOCATION_CACHED
#define SRVB_SORTASCS16_LOCATION                 SRVB_LOCATION_SPRAM
#define SRVB_SORTASCS32_LOCATION                 SRVB_LOCATION_SPRAM
#define SRVB_SORTASCS8_LOCATION                  SRVB_LOCATION_SPRAM
#define SRVB_SORTASCU16_LOCATION                 SRVB_LOCATION_SPRAM
#define SRVB_SORTASCU32_LOCATION                 SRVB_LOCATION_SPRAM
#define SRVB_SORTASCU8_LOCATION                  SRVB_LOCATION_SPRAM
#define SRVB_SORTDESCS16_LOCATION                SRVB_LOCATION_SPRAM
#define SRVB_SORTDESCS32_LOCATION                SRVB_LOCATION_SPRAM
#define SRVB_SORTDESCS8_LOCATION                 SRVB_LOCATION_SPRAM
#define SRVB_SORTDESCU16_LOCATION                SRVB_LOCATION_SPRAM
#define SRVB_SORTDESCU32_LOCATION                SRVB_LOCATION_SPRAM
#define SRVB_SORTDESCU8_LOCATION                 SRVB_LOCATION_SPRAM

/**************************************************************************************************/
/* Following services can be set to: SRVB_LOCATION_INLINE                                         */
/**************************************************************************************************/

#define SRVB_BITPOSLSBU32_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_BITPOSMSBU32_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_CLRBITMASKU16_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_CLRBITMASKU32_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_CLRBITMASKU8_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_CLRBITU16_LOCATION                  SRVB_LOCATION_INLINE
#define SRVB_CLRBITU32_LOCATION                  SRVB_LOCATION_INLINE
#define SRVB_CLRBITU8_LOCATION                   SRVB_LOCATION_INLINE
#define SRVB_COPYBITU32_LOCATION                 SRVB_LOCATION_INLINE
#define SRVB_EDGEBIPOL_B_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_EDGEFALLING_B_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_EDGERISING_B_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_GETBITFIELDU16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_GETBITFIELDU32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_GETBITFIELDU8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_GETBITU16_B_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_GETBITU32_B_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_GETBITU8_B_LOCATION                 SRVB_LOCATION_INLINE
#define SRVB_INTERVALCLOSED_S32_B_LOCATION       SRVB_LOCATION_INLINE
#define SRVB_INTERVALCLOSED_U32_B_LOCATION       SRVB_LOCATION_INLINE
#define SRVB_INTERVALLEFTOPEN_S32_B_LOCATION     SRVB_LOCATION_INLINE
#define SRVB_INTERVALLEFTOPEN_U32_B_LOCATION     SRVB_LOCATION_INLINE
#define SRVB_INTERVALOPEN_S32_B_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_INTERVALOPEN_U32_B_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_INTERVALRHOPEN_S32_B_LOCATION       SRVB_LOCATION_INLINE
#define SRVB_INTERVALRHOPEN_U32_B_LOCATION       SRVB_LOCATION_INLINE
#define SRVB_LEADINGONES_U32_S32_LOCATION        SRVB_LOCATION_INLINE
#define SRVB_LEADINGSIGNS_S32_S32_LOCATION       SRVB_LOCATION_INLINE
#define SRVB_LEADINGZEROS_U32_S32_LOCATION       SRVB_LOCATION_INLINE
#define SRVB_MOD_S32S32_S16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_MOD_S32S32_S32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_MOD_S32S32_S8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_MOD_U32U32_U16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_MOD_U32U32_U32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_MOD_U32U32_U8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_NEG_S32_S16_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_NEG_S32_S32_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_NEG_S32_S8_LOCATION                 SRVB_LOCATION_INLINE
#define SRVB_NEG_S32_U16_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_NEG_S32_U32_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_NEG_S32_U8_LOCATION                 SRVB_LOCATION_INLINE
#define SRVB_NEG_U32_S16_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_NEG_U32_S32_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_NEG_U32_S8_LOCATION                 SRVB_LOCATION_INLINE
#define SRVB_PUTBITFIELDU16_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_PUTBITFIELDU32_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_PUTBITFIELDU8_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_PUTBITMASKU16_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_PUTBITMASKU32_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_PUTBITMASKU8_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_PUTBITU16_LOCATION                  SRVB_LOCATION_INLINE
#define SRVB_PUTBITU32_LOCATION                  SRVB_LOCATION_INLINE
#define SRVB_PUTBITU8_LOCATION                   SRVB_LOCATION_INLINE
#define SRVB_RANGELIMITER_S16_LOCATION           SRVB_LOCATION_INLINE
#define SRVB_RANGELIMITER_S32_LOCATION           SRVB_LOCATION_INLINE
#define SRVB_RANGELIMITER_S8_LOCATION            SRVB_LOCATION_INLINE
#define SRVB_RANGELIMITER_U16_LOCATION           SRVB_LOCATION_INLINE
#define SRVB_RANGELIMITER_U32_LOCATION           SRVB_LOCATION_INLINE
#define SRVB_RANGELIMITER_U8_LOCATION            SRVB_LOCATION_INLINE
#define SRVB_RSFF_B_LOCATION                     SRVB_LOCATION_INLINE
#define SRVB_SETBITMASKU16_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_SETBITMASKU32_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_SETBITMASKU8_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_SETBITU16_LOCATION                  SRVB_LOCATION_INLINE
#define SRVB_SETBITU32_LOCATION                  SRVB_LOCATION_INLINE
#define SRVB_SETBITU8_LOCATION                   SRVB_LOCATION_INLINE
#define SRVB_SWITCHHYSTCHD_S32_B_LOCATION        SRVB_LOCATION_INLINE
#define SRVB_SWITCHHYSTCHD_U32_B_LOCATION        SRVB_LOCATION_INLINE
#define SRVB_SWITCHHYSTDR_S32_B_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_SWITCHHYSTDR_U32_B_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_SWITCHHYSTLD_S32_B_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_SWITCHHYSTLD_U32_B_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_SWITCHHYSTLR_S32_B_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_SWITCHHYSTLR_U32_B_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_TSTBITINMASKU16_B_LOCATION          SRVB_LOCATION_INLINE
#define SRVB_TSTBITINMASKU32_B_LOCATION          SRVB_LOCATION_INLINE
#define SRVB_TSTBITINMASKU8_B_LOCATION           SRVB_LOCATION_INLINE
#define SRVB_TSTBITMASKU16_B_LOCATION            SRVB_LOCATION_INLINE
#define SRVB_TSTBITMASKU32_B_LOCATION            SRVB_LOCATION_INLINE
#define SRVB_TSTBITMASKU8_B_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_TYPELIMITER_S32_S16_LOCATION        SRVB_LOCATION_INLINE
#define SRVB_TYPELIMITER_S32_S8_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_TYPELIMITER_S32_U16_LOCATION        SRVB_LOCATION_INLINE
#define SRVB_TYPELIMITER_S32_U32_LOCATION        SRVB_LOCATION_INLINE
#define SRVB_TYPELIMITER_S32_U8_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_TYPELIMITER_U32_S16_LOCATION        SRVB_LOCATION_INLINE
#define SRVB_TYPELIMITER_U32_S32_LOCATION        SRVB_LOCATION_INLINE
#define SRVB_TYPELIMITER_U32_S8_LOCATION         SRVB_LOCATION_INLINE
#define SRVB_TYPELIMITER_U32_U16_LOCATION        SRVB_LOCATION_INLINE
#define SRVB_TYPELIMITER_U32_U8_LOCATION         SRVB_LOCATION_INLINE


/**************************************************************************************************/
/* Old services (will be not part of DGS-SRV, only in adapter)                                    */
/**************************************************************************************************/

#define SRVB_ADAPTER_LOCATION                    SRVB_LOCATION_INLINE

#define SRVB_DIFFHWTMRS16_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_DIFFHWTMRS32_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_DIFFSWTMR100MSU8_LOCATION           SRVB_LOCATION_INLINE
#define SRVB_DIFFSWTMR10MSU8_LOCATION            SRVB_LOCATION_INLINE
#define SRVB_DIFFSWTMRS16_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_DIFFSWTMRS32_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_GETHWTMRS16_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_GETHWTMRS32_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_GETSWTMR100MSU8_LOCATION            SRVB_LOCATION_INLINE
#define SRVB_GETSWTMR10MSU8_LOCATION             SRVB_LOCATION_INLINE
#define SRVB_GETSWTMRS16_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_GETSWTMRS32_LOCATION                SRVB_LOCATION_INLINE
#define SRVB_STARTHWTMRS16_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_STARTHWTMRS32_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_STARTSWTMR100MSU8_LOCATION          SRVB_LOCATION_INLINE
#define SRVB_STARTSWTMR10MSU8_LOCATION           SRVB_LOCATION_INLINE
#define SRVB_STARTSWTMRS16_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_STARTSWTMRS32_LOCATION              SRVB_LOCATION_INLINE
#define SRVB_STOPHWTMRS16_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_STOPHWTMRS32_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_STOPSWTMR100MSU8_LOCATION           SRVB_LOCATION_INLINE
#define SRVB_STOPSWTMR10MSU8_LOCATION            SRVB_LOCATION_INLINE
#define SRVB_STOPSWTMRS16_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_STOPSWTMRS32_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_TESTHWTMRS16_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_TESTHWTMRS32_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_TESTSWTMR100MSU8_LOCATION           SRVB_LOCATION_INLINE
#define SRVB_TESTSWTMR10MSU8_LOCATION            SRVB_LOCATION_INLINE
#define SRVB_TESTSWTMRS16_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_TESTSWTMRS32_LOCATION               SRVB_LOCATION_INLINE
#define SRVB_SWTMRINC10MSINI_LOCATION            SRVB_LOCATION_CACHED
#define SRVB_SWTMRINC10MSPROC_LOCATION           SRVB_LOCATION_CACHED
#define SRVB_MULSHRIGHT16_LOCATION               SRVB_LOCATION_SPRAM
#define SRVB_MULSHRIGHT32_LOCATION               SRVB_LOCATION_SPRAM

/* Suzuki SMC project specific hysteresis functionalities */
#define SRVB_SWITCHHYSTLRE_U32_B_LOCATION     SRVB_LOCATION_CACHED
#define SRVB_SWITCHHYSTLER_U32_B_LOCATION     SRVB_LOCATION_CACHED
#define SRVB_SWITCHHYSTLREI_U32_B_LOCATION    SRVB_LOCATION_CACHED
#define SRVB_SWITCHHYSTLERI_U32_B_LOCATION    SRVB_LOCATION_CACHED
#define SRVB_SWITCHHYSTLED_U32_B_LOCATION     SRVB_LOCATION_CACHED
#define SRVB_SWITCHHYSTLDE_U32_B_LOCATION     SRVB_LOCATION_CACHED
#define SRVB_SWITCHHYSTDER_U32_B_LOCATION     SRVB_LOCATION_CACHED
#define SRVB_SWITCHHYSTDRE_U32_B_LOCATION     SRVB_LOCATION_CACHED
#define SRVB_SWITCHHYSTLRE_S32_B_LOCATION     SRVB_LOCATION_CACHED
#define SRVB_SWITCHHYSTLER_S32_B_LOCATION     SRVB_LOCATION_CACHED
#define SRVB_SWITCHHYSTLREI_S32_B_LOCATION    SRVB_LOCATION_CACHED
#define SRVB_SWITCHHYSTLERI_S32_B_LOCATION    SRVB_LOCATION_CACHED
#define SRVB_SWITCHHYSTLED_S32_B_LOCATION     SRVB_LOCATION_CACHED
#define SRVB_SWITCHHYSTLDE_S32_B_LOCATION     SRVB_LOCATION_CACHED
#define SRVB_SWITCHHYSTDER_S32_B_LOCATION     SRVB_LOCATION_CACHED
#define SRVB_SWITCHHYSTDRE_S32_B_LOCATION     SRVB_LOCATION_CACHED

/* SRVB_CONF_H */
#endif
