/********************************************************************************
FILE:         cdrv_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _CDRV_MSG_H
#define _CDRV_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __EPM_NUMCYL_EXT__
#define __EPM_NUMCYL_EXT__
extern uint8                    Epm_numCyl;
#endif /* __EPM_NUMCYL_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_Epm_numCyl 
#define SET_Epm_numCyl (Epm_numCyl=TRUE)
#endif
#ifndef CLR_Epm_numCyl 
#define CLR_Epm_numCyl (Epm_numCyl=FALSE)
#endif
#ifndef GET_Epm_numCyl 
#define GET_Epm_numCyl (Epm_numCyl)
#endif
#ifndef PUT_Epm_numCyl 
#define PUT_Epm_numCyl(val) ((val) ? SET_Epm_numCyl : CLR_Epm_numCyl)
#endif

#endif
