/********************************************************************************
FILE:         dsm_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _DSM_MSG_H
#define _DSM_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __EPM_NENG_EXT__
#define __EPM_NENG_EXT__
extern sint16 Epm_nEng;
#endif /* __EPM_NENG_EXT__ */

#ifndef __DSM_STFADEOUT_EXT__
#define __DSM_STFADEOUT_EXT__
extern uint16 DSM_stFadeOut;
#endif /* __DSM_STFADEOUT_EXT__ */

#ifndef __COENG_ST_EXT__
#define __COENG_ST_EXT__
extern uint8                    CoEng_st;
#endif /* __COENG_ST_EXT__ */

#ifndef __BASSVR_BFUNCTSTREQ_EXT__
#define __BASSVR_BFUNCTSTREQ_EXT__
extern _bit                     BasSvr_bFuncTstReq;
#endif /* __BASSVR_BFUNCTSTREQ_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_CoEng_st 
#define SET_CoEng_st (CoEng_st=TRUE)
#endif
#ifndef CLR_CoEng_st 
#define CLR_CoEng_st (CoEng_st=FALSE)
#endif
#ifndef GET_CoEng_st 
#define GET_CoEng_st (CoEng_st)
#endif
#ifndef PUT_CoEng_st 
#define PUT_CoEng_st(val) ((val) ? SET_CoEng_st : CLR_CoEng_st)
#endif


#ifndef SET_BasSvr_bFuncTstReq 
#define SET_BasSvr_bFuncTstReq (BasSvr_bFuncTstReq=TRUE)
#endif
#ifndef CLR_BasSvr_bFuncTstReq 
#define CLR_BasSvr_bFuncTstReq (BasSvr_bFuncTstReq=FALSE)
#endif
#ifndef GET_BasSvr_bFuncTstReq 
#define GET_BasSvr_bFuncTstReq (BasSvr_bFuncTstReq)
#endif
#ifndef PUT_BasSvr_bFuncTstReq 
#define PUT_BasSvr_bFuncTstReq(val) ((val) ? SET_BasSvr_bFuncTstReq : CLR_BasSvr_bFuncTstReq)
#endif

#endif
