/********************************************************************************
FILE:         errlmp2med_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _ERRLMP2MED_MSG_H
#define _ERRLMP2MED_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __MILLMP_STMIL_EXT__
#define __MILLMP_STMIL_EXT__
extern uint8                    MILLmp_stMIL;
#endif /* __MILLMP_STMIL_EXT__ */

#ifndef __MILLMP_STPS_EXT__
#define __MILLMP_STPS_EXT__
extern bool                     MILLmp_stPs;
#endif /* __MILLMP_STPS_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_MILLmp_stMIL 
#define SET_MILLmp_stMIL (MILLmp_stMIL=TRUE)
#endif
#ifndef CLR_MILLmp_stMIL 
#define CLR_MILLmp_stMIL (MILLmp_stMIL=FALSE)
#endif
#ifndef GET_MILLmp_stMIL 
#define GET_MILLmp_stMIL (MILLmp_stMIL)
#endif
#ifndef PUT_MILLmp_stMIL 
#define PUT_MILLmp_stMIL(val) ((val) ? SET_MILLmp_stMIL : CLR_MILLmp_stMIL)
#endif


#ifndef SET_MILLmp_stPs 
#define SET_MILLmp_stPs (MILLmp_stPs=TRUE)
#endif
#ifndef CLR_MILLmp_stPs 
#define CLR_MILLmp_stPs (MILLmp_stPs=FALSE)
#endif
#ifndef GET_MILLmp_stPs 
#define GET_MILLmp_stPs (MILLmp_stPs)
#endif
#ifndef PUT_MILLmp_stPs 
#define PUT_MILLmp_stPs(val) ((val) ? SET_MILLmp_stPs : CLR_MILLmp_stPs)
#endif

#endif
