/********************************************************************************
FILE:         igndd_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _IGNDD_MSG_H
#define _IGNDD_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __EPM_NENG_EXT__
#define __EPM_NENG_EXT__
extern sint16 Epm_nEng;
#endif /* __EPM_NENG_EXT__ */

#ifndef __EPM_CTCYL_EXT__
#define __EPM_CTCYL_EXT__
extern uint8                    Epm_ctCyl;
#endif /* __EPM_CTCYL_EXT__ */

#ifndef __EPM_STOPMODE_EXT__
#define __EPM_STOPMODE_EXT__
extern uint8                    Epm_stOpMode;
#endif /* __EPM_STOPMODE_EXT__ */

#ifndef __EPM_STSYNC_EXT__
#define __EPM_STSYNC_EXT__
extern uint8                    Epm_stSync;
#endif /* __EPM_STSYNC_EXT__ */

#ifndef __SYC_STSUB_EXT__
#define __SYC_STSUB_EXT__
extern uint8                    SyC_stSub;
#endif /* __SYC_STSUB_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_Epm_ctCyl 
#define SET_Epm_ctCyl (Epm_ctCyl=TRUE)
#endif
#ifndef CLR_Epm_ctCyl 
#define CLR_Epm_ctCyl (Epm_ctCyl=FALSE)
#endif
#ifndef GET_Epm_ctCyl 
#define GET_Epm_ctCyl (Epm_ctCyl)
#endif
#ifndef PUT_Epm_ctCyl 
#define PUT_Epm_ctCyl(val) ((val) ? SET_Epm_ctCyl : CLR_Epm_ctCyl)
#endif


#ifndef SET_Epm_stOpMode 
#define SET_Epm_stOpMode (Epm_stOpMode=TRUE)
#endif
#ifndef CLR_Epm_stOpMode 
#define CLR_Epm_stOpMode (Epm_stOpMode=FALSE)
#endif
#ifndef GET_Epm_stOpMode 
#define GET_Epm_stOpMode (Epm_stOpMode)
#endif
#ifndef PUT_Epm_stOpMode 
#define PUT_Epm_stOpMode(val) ((val) ? SET_Epm_stOpMode : CLR_Epm_stOpMode)
#endif


#ifndef SET_Epm_stSync 
#define SET_Epm_stSync (Epm_stSync=TRUE)
#endif
#ifndef CLR_Epm_stSync 
#define CLR_Epm_stSync (Epm_stSync=FALSE)
#endif
#ifndef GET_Epm_stSync 
#define GET_Epm_stSync (Epm_stSync)
#endif
#ifndef PUT_Epm_stSync 
#define PUT_Epm_stSync(val) ((val) ? SET_Epm_stSync : CLR_Epm_stSync)
#endif


#ifndef SET_SyC_stSub 
#define SET_SyC_stSub (SyC_stSub=TRUE)
#endif
#ifndef CLR_SyC_stSub 
#define CLR_SyC_stSub (SyC_stSub=FALSE)
#endif
#ifndef GET_SyC_stSub 
#define GET_SyC_stSub (SyC_stSub)
#endif
#ifndef PUT_SyC_stSub 
#define PUT_SyC_stSub(val) ((val) ? SET_SyC_stSub : CLR_SyC_stSub)
#endif

#endif
