/*****************************************************************************
   hw_user.c
   Generated By:
   Raptor 2022b_1.1.14772 (6969)
   Matlab (R2022b) 9.13

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Feb 22 21:12:12 2023
 *****************************************************************************/

#include "eagle_EVSR24.h"
#include "eagle_EVSR24_private.h"
#include "hw_user.h"
#include "data.h"
#include "time.h"
#include "sws_eep.h"
#include "sws_can.h"
#include "can_general.h"

/*****************************************************************************
   DEFINES
 *****************************************************************************/
#define TIMESUB(A,B)                   ((A >= B) ? (A-B):(0xFFFFFFFF-B+1+A))

/*****************************************************************************
   CONSTANTS
 *****************************************************************************/
uint8 swsh_Write_KnCDrv_SensorDiagReq(void);
uint8 swsh_Write_KnCDrv_KnockSensorNumber (uint8);
uint8 swsh_Write_KnCDrv_AmplificationFactor(uint8);
sint16 swsh_Write_KnCDrv_MeasureWindowBegin(void);
sint16 swsh_Write_KnCDrv_MeasureWindowLength(void);
sint16 swsh_Write_KnCDrv_FilterSelection(uint8);
uint8 app_is_in_shutdown = 0;

/*****************************************************************************
   TIMER CALLBACK FUNCTIONS
 *****************************************************************************/
void Thread_Foreground(uint32 param)
{
  if (!app_is_in_shutdown) {
    Timer_ooqlV();
  }

  Timed_Trigger_XCP();
  can_process_rx_queue_CAN1();
  UNUSED(param);
}                                      /* End Thread_Foreground() */

void Thread_Background(uint32 param)
{
  Timer_BGND_G6Wyo();
  UNUSED(param);
}

/*****************************************************************************
   APPLICATION CALLBACK FUNCTIONS
 *****************************************************************************/
#define START_SECTION_Task_oem_r1ms
#include "swsh_rb2oem.h"

void App_Startup(void)
{
  app_is_in_shutdown = 0;
}

#define STOP_SECTION_Task_oem_r1ms
#include "swsh_rb2oem.h"
#define START_SECTION_Task_oem_r1ms
#include "swsh_rb2oem.h"

void App_Shutdown(void)
{
  app_is_in_shutdown = 1;
}

#define STOP_SECTION_Task_oem_r1ms
#include "swsh_rb2oem.h"
#define START_SECTION_Mo_CodeCyclicCheck
#include "mo_pragma.h"

void App_SafetyMonitor(void)
{
}

#define STOP_SECTION_Mo_CodeCyclicCheck
#include "mo_pragma.h"
#define START_SECTION_Task_oem_rini
#include "swsh_rb2oem.h"

void NE_ini(void)
{
  {
    extern void initRAMVariables(RAMVariables_T* ramVariables);
    initRAMVariables(&RAMVariables);
  }

  {
    extern void initCONSTVariables(const CONSTVariables_T* cv);
    initCONSTVariables(&CONSTVariables);
  }

  {
    extern void App_EE_Init(void);
    App_EE_Init();
  }

  eagle_EVSR24_initialize();
  App_Startup();

  /* CAN Bus Initializations */
  pre_start_CAN_CAN1();                /* <Root>/raptor_can_def */
  swsh_caninit_user (0, &can_init[0]);
  post_start_CAN_CAN1();               /* <Root>/raptor_can_def */
  Xcp_Initialize();
  swsh_Write_LSFRiSwitch(21, 0);
  swsh_Write_LSFRiSwitch(22, 0);
}

#define STOP_SECTION_Task_oem_rini
#include "swsh_rb2oem.h"
#define START_SECTION_Task_oem_r1ms
#include "swsh_rb2oem.h"

void NE_1ms(void)
{
  can_process_CAN1();                  /* <Root>/raptor_can_def */
}

#define STOP_SECTION_Task_oem_r1ms
#include "swsh_rb2oem.h"
#define START_SECTION_Task_oem_r5ms
#include "swsh_rb2oem.h"

void NE_5ms(void)
{
  Thread_Foreground(0);
  if (!app_is_in_shutdown) {
    eagle_EVSR24_step();

    /* Get model outputs here */
  }
}

#define STOP_SECTION_Task_oem_r5ms
#include "swsh_rb2oem.h"
#define START_SECTION_Task_oem_r10ms
#include "swsh_rb2oem.h"

void NE_10ms(void)
{
}

#define STOP_SECTION_Task_oem_r10ms
#include "swsh_rb2oem.h"
#define START_SECTION_Task_oem_r20ms
#include "swsh_rb2oem.h"

void NE_20ms(void)
{
}

#define STOP_SECTION_Task_oem_r20ms
#include "swsh_rb2oem.h"
#define START_SECTION_Task_oem_r50ms
#include "swsh_rb2oem.h"

void NE_50ms(void)
{
  Thread_Background(0);
}

#define STOP_SECTION_Task_oem_r50ms
#include "swsh_rb2oem.h"
#define START_SECTION_Task_oem_r100ms
#include "swsh_rb2oem.h"

void NE_100ms(void)
{
  swsh_Write_InjCDrv_EndOfStart(InjCDrv_EndOfStart_Data());
  swsh_Write_EndOfStart(EndOfStart_Data());
  swsh_Write_EngineCoolantTemp(255);
  swsh_Write_OverRunFuelCutOff(0);
}

#define STOP_SECTION_Task_oem_r100ms
#include "swsh_rb2oem.h"
#define START_SECTION_Task_oem_r200ms
#include "swsh_rb2oem.h"

uint8 bswStartDiagTestComplete = 255;
void NE_200ms(void)
{
  if (bswStartDiagTestComplete == 255) {
    bswStartDiagTestComplete = 0;
  } else {
    bswStartDiagTestComplete = 1;
  }
}

#define STOP_SECTION_Task_oem_r200ms
#include "swsh_rb2oem.h"
#define START_SECTION_Task_oem_r1000ms
#include "swsh_rb2oem.h"

void NE_1000ms(void)
{
}

#define STOP_SECTION_Task_oem_r1000ms
#include "swsh_rb2oem.h"
#define START_SECTION_Mo_CodeCyclicCheck
#include "mo_pragma.h"

void NE_lvl2(void)
{
  swsh_Write_MonPrtlResp ((uint32) 0xA001A001);
}

#define STOP_SECTION_Mo_CodeCyclicCheck
#include "mo_pragma.h"

const T_processPtrTab NewEagle_ASW_krsyn = { END_TASK };

const T_processPtrTab NewEagle_ASW_syn = { END_TASK };

const T_processPtrTab NewEagle_ASW_ini = { &NE_ini, END_TASK };

const T_processPtrTab NewEagle_ASW_fcmclr = { END_TASK };

const T_processPtrTab NewEagle_ASW1_1ms = { &NE_1ms, END_TASK };

const T_processPtrTab NewEagle_ASW1_5ms = { &NE_5ms, END_TASK };

const T_processPtrTab NewEagle_ASW1_10ms = { &NE_lvl2, &NE_10ms, END_TASK };

const T_processPtrTab NewEagle_ASW1_20ms = { &NE_20ms, END_TASK };

const T_processPtrTab NewEagle_ASW1_50ms = { &NE_50ms, END_TASK };

const T_processPtrTab NewEagle_ASW1_100ms = { &NE_100ms, END_TASK };

const T_processPtrTab NewEagle_ASW1_200ms = { &NE_200ms, END_TASK };

const T_processPtrTab NewEagle_ASW1_1000ms = { &NE_1000ms, END_TASK };

const T_processPtrTab NewEagle_ASW2_1ms = { END_TASK };

const T_processPtrTab NewEagle_ASW2_5ms = { END_TASK };

const T_processPtrTab NewEagle_ASW2_10ms = { END_TASK };

const T_processPtrTab NewEagle_ASW2_20ms = { END_TASK };

const T_processPtrTab NewEagle_ASW2_50ms = { END_TASK };

const T_processPtrTab NewEagle_ASW2_100ms = { END_TASK };

const T_processPtrTab NewEagle_ASW2_1000ms = { END_TASK };

const T_processPtrTab NewEagle_ASW2_200ms = { END_TASK };

const T_processPtrTab NewEagle_ASW3_5ms = { END_TASK };

const T_processPtrTab NewEagle_ASW3_10ms = { END_TASK };

const T_processPtrTab NewEagle_ASW3_20ms = { END_TASK };

const T_processPtrTab NewEagle_ASW3_50ms = { END_TASK };

const T_processPtrTab NewEagle_ASW3_100ms = { END_TASK };

const T_processPtrTab NewEagle_ASW3_200ms = { END_TASK };

const T_processPtrTab NewEagle_ASW3_1000ms = { END_TASK };

const T_processPtrTab NewEagle_ASW_1msSwOff = { &NE_1ms, END_TASK };

const T_processPtrTab NewEagle_ASW_5msSwOff = { &NE_5ms, END_TASK };

const T_processPtrTab NewEagle_ASW_10msSwOff = { &NE_10ms, END_TASK };

const T_processPtrTab NewEagle_ASW_20msSwOff = { &NE_20ms, END_TASK };

const T_processPtrTab NewEagle_ASW_50msSwOff = { &NE_50ms, END_TASK };

const T_processPtrTab NewEagle_ASW_100msSwOff = { &NE_100ms, END_TASK };

const T_processPtrTab NewEagle_ASW_200msSwOff = { &NE_200ms, END_TASK };

const T_processPtrTab NewEagle_ASW_1000msSwOff = { &NE_1000ms, END_TASK };

/*Dummy definitions for CB functions*/
uint8 NewEagle_SeedKey(uint8* seed, uint8* TstrKey, uint8 length)
{
  UNUSED(seed);
  UNUSED(TstrKey);
  UNUSED(length);
  return (0x00);
}

bool NewEagle_PreCond (void)
{
  return (TRUE);
}

uint8 swsh_Write_KnCDrv_SensorDiagReq(void)
{
  return (0);
}

uint8 swsh_Write_KnCDrv_KnockSensorNumber (uint8 cylkr)
{
  UNUSED(cylkr);
  return (0);
}

uint8 swsh_Write_KnCDrv_AmplificationFactor(uint8 cylkr)
{
  UNUSED(cylkr);
  return (1);
}

sint16 swsh_Write_KnCDrv_MeasureWindowBegin(void)
{
  return (0);
}

sint16 swsh_Write_KnCDrv_MeasureWindowLength(void)
{
  return (2000);
}

sint16 swsh_Write_KnCDrv_FilterSelection(uint8 cylkr)
{
  UNUSED(cylkr);
  return (0);
}

/*LIN Callback functions*/
void Lin_RxUserCallback(uint8 numId, uint8 *data_pa)
{
  UNUSED(numId);
  UNUSED(data_pa);
}

void Lin_TxUserCallback(uint8 numId, uint8 *data_pa)
{
  UNUSED(numId);
  UNUSED(data_pa);
}

void Lin_ErrorUserCallback(uint8 numId, uint8 *data_pa)
{
  UNUSED(numId);
  UNUSED(data_pa);
}

void Lin_WakeUpErrorUser_Callback(uint8 numnodeId)
{
  UNUSED(numnodeId);
}
