/*****************************************************************************
   can_CAN1.h
   Generated By:
   Raptor 2023a_2.0.15039 (7682)
   Matlab (R2022b) 9.13

   Copyright (c) 2023 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Tue Oct 17 21:06:40 2023
 *****************************************************************************/

#ifndef __CAN_CAN1_H
#define __CAN_CAN1_H

/*  CAN Bus : CAN1 	*/
/*  Resource: CAN1 	*/
/*  Bus Enum: CAN_BUS_A */
/* Baud Rate: 500k 	*/

/* FUNCTION PROTOTYPES */
/* CAN initialization */
extern void pre_start_CAN_CAN1(void);
extern void post_start_CAN_CAN1(void);
extern void can_process_CAN1(void);
extern void can_errorCheck_CAN1(void);
extern void CAN1_TX_Queue_Get_Status(uint8_T* queueSize, uint8_T* depth, uint8_T*
  maxDepth, uint32_T* overruns );
extern void CAN1_RX_Queue_Get_Status(uint8_T* queueSize, uint8_T* depth, uint8_T*
  maxDepth, uint32_T* overruns );

/* Receive CAN object declarations */
extern uint8_T can_get_9068__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_9067__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_9069__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_9025__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern uint8_T can_get_9051__0001(uint16_T *age, uint32_T* id, uint8_T* extended,
  uint8_T *data, uint8_T length);
extern void can_init_rxIdRxTrig_XCP_BC_XCP1(uint32_T id, uint8_T extended);
extern uint32_T RxTrig_XCP_BC_XCP1_msgID;
extern uint8_T RxTrig_XCP_BC_XCP1_msgExtended;
extern uint8_T can_get_RxTrig_XCP_BC_XCP1(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length);
extern void can_init_rxIdRxTrig_XCP_CMD_XCP1(uint32_T id, uint8_T extended);
extern uint32_T RxTrig_XCP_CMD_XCP1_msgID;
extern uint8_T RxTrig_XCP_CMD_XCP1_msgExtended;
extern uint8_T can_get_RxTrig_XCP_CMD_XCP1(uint16_T *age, uint32_T* id, uint8_T*
  extended, uint8_T *data, uint8_T length);
extern void can_update_CAN1(uint32_T id, uint8_T extended, uint8_T length, const
  uint8_T *data);

/* Transmit CAN object declarations */
extern void can_send_6920__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_send_6902__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_send_6903__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_send_6901__0002(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_send_6931__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_send_6932__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_send_6930__0001(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_send_Tx_XCP_XCP1(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);

#endif
