/*****************************************************************************
   raptor_types.h
   Generated By:
   Raptor 2023a_2.0.15039 (7682)
   Matlab (R2022b) 9.13

   Copyright (c) 2023 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Tue Oct 17 21:06:40 2023
 *****************************************************************************/

#ifndef RAPTOR_TYPES_H
#define RAPTOR_TYPES_H
#include "rtwtypes.h"
#include "EVSR24_types.h"
#ifndef NULL
#define NULL                           (0)
#endif
#endif
