/*****************************************************************************
   raptor_time.h
   Generated By:
   Raptor 2023a_2.0.15039 (7682)
   Matlab (R2022b) 9.13

   Copyright (c) 2023 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Tue Oct 17 21:06:40 2023
 *****************************************************************************/

#include "rtwtypes.h"

extern uint32_T raptor_GetDeltaTime_us(uint32_T*);
extern uint32_T raptor_GetDeltaTime_ms(uint32_T*);
extern uint32_T raptor_ticks(void);
