/*****************************************************************************
   time.h
   Generated By:
   Raptor 2023a_2.0.15039 (7682)
   Matlab (R2022b) 9.13

   Copyright (c) 2023 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Tue Oct 17 21:06:40 2023
 *****************************************************************************/

#ifndef TIME_H
#define TIME_H

uint32_T raptor_ticks(void);
uint32_T ticks_i(void);
uint32_T raptor_ticks_us(void);
uint32_T ticks_us_i(void);

#endif
