/*****************************************************************************
   raptor_types.h
   Generated By:
   Raptor 2022b_1.1.14772 (6969)
   Matlab (R2022b) 9.13

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Feb 22 21:12:12 2023
 *****************************************************************************/

#ifndef RAPTOR_TYPES_H
#define RAPTOR_TYPES_H
#include "rtwtypes.h"
#include "eagle_EVSR24_types.h"
#ifndef NULL
#define NULL                           (0)
#endif
#endif
