/********************************************************************************
FILE:         d2ctr_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _D2CTR_MSG_H
#define _D2CTR_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __CTRERF1_EXT__
#define __CTRERF1_EXT__
extern uint16 ctrerf1;
#endif /* __CTRERF1_EXT__ */

#ifndef __CTRERFK1_EXT__
#define __CTRERFK1_EXT__
extern uint16 ctrerfk1;
#endif /* __CTRERFK1_EXT__ */

#ifndef __CTRRDY1_EXT__
#define __CTRRDY1_EXT__
extern uint16 ctrrdy1;
#endif /* __CTRRDY1_EXT__ */

#ifndef __CTRSFP_EXT__
#define __CTRSFP_EXT__
extern uint16 ctrsfp;
#endif /* __CTRSFP_EXT__ */

#ifndef __CTRZYF0_EXT__
#define __CTRZYF0_EXT__
extern uint16 ctrzyf0;
#endif /* __CTRZYF0_EXT__ */

#ifndef __CTRZYF1_EXT__
#define __CTRZYF1_EXT__
extern uint16 ctrzyf1;
#endif /* __CTRZYF1_EXT__ */

#ifndef __B_SYSERR_EXT__
#define __B_SYSERR_EXT__
extern bool                     B_syserr;
#endif /* __B_SYSERR_EXT__ */

#ifndef __B_SYSERRK_EXT__
#define __B_SYSERRK_EXT__
extern bool                     B_syserrk;
#endif /* __B_SYSERRK_EXT__ */

#ifndef __B_TRIP_EXT__
#define __B_TRIP_EXT__
extern bool                     B_trip;
#endif /* __B_TRIP_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_B_syserr 
#define SET_B_syserr (B_syserr=TRUE)
#endif
#ifndef CLR_B_syserr 
#define CLR_B_syserr (B_syserr=FALSE)
#endif
#ifndef GET_B_syserr 
#define GET_B_syserr (B_syserr)
#endif
#ifndef PUT_B_syserr 
#define PUT_B_syserr(val) ((val) ? SET_B_syserr : CLR_B_syserr)
#endif


#ifndef SET_B_syserrk 
#define SET_B_syserrk (B_syserrk=TRUE)
#endif
#ifndef CLR_B_syserrk 
#define CLR_B_syserrk (B_syserrk=FALSE)
#endif
#ifndef GET_B_syserrk 
#define GET_B_syserrk (B_syserrk)
#endif
#ifndef PUT_B_syserrk 
#define PUT_B_syserrk(val) ((val) ? SET_B_syserrk : CLR_B_syserrk)
#endif


#ifndef SET_B_trip 
#define SET_B_trip (B_trip=TRUE)
#endif
#ifndef CLR_B_trip 
#define CLR_B_trip (B_trip=FALSE)
#endif
#ifndef GET_B_trip 
#define GET_B_trip (B_trip)
#endif
#ifndef PUT_B_trip 
#define PUT_B_trip(val) ((val) ? SET_B_trip : CLR_B_trip)
#endif

#endif
