/*****************************************************************************
   faultmanager.h
   Generated By:
   Raptor 2023a_2.0.15039 (7682)
   Matlab (R2022b) 9.13

   Copyright (c) 2023 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Tue Oct 17 21:06:40 2023
 *****************************************************************************/

#ifndef __FAULTMANAGER_H
#define __FAULTMANAGER_H
#include "rtwtypes.h"
#define FAULT_NOTOCCURRED_MASK         0x01U
#define FAULT_SUSPECTED_MASK           0x02U
#define FAULT_ACTIVE_MASK              0x04U
#define FAULT_OCCURRED_MASK            0x08U
#define FAULT_ACTIVEATSHUTDOWN_MASK    0x10U

typedef enum {
  FAULT_NONE = 0,
  FAULT_NOTOCCURRED = 1,
  FAULT_SUSPECTED = 2,
  FAULT_ACTIVE = 4,
  FAULT_OCCURRED = 8,
  FAULT_ACTIVEATSHUTDOWN = 16,
  FAULT_CLEAR = 32,
} E_FaultState;

typedef enum {
  FLTEVT_NONE = 0x00,
  FLTEVT_RISENOTOCCURRED = 0x01,
  FLTEVT_FALLNOTOCCURRED = 0x02,
  FLTEVT_RISESUSPECTED = 0x04,
  FLTEVT_FALLSUSPECTED = 0x08,
  FLTEVT_RISEACTIVE = 0x10,
  FLTEVT_FALLACTIVE = 0x20,
  FLTEVT_RISEOCCURRED = 0x40,
  FLTEVT_FALLOCCURRED = 0x80,
} E_FaultEvent;

typedef enum {
  FLTOP_NOTHING,
  FLTOP_FALSE,
  FLTOP_TRUE,
} E_FaultOperation;

#ifndef FM_UNUSED
#define FM_UNUSED(x)                   (void)x
#endif                                 /* FM_UNUSED */

void updateFaultInput(int16_T faultIdx, boolean_T inSample, uint32_T xLimit,
                      uint32_T yLimit, boolean_T sticky);
void initFaultManager(void);
void clearFaults(void);
void clearFault(int16_T faultIdx);
boolean_T getFaultState(int16_T faultIdx, E_FaultState state);
int16_T getNextFaultByAction(int16_T action, int16_T startIdx);
int16_T getNextFaultByState(E_FaultState state, boolean_T onlyEmissRelated,
  int16_T startIdx);
int16_T getNextFault(int16_T startIdx);
uint16_T getFaultStateCount(E_FaultState state);
void setOccurredState(int16_T faultIdx, boolean_T nextValue);
void setActiveState(int16_T faultIdx, boolean_T nextValue);
void setSuspectedState(int16_T faultIdx, boolean_T nextValue);
void setActiveAtShutdownState(int16_T faultIdx, boolean_T nextValue);
boolean_T getFaultActionState(int16_T action);
boolean_T getFaultPersistent(int16_T faultIdx);
boolean_T getFaultSticky(int16_T faultIdx);
E_FaultOperation getFaultOperation(int16_T faultIdx);

/* Fault Idx, Fault Name, X Limit Initial Value, Y Limit Initial Value
   1	IN_appsError_bool 25U 50U
   2	IN_brakeErrorF_bool 25U 50U
   3	IN_brakeErrorR_bool 25U 50U
   4	IN_brakeVHighF_bool 25U 50U
   5	IN_brakeVHighR_bool 25U 50U
   6	IN_brakeVLowF_bool 25U 50U
   7	IN_brakeVLowR_bool 25U 50U
   8	IN_bspdBrakeError_bool 25U 50U
   9	IN_bspdStatusError_bool 25U 50U
   10	IN_coolantTempErrorInverterIn_bool 25U 50U
   11	IN_coolantTempErrorInverterOut_bool 25U 50U
   12	IN_coolantTempErrorMotorIn_bool 25U 50U
   13	IN_coolantTempVHighInverterIn_bool 25U 50U
   14	IN_coolantTempVHighInverterOut_bool 25U 50U
   15	IN_coolantTempVHighMotorIn_bool 25U 50U
   16	IN_coolantTempVLowInverterIn_bool 25U 50U
   17	IN_coolantTempVLowInverterOut_bool 25U 50U
   18	IN_coolantTempVLowMotorIn_bool 25U 50U
   19	IN_hallEffectErrorFL_bool 25U 50U
   20	IN_hallEffectErrorFR_bool 25U 50U
   21	IN_hallEffectErrorRL_bool 25U 50U
   22	IN_hallEffectErrorRR_bool 25U 50U
   23	IN_hallEffectVHighFL_bool 25U 50U
   24	IN_hallEffectVHighFR_bool 25U 50U
   25	IN_hallEffectVHighRL_bool 25U 50U
   26	IN_hallEffectVHighRR_bool 25U 50U
   27	IN_hallEffectVLowFL_bool 25U 50U
   28	IN_hallEffectVLowFR_bool 25U 50U
   29	IN_hallEffectVLowRL_bool 25U 50U
   30	IN_hallEffectVLowRR_bool 25U 50U
   31	IN_rotorTempErrorFL_bool 25U 50U
   32	IN_rotorTempErrorFR_bool 25U 50U
   33	IN_rotorTempErrorRL_bool 25U 50U
   34	IN_rotorTempErrorRR_bool 25U 50U
   35	IN_rotorTempVHighFL_bool 25U 50U
   36	IN_rotorTempVHighFR_bool 25U 50U
   37	IN_rotorTempVHighRL_bool 25U 50U
   38	IN_rotorTempVHighRR_bool 25U 50U
   39	IN_rotorTempVLowFL_bool 25U 50U
   40	IN_rotorTempVLowFR_bool 25U 50U
   41	IN_rotorTempVLowRL_bool 25U 50U
   42	IN_rotorTempVLowRR_bool 25U 50U
   43	IN_throttleError1_bool 25U 50U
   44	IN_throttleError2_bool 25U 50U
   45	IN_throttleVHigh1_bool 25U 50U
   46	IN_throttleVHigh2_bool 25U 50U
   47	IN_throttleVLow1_bool 25U 50U
   48	IN_throttleVLow2_bool 25U 50U
   49	IN_tireTempErrorFLI_bool 25U 50U
   50	IN_tireTempErrorFLM_bool 25U 50U
   51	IN_tireTempErrorFLO_bool 25U 50U
   52	IN_tireTempErrorFRI_bool 25U 50U
   53	IN_tireTempErrorFRM_bool 25U 50U
   54	IN_tireTempErrorFRO_bool 25U 50U
   55	IN_tireTempErrorRLI_bool 25U 50U
   56	IN_tireTempErrorRLM_bool 25U 50U
   57	IN_tireTempErrorRLO_bool 25U 50U
   58	IN_tireTempErrorRRI_bool 25U 50U
   59	IN_tireTempErrorRRM_bool 25U 50U
   60	IN_tireTempErrorRRO_bool 25U 50U
   61	IN_tireTempVHighFLI_bool 25U 50U
   62	IN_tireTempVHighFLM_bool 25U 50U
   63	IN_tireTempVHighFLO_bool 25U 50U
   64	IN_tireTempVHighFRI_bool 25U 50U
   65	IN_tireTempVHighFRM_bool 25U 50U
   66	IN_tireTempVHighFRO_bool 25U 50U
   67	IN_tireTempVHighRLI_bool 25U 50U
   68	IN_tireTempVHighRLM_bool 25U 50U
   69	IN_tireTempVHighRLO_bool 25U 50U
   70	IN_tireTempVHighRRI_bool 25U 50U
   71	IN_tireTempVHighRRM_bool 25U 50U
   72	IN_tireTempVHighRRO_bool 25U 50U
   73	IN_tireTempVLowFLI_bool 25U 50U
   74	IN_tireTempVLowFLM_bool 25U 50U
   75	IN_tireTempVLowFLO_bool 25U 50U
   76	IN_tireTempVLowFRI_bool 25U 50U
   77	IN_tireTempVLowFRM_bool 25U 50U
   78	IN_tireTempVLowFRO_bool 25U 50U
   79	IN_tireTempVLowRLI_bool 25U 50U
   80	IN_tireTempVLowRLM_bool 25U 50U
   81	IN_tireTempVLowRLO_bool 25U 50U
   82	IN_tireTempVLowRRI_bool 25U 50U
   83	IN_tireTempVLowRRM_bool 25U 50U
   84	IN_tireTempVLowRRO_bool 25U 50U
 */
#endif
