/********************************************************************************
FILE:         swadp_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _SWADP_MSG_H
#define _SWADP_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __CRCTL_VDES_EXT__
#define __CRCTL_VDES_EXT__
extern sint16 CrCtl_vDes;
#endif /* __CRCTL_VDES_EXT__ */

#ifndef __EXHMOD_TWALLS1B1_EXT__
#define __EXHMOD_TWALLS1B1_EXT__
extern sint16 ExhMod_tWallS1B1;
#endif /* __EXHMOD_TWALLS1B1_EXT__ */

#ifndef __EXHMOD_TWALLS1B2_EXT__
#define __EXHMOD_TWALLS1B2_EXT__
extern sint16 ExhMod_tWallS1B2;
#endif /* __EXHMOD_TWALLS1B2_EXT__ */

#ifndef __FAN_R_EXT__
#define __FAN_R_EXT__
extern sint16 Fan_r;
#endif /* __FAN_R_EXT__ */

#ifndef __SPDGOV_ST_EXT__
#define __SPDGOV_ST_EXT__
extern uint16 SpdGov_st;
#endif /* __SPDGOV_ST_EXT__ */

#ifndef __AIRSYS_BCASEDGADAPEXH_EXT__
#define __AIRSYS_BCASEDGADAPEXH_EXT__
extern _bit                     AirSys_bCaSEdgAdapExh;
#endif /* __AIRSYS_BCASEDGADAPEXH_EXT__ */

#ifndef __AIRSYS_BCASEDGADAPINTK_EXT__
#define __AIRSYS_BCASEDGADAPINTK_EXT__
extern _bit                     AirSys_bCaSEdgAdapIntk;
#endif /* __AIRSYS_BCASEDGADAPINTK_EXT__ */

#ifndef __BASSVR_BFUNCTSTREQ_EXT__
#define __BASSVR_BFUNCTSTREQ_EXT__
extern _bit                     BasSvr_bFuncTstReq;
#endif /* __BASSVR_BFUNCTSTREQ_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_AirSys_bCaSEdgAdapExh 
#define SET_AirSys_bCaSEdgAdapExh (AirSys_bCaSEdgAdapExh=TRUE)
#endif
#ifndef CLR_AirSys_bCaSEdgAdapExh 
#define CLR_AirSys_bCaSEdgAdapExh (AirSys_bCaSEdgAdapExh=FALSE)
#endif
#ifndef GET_AirSys_bCaSEdgAdapExh 
#define GET_AirSys_bCaSEdgAdapExh (AirSys_bCaSEdgAdapExh)
#endif
#ifndef PUT_AirSys_bCaSEdgAdapExh 
#define PUT_AirSys_bCaSEdgAdapExh(val) ((val) ? SET_AirSys_bCaSEdgAdapExh : CLR_AirSys_bCaSEdgAdapExh)
#endif


#ifndef SET_AirSys_bCaSEdgAdapIntk 
#define SET_AirSys_bCaSEdgAdapIntk (AirSys_bCaSEdgAdapIntk=TRUE)
#endif
#ifndef CLR_AirSys_bCaSEdgAdapIntk 
#define CLR_AirSys_bCaSEdgAdapIntk (AirSys_bCaSEdgAdapIntk=FALSE)
#endif
#ifndef GET_AirSys_bCaSEdgAdapIntk 
#define GET_AirSys_bCaSEdgAdapIntk (AirSys_bCaSEdgAdapIntk)
#endif
#ifndef PUT_AirSys_bCaSEdgAdapIntk 
#define PUT_AirSys_bCaSEdgAdapIntk(val) ((val) ? SET_AirSys_bCaSEdgAdapIntk : CLR_AirSys_bCaSEdgAdapIntk)
#endif


#ifndef SET_BasSvr_bFuncTstReq 
#define SET_BasSvr_bFuncTstReq (BasSvr_bFuncTstReq=TRUE)
#endif
#ifndef CLR_BasSvr_bFuncTstReq 
#define CLR_BasSvr_bFuncTstReq (BasSvr_bFuncTstReq=FALSE)
#endif
#ifndef GET_BasSvr_bFuncTstReq 
#define GET_BasSvr_bFuncTstReq (BasSvr_bFuncTstReq)
#endif
#ifndef PUT_BasSvr_bFuncTstReq 
#define PUT_BasSvr_bFuncTstReq(val) ((val) ? SET_BasSvr_bFuncTstReq : CLR_BasSvr_bFuncTstReq)
#endif

#endif
