/********************************************************************************
FILE:         uego_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _UEGO_MSG_H
#define _UEGO_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __EPMCRS_TISEG_EXT__
#define __EPMCRS_TISEG_EXT__
extern sint32 EpmCrS_tiSeg;
#endif /* __EPMCRS_TISEG_EXT__ */

#ifndef __UEGO_STLSMERRINFODIAGREGS1B1_EXT__
#define __UEGO_STLSMERRINFODIAGREGS1B1_EXT__
extern uint32 UEGO_stLsmErrInfoDiagRegS1B1;
#endif /* __UEGO_STLSMERRINFODIAGREGS1B1_EXT__ */

#ifndef __UEGO_STLSMERRINFODIAGREGS1B2_EXT__
#define __UEGO_STLSMERRINFODIAGREGS1B2_EXT__
extern uint32 UEGO_stLsmErrInfoDiagRegS1B2;
#endif /* __UEGO_STLSMERRINFODIAGREGS1B2_EXT__ */

#ifndef __EPM_NENG_EXT__
#define __EPM_NENG_EXT__
extern sint16 Epm_nEng;
#endif /* __EPM_NENG_EXT__ */

#ifndef __EXHMOD_TWALLS1B1_EXT__
#define __EXHMOD_TWALLS1B1_EXT__
extern sint16 ExhMod_tWallS1B1;
#endif /* __EXHMOD_TWALLS1B1_EXT__ */

#ifndef __EXHMOD_TWALLS1B2_EXT__
#define __EXHMOD_TWALLS1B2_EXT__
extern sint16 ExhMod_tWallS1B2;
#endif /* __EXHMOD_TWALLS1B2_EXT__ */

#ifndef __UEGO_IIPMPELECCORRDS1B1_EXT__
#define __UEGO_IIPMPELECCORRDS1B1_EXT__
extern sint16 UEGO_iIPmpElecCorrdS1B1;
#endif /* __UEGO_IIPMPELECCORRDS1B1_EXT__ */

#ifndef __UEGO_IIPMPELECCORRDS1B2_EXT__
#define __UEGO_IIPMPELECCORRDS1B2_EXT__
extern sint16 UEGO_iIPmpElecCorrdS1B2;
#endif /* __UEGO_IIPMPELECCORRDS1B2_EXT__ */

#ifndef __UEGO_IIPMPPACARYS1B1_EXT__
#define __UEGO_IIPMPPACARYS1B1_EXT__
extern sint16 UEGO_iIPmpPacAryS1B1[15];
#endif /* __UEGO_IIPMPPACARYS1B1_EXT__ */

#ifndef __UEGO_IIPMPPACARYS1B2_EXT__
#define __UEGO_IIPMPPACARYS1B2_EXT__
extern sint16 UEGO_iIPmpPacAryS1B2[15];
#endif /* __UEGO_IIPMPPACARYS1B2_EXT__ */

#ifndef __UEGO_IIPMPPACAVRGS1B1_EXT__
#define __UEGO_IIPMPPACAVRGS1B1_EXT__
extern sint16 UEGO_iIPmpPacAvrgS1B1;
#endif /* __UEGO_IIPMPPACAVRGS1B1_EXT__ */

#ifndef __UEGO_IIPMPPACAVRGS1B2_EXT__
#define __UEGO_IIPMPPACAVRGS1B2_EXT__
extern sint16 UEGO_iIPmpPacAvrgS1B2;
#endif /* __UEGO_IIPMPPACAVRGS1B2_EXT__ */

#ifndef __UEGO_IIPMPRAWLSTS1B1_EXT__
#define __UEGO_IIPMPRAWLSTS1B1_EXT__
extern sint16 UEGO_iIPmpRawLstS1B1;
#endif /* __UEGO_IIPMPRAWLSTS1B1_EXT__ */

#ifndef __UEGO_IIPMPRAWLSTS1B2_EXT__
#define __UEGO_IIPMPRAWLSTS1B2_EXT__
extern sint16 UEGO_iIPmpRawLstS1B2;
#endif /* __UEGO_IIPMPRAWLSTS1B2_EXT__ */

#ifndef __UEGO_IIPMPRVSCHRGS1B1_EXT__
#define __UEGO_IIPMPRVSCHRGS1B1_EXT__
extern sint16 UEGO_iIPmpRvsChrgS1B1[15];
#endif /* __UEGO_IIPMPRVSCHRGS1B1_EXT__ */

#ifndef __UEGO_IIPMPRVSCHRGS1B2_EXT__
#define __UEGO_IIPMPRVSCHRGS1B2_EXT__
extern sint16 UEGO_iIPmpRvsChrgS1B2[15];
#endif /* __UEGO_IIPMPRVSCHRGS1B2_EXT__ */

#ifndef __UEGO_IIPMPSEGWOCRVS1B1_EXT__
#define __UEGO_IIPMPSEGWOCRVS1B1_EXT__
extern sint16 UEGO_iIPmpSegWoCrvS1B1;
#endif /* __UEGO_IIPMPSEGWOCRVS1B1_EXT__ */

#ifndef __UEGO_IIPMPSEGWOCRVS1B2_EXT__
#define __UEGO_IIPMPSEGWOCRVS1B2_EXT__
extern sint16 UEGO_iIPmpSegWoCrvS1B2;
#endif /* __UEGO_IIPMPSEGWOCRVS1B2_EXT__ */

#ifndef __UEGO_IISQMEASS1B1_EXT__
#define __UEGO_IISQMEASS1B1_EXT__
extern sint16 UEGO_iIsqMeasS1B1;
#endif /* __UEGO_IISQMEASS1B1_EXT__ */

#ifndef __UEGO_IISQMEASS1B2_EXT__
#define __UEGO_IISQMEASS1B2_EXT__
extern sint16 UEGO_iIsqMeasS1B2;
#endif /* __UEGO_IISQMEASS1B2_EXT__ */

#ifndef __UEGO_IISQREGDESS1B1_EXT__
#define __UEGO_IISQREGDESS1B1_EXT__
extern sint16 UEGO_iIsqRegDesS1B1;
#endif /* __UEGO_IISQREGDESS1B1_EXT__ */

#ifndef __UEGO_IISQREGDESS1B2_EXT__
#define __UEGO_IISQREGDESS1B2_EXT__
extern sint16 UEGO_iIsqRegDesS1B2;
#endif /* __UEGO_IISQREGDESS1B2_EXT__ */

#ifndef __UEGO_IISQRMEASS1B1_EXT__
#define __UEGO_IISQRMEASS1B1_EXT__
extern sint16 UEGO_iIsqrMeasS1B1;
#endif /* __UEGO_IISQRMEASS1B1_EXT__ */

#ifndef __UEGO_IISQRMEASS1B2_EXT__
#define __UEGO_IISQRMEASS1B2_EXT__
extern sint16 UEGO_iIsqrMeasS1B2;
#endif /* __UEGO_IISQRMEASS1B2_EXT__ */

#ifndef __UEGO_IISQRREGDESS1B1_EXT__
#define __UEGO_IISQRREGDESS1B1_EXT__
extern sint16 UEGO_iIsqrRegDesS1B1;
#endif /* __UEGO_IISQRREGDESS1B1_EXT__ */

#ifndef __UEGO_IISQRREGDESS1B2_EXT__
#define __UEGO_IISQRREGDESS1B2_EXT__
extern sint16 UEGO_iIsqrRegDesS1B2;
#endif /* __UEGO_IISQRREGDESS1B2_EXT__ */

#ifndef __UEGO_NUMUNSETTEST_EXT__
#define __UEGO_NUMUNSETTEST_EXT__
extern sint16 UEGO_numUnsetTest;
#endif /* __UEGO_NUMUNSETTEST_EXT__ */

#ifndef __UEGO_NUMUOFFGND1S1B1_EXT__
#define __UEGO_NUMUOFFGND1S1B1_EXT__
extern sint16 UEGO_numUoffgnd1S1B1;
#endif /* __UEGO_NUMUOFFGND1S1B1_EXT__ */

#ifndef __UEGO_NUMUOFFGND1S1B2_EXT__
#define __UEGO_NUMUOFFGND1S1B2_EXT__
extern sint16 UEGO_numUoffgnd1S1B2;
#endif /* __UEGO_NUMUOFFGND1S1B2_EXT__ */

#ifndef __UEGO_NUMUOFFGND2S1B1_EXT__
#define __UEGO_NUMUOFFGND2S1B1_EXT__
extern sint16 UEGO_numUoffgnd2S1B1;
#endif /* __UEGO_NUMUOFFGND2S1B1_EXT__ */

#ifndef __UEGO_NUMUOFFGND2S1B2_EXT__
#define __UEGO_NUMUOFFGND2S1B2_EXT__
extern sint16 UEGO_numUoffgnd2S1B2;
#endif /* __UEGO_NUMUOFFGND2S1B2_EXT__ */

#ifndef __UEGO_NUMUOFFGND3S1B1_EXT__
#define __UEGO_NUMUOFFGND3S1B1_EXT__
extern sint16 UEGO_numUoffgnd3S1B1;
#endif /* __UEGO_NUMUOFFGND3S1B1_EXT__ */

#ifndef __UEGO_NUMUOFFGND3S1B2_EXT__
#define __UEGO_NUMUOFFGND3S1B2_EXT__
extern sint16 UEGO_numUoffgnd3S1B2;
#endif /* __UEGO_NUMUOFFGND3S1B2_EXT__ */

#ifndef __UEGO_NUMUOFFIPE1Z1S1B1_EXT__
#define __UEGO_NUMUOFFIPE1Z1S1B1_EXT__
extern sint16 UEGO_numUoffipe1Z1S1B1;
#endif /* __UEGO_NUMUOFFIPE1Z1S1B1_EXT__ */

#ifndef __UEGO_NUMUOFFIPE1Z1S1B2_EXT__
#define __UEGO_NUMUOFFIPE1Z1S1B2_EXT__
extern sint16 UEGO_numUoffipe1Z1S1B2;
#endif /* __UEGO_NUMUOFFIPE1Z1S1B2_EXT__ */

#ifndef __UEGO_NUMUOFFIPE1Z2S1B1_EXT__
#define __UEGO_NUMUOFFIPE1Z2S1B1_EXT__
extern sint16 UEGO_numUoffipe1Z2S1B1;
#endif /* __UEGO_NUMUOFFIPE1Z2S1B1_EXT__ */

#ifndef __UEGO_NUMUOFFIPE1Z2S1B2_EXT__
#define __UEGO_NUMUOFFIPE1Z2S1B2_EXT__
extern sint16 UEGO_numUoffipe1Z2S1B2;
#endif /* __UEGO_NUMUOFFIPE1Z2S1B2_EXT__ */

#ifndef __UEGO_NUMUOFFIPE2Z1S1B1_EXT__
#define __UEGO_NUMUOFFIPE2Z1S1B1_EXT__
extern sint16 UEGO_numUoffipe2Z1S1B1;
#endif /* __UEGO_NUMUOFFIPE2Z1S1B1_EXT__ */

#ifndef __UEGO_NUMUOFFIPE2Z1S1B2_EXT__
#define __UEGO_NUMUOFFIPE2Z1S1B2_EXT__
extern sint16 UEGO_numUoffipe2Z1S1B2;
#endif /* __UEGO_NUMUOFFIPE2Z1S1B2_EXT__ */

#ifndef __UEGO_NUMUOFFIPE2Z2S1B1_EXT__
#define __UEGO_NUMUOFFIPE2Z2S1B1_EXT__
extern sint16 UEGO_numUoffipe2Z2S1B1;
#endif /* __UEGO_NUMUOFFIPE2Z2S1B1_EXT__ */

#ifndef __UEGO_NUMUOFFIPE2Z2S1B2_EXT__
#define __UEGO_NUMUOFFIPE2Z2S1B2_EXT__
extern sint16 UEGO_numUoffipe2Z2S1B2;
#endif /* __UEGO_NUMUOFFIPE2Z2S1B2_EXT__ */

#ifndef __UEGO_NUMUOFFVCC1S1B1_EXT__
#define __UEGO_NUMUOFFVCC1S1B1_EXT__
extern sint16 UEGO_numUoffvcc1S1B1;
#endif /* __UEGO_NUMUOFFVCC1S1B1_EXT__ */

#ifndef __UEGO_NUMUOFFVCC1S1B2_EXT__
#define __UEGO_NUMUOFFVCC1S1B2_EXT__
extern sint16 UEGO_numUoffvcc1S1B2;
#endif /* __UEGO_NUMUOFFVCC1S1B2_EXT__ */

#ifndef __UEGO_NUMUOFFVCC2S1B1_EXT__
#define __UEGO_NUMUOFFVCC2S1B1_EXT__
extern sint16 UEGO_numUoffvcc2S1B1;
#endif /* __UEGO_NUMUOFFVCC2S1B1_EXT__ */

#ifndef __UEGO_NUMUOFFVCC2S1B2_EXT__
#define __UEGO_NUMUOFFVCC2S1B2_EXT__
extern sint16 UEGO_numUoffvcc2S1B2;
#endif /* __UEGO_NUMUOFFVCC2S1B2_EXT__ */

#ifndef __UEGO_NUMUOFFVCC3S1B1_EXT__
#define __UEGO_NUMUOFFVCC3S1B1_EXT__
extern sint16 UEGO_numUoffvcc3S1B1;
#endif /* __UEGO_NUMUOFFVCC3S1B1_EXT__ */

#ifndef __UEGO_NUMUOFFVCC3S1B2_EXT__
#define __UEGO_NUMUOFFVCC3S1B2_EXT__
extern sint16 UEGO_numUoffvcc3S1B2;
#endif /* __UEGO_NUMUOFFVCC3S1B2_EXT__ */

#ifndef __UEGO_NUMUOFFVCCI2S1B1_EXT__
#define __UEGO_NUMUOFFVCCI2S1B1_EXT__
extern sint16 UEGO_numUoffvcci2S1B1;
#endif /* __UEGO_NUMUOFFVCCI2S1B1_EXT__ */

#ifndef __UEGO_NUMUOFFVCCI2S1B2_EXT__
#define __UEGO_NUMUOFFVCCI2S1B2_EXT__
extern sint16 UEGO_numUoffvcci2S1B2;
#endif /* __UEGO_NUMUOFFVCCI2S1B2_EXT__ */

#ifndef __UEGO_RATIPMPPACARYS1B1_EXT__
#define __UEGO_RATIPMPPACARYS1B1_EXT__
extern sint16 UEGO_ratIPmpPacAryS1B1[16];
#endif /* __UEGO_RATIPMPPACARYS1B1_EXT__ */

#ifndef __UEGO_RATIPMPPACARYS1B2_EXT__
#define __UEGO_RATIPMPPACARYS1B2_EXT__
extern sint16 UEGO_ratIPmpPacAryS1B2[16];
#endif /* __UEGO_RATIPMPPACARYS1B2_EXT__ */

#ifndef __UEGO_TEGMDLS1B1_EXT__
#define __UEGO_TEGMDLS1B1_EXT__
extern sint16 UEGO_tEgMdlS1B1;
#endif /* __UEGO_TEGMDLS1B1_EXT__ */

#ifndef __UEGO_TEGMDLS1B2_EXT__
#define __UEGO_TEGMDLS1B2_EXT__
extern sint16 UEGO_tEgMdlS1B2;
#endif /* __UEGO_TEGMDLS1B2_EXT__ */

#ifndef __UEGO_TWALLMDLS1B1_EXT__
#define __UEGO_TWALLMDLS1B1_EXT__
extern sint16 UEGO_tWallMdlS1B1;
#endif /* __UEGO_TWALLMDLS1B1_EXT__ */

#ifndef __UEGO_TWALLMDLS1B2_EXT__
#define __UEGO_TWALLMDLS1B2_EXT__
extern sint16 UEGO_tWallMdlS1B2;
#endif /* __UEGO_TWALLMDLS1B2_EXT__ */

#ifndef __UEGO_UUMEASMAXLNS1B1_EXT__
#define __UEGO_UUMEASMAXLNS1B1_EXT__
extern sint16 UEGO_uUMeasMaxLNS1B1;
#endif /* __UEGO_UUMEASMAXLNS1B1_EXT__ */

#ifndef __UEGO_UUMEASMAXLNS1B2_EXT__
#define __UEGO_UUMEASMAXLNS1B2_EXT__
extern sint16 UEGO_uUMeasMaxLNS1B2;
#endif /* __UEGO_UUMEASMAXLNS1B2_EXT__ */

#ifndef __UEGO_UUMEASMAXLPS1B1_EXT__
#define __UEGO_UUMEASMAXLPS1B1_EXT__
extern sint16 UEGO_uUMeasMaxLPS1B1;
#endif /* __UEGO_UUMEASMAXLPS1B1_EXT__ */

#ifndef __UEGO_UUMEASMAXLPS1B2_EXT__
#define __UEGO_UUMEASMAXLPS1B2_EXT__
extern sint16 UEGO_uUMeasMaxLPS1B2;
#endif /* __UEGO_UUMEASMAXLPS1B2_EXT__ */

#ifndef __UEGO_UUN0ELECCORRDS1B1_EXT__
#define __UEGO_UUN0ELECCORRDS1B1_EXT__
extern sint16 UEGO_uUn0ElecCorrdS1B1;
#endif /* __UEGO_UUN0ELECCORRDS1B1_EXT__ */

#ifndef __UEGO_UUN0ELECCORRDS1B2_EXT__
#define __UEGO_UUN0ELECCORRDS1B2_EXT__
extern sint16 UEGO_uUn0ElecCorrdS1B2;
#endif /* __UEGO_UUN0ELECCORRDS1B2_EXT__ */

#ifndef __UEGO_UUN0PACARYS1B1_EXT__
#define __UEGO_UUN0PACARYS1B1_EXT__
extern sint16 UEGO_uUn0PacAryS1B1[15];
#endif /* __UEGO_UUN0PACARYS1B1_EXT__ */

#ifndef __UEGO_UUN0PACARYS1B2_EXT__
#define __UEGO_UUN0PACARYS1B2_EXT__
extern sint16 UEGO_uUn0PacAryS1B2[15];
#endif /* __UEGO_UUN0PACARYS1B2_EXT__ */

#ifndef __UEGO_UUN0RAWLSTS1B1_EXT__
#define __UEGO_UUN0RAWLSTS1B1_EXT__
extern sint16 UEGO_uUn0RawLstS1B1;
#endif /* __UEGO_UUN0RAWLSTS1B1_EXT__ */

#ifndef __UEGO_UUN0RAWLSTS1B2_EXT__
#define __UEGO_UUN0RAWLSTS1B2_EXT__
extern sint16 UEGO_uUn0RawLstS1B2;
#endif /* __UEGO_UUN0RAWLSTS1B2_EXT__ */

#ifndef __UEGO_UUP0PACARYS1B1_EXT__
#define __UEGO_UUP0PACARYS1B1_EXT__
extern sint16 UEGO_uUp0PacAryS1B1[15];
#endif /* __UEGO_UUP0PACARYS1B1_EXT__ */

#ifndef __UEGO_UUP0PACARYS1B2_EXT__
#define __UEGO_UUP0PACARYS1B2_EXT__
extern sint16 UEGO_uUp0PacAryS1B2[15];
#endif /* __UEGO_UUP0PACARYS1B2_EXT__ */

#ifndef __SPDGOV_ST_EXT__
#define __SPDGOV_ST_EXT__
extern uint16 SpdGov_st;
#endif /* __SPDGOV_ST_EXT__ */

#ifndef __UEGO_FACRIERIAS1B1_EXT__
#define __UEGO_FACRIERIAS1B1_EXT__
extern uint16 UEGO_facRieRiaS1B1;
#endif /* __UEGO_FACRIERIAS1B1_EXT__ */

#ifndef __UEGO_FACRIERIAS1B2_EXT__
#define __UEGO_FACRIERIAS1B2_EXT__
extern uint16 UEGO_facRieRiaS1B2;
#endif /* __UEGO_FACRIERIAS1B2_EXT__ */

#ifndef __UEGO_FACRIERIPS1B1_EXT__
#define __UEGO_FACRIERIPS1B1_EXT__
extern uint16 UEGO_facRieRipS1B1;
#endif /* __UEGO_FACRIERIPS1B1_EXT__ */

#ifndef __UEGO_FACRIERIPS1B2_EXT__
#define __UEGO_FACRIERIPS1B2_EXT__
extern uint16 UEGO_facRieRipS1B2;
#endif /* __UEGO_FACRIERIPS1B2_EXT__ */

#ifndef __UEGO_MEGFLOWS1B1_EXT__
#define __UEGO_MEGFLOWS1B1_EXT__
extern uint16 UEGO_mEgFlowS1B1;
#endif /* __UEGO_MEGFLOWS1B1_EXT__ */

#ifndef __UEGO_MEGFLOWS1B2_EXT__
#define __UEGO_MEGFLOWS1B2_EXT__
extern uint16 UEGO_mEgFlowS1B2;
#endif /* __UEGO_MEGFLOWS1B2_EXT__ */

#ifndef __UEGO_NUMRAMREGMODES1B1_EXT__
#define __UEGO_NUMRAMREGMODES1B1_EXT__
extern uint16 UEGO_numRamRegModeS1B1;
#endif /* __UEGO_NUMRAMREGMODES1B1_EXT__ */

#ifndef __UEGO_NUMRAMREGMODES1B2_EXT__
#define __UEGO_NUMRAMREGMODES1B2_EXT__
extern uint16 UEGO_numRamRegModeS1B2;
#endif /* __UEGO_NUMRAMREGMODES1B2_EXT__ */

#ifndef __UEGO_RCERS1B1_EXT__
#define __UEGO_RCERS1B1_EXT__
extern uint16 UEGO_rCerS1B1;
#endif /* __UEGO_RCERS1B1_EXT__ */

#ifndef __UEGO_RCERS1B2_EXT__
#define __UEGO_RCERS1B2_EXT__
extern uint16 UEGO_rCerS1B2;
#endif /* __UEGO_RCERS1B2_EXT__ */

#ifndef __UEGO_RRIARAWS1B1_EXT__
#define __UEGO_RRIARAWS1B1_EXT__
extern uint16 UEGO_rRiaRawS1B1;
#endif /* __UEGO_RRIARAWS1B1_EXT__ */

#ifndef __UEGO_RRIARAWS1B2_EXT__
#define __UEGO_RRIARAWS1B2_EXT__
extern uint16 UEGO_rRiaRawS1B2;
#endif /* __UEGO_RRIARAWS1B2_EXT__ */

#ifndef __UEGO_RRIERAWS1B1_EXT__
#define __UEGO_RRIERAWS1B1_EXT__
extern uint16 UEGO_rRieRawS1B1;
#endif /* __UEGO_RRIERAWS1B1_EXT__ */

#ifndef __UEGO_RRIERAWS1B2_EXT__
#define __UEGO_RRIERAWS1B2_EXT__
extern uint16 UEGO_rRieRawS1B2;
#endif /* __UEGO_RRIERAWS1B2_EXT__ */

#ifndef __UEGO_RATLAMRECPRMDLS1B1_EXT__
#define __UEGO_RATLAMRECPRMDLS1B1_EXT__
extern uint16 UEGO_ratLamRecprMdlS1B1;
#endif /* __UEGO_RATLAMRECPRMDLS1B1_EXT__ */

#ifndef __UEGO_RATLAMRECPRMDLS1B2_EXT__
#define __UEGO_RATLAMRECPRMDLS1B2_EXT__
extern uint16 UEGO_ratLamRecprMdlS1B2;
#endif /* __UEGO_RATLAMRECPRMDLS1B2_EXT__ */

#ifndef __UEGO_RESRCODS1B1_EXT__
#define __UEGO_RESRCODS1B1_EXT__
extern uint16 UEGO_resRCodS1B1;
#endif /* __UEGO_RESRCODS1B1_EXT__ */

#ifndef __UEGO_RESRCODS1B2_EXT__
#define __UEGO_RESRCODS1B2_EXT__
extern uint16 UEGO_resRCodS1B2;
#endif /* __UEGO_RESRCODS1B2_EXT__ */

#ifndef __UEGO_RESRPARLS1B1_EXT__
#define __UEGO_RESRPARLS1B1_EXT__
extern uint16 UEGO_resRParlS1B1;
#endif /* __UEGO_RESRPARLS1B1_EXT__ */

#ifndef __UEGO_RESRPARLS1B2_EXT__
#define __UEGO_RESRPARLS1B2_EXT__
extern uint16 UEGO_resRParlS1B2;
#endif /* __UEGO_RESRPARLS1B2_EXT__ */

#ifndef __UEGO_STIPMPTM2RS1B1_EXT__
#define __UEGO_STIPMPTM2RS1B1_EXT__
extern uint16 UEGO_stIPmpTM2RS1B1;
#endif /* __UEGO_STIPMPTM2RS1B1_EXT__ */

#ifndef __UEGO_STIPMPTM2RS1B2_EXT__
#define __UEGO_STIPMPTM2RS1B2_EXT__
extern uint16 UEGO_stIPmpTM2RS1B2;
#endif /* __UEGO_STIPMPTM2RS1B2_EXT__ */

#ifndef __UEGO_TCERS1B1_EXT__
#define __UEGO_TCERS1B1_EXT__
extern uint16 UEGO_tCerS1B1;
#endif /* __UEGO_TCERS1B1_EXT__ */

#ifndef __UEGO_TCERS1B2_EXT__
#define __UEGO_TCERS1B2_EXT__
extern uint16 UEGO_tCerS1B2;
#endif /* __UEGO_TCERS1B2_EXT__ */

#ifndef __COENG_ST_EXT__
#define __COENG_ST_EXT__
extern uint8                    CoEng_st;
#endif /* __COENG_ST_EXT__ */

#ifndef __UEGO_IDXOPTS1B1_EXT__
#define __UEGO_IDXOPTS1B1_EXT__
extern uint8 UEGO_idxOPTS1B1;
#endif /* __UEGO_IDXOPTS1B1_EXT__ */

#ifndef __UEGO_IDXOPTS1B2_EXT__
#define __UEGO_IDXOPTS1B2_EXT__
extern uint8 UEGO_idxOPTS1B2;
#endif /* __UEGO_IDXOPTS1B2_EXT__ */

#ifndef __UEGO_IDXTYPS1B1_EXT__
#define __UEGO_IDXTYPS1B1_EXT__
extern uint8 UEGO_idxTypS1B1;
#endif /* __UEGO_IDXTYPS1B1_EXT__ */

#ifndef __UEGO_IDXTYPS1B2_EXT__
#define __UEGO_IDXTYPS1B2_EXT__
extern uint8 UEGO_idxTypS1B2;
#endif /* __UEGO_IDXTYPS1B2_EXT__ */

#ifndef __UEGO_NRRPCCURRCYCS1B1_EXT__
#define __UEGO_NRRPCCURRCYCS1B1_EXT__
extern uint8 UEGO_nrRpcCurrCycS1B1;
#endif /* __UEGO_NRRPCCURRCYCS1B1_EXT__ */

#ifndef __UEGO_NRRPCCURRCYCS1B2_EXT__
#define __UEGO_NRRPCCURRCYCS1B2_EXT__
extern uint8 UEGO_nrRpcCurrCycS1B2;
#endif /* __UEGO_NRRPCCURRCYCS1B2_EXT__ */

#ifndef __UEGO_NUMDIAGMODCTRLS1B1_EXT__
#define __UEGO_NUMDIAGMODCTRLS1B1_EXT__
extern uint8 UEGO_numDiagModCtrlS1B1;
#endif /* __UEGO_NUMDIAGMODCTRLS1B1_EXT__ */

#ifndef __UEGO_NUMDIAGMODCTRLS1B2_EXT__
#define __UEGO_NUMDIAGMODCTRLS1B2_EXT__
extern uint8 UEGO_numDiagModCtrlS1B2;
#endif /* __UEGO_NUMDIAGMODCTRLS1B2_EXT__ */

#ifndef __UEGO_NUMMODDESS1B1_EXT__
#define __UEGO_NUMMODDESS1B1_EXT__
extern uint8 UEGO_numModDesS1B1;
#endif /* __UEGO_NUMMODDESS1B1_EXT__ */

#ifndef __UEGO_NUMMODDESS1B2_EXT__
#define __UEGO_NUMMODDESS1B2_EXT__
extern uint8 UEGO_numModDesS1B2;
#endif /* __UEGO_NUMMODDESS1B2_EXT__ */

#ifndef __UEGO_NUMMODMEASS1B1_EXT__
#define __UEGO_NUMMODMEASS1B1_EXT__
extern uint8 UEGO_numModMeasS1B1;
#endif /* __UEGO_NUMMODMEASS1B1_EXT__ */

#ifndef __UEGO_NUMMODMEASS1B2_EXT__
#define __UEGO_NUMMODMEASS1B2_EXT__
extern uint8 UEGO_numModMeasS1B2;
#endif /* __UEGO_NUMMODMEASS1B2_EXT__ */

#ifndef __UEGO_NUMMODPROBS1B1_EXT__
#define __UEGO_NUMMODPROBS1B1_EXT__
extern uint8 UEGO_numModProbS1B1;
#endif /* __UEGO_NUMMODPROBS1B1_EXT__ */

#ifndef __UEGO_NUMMODPROBS1B2_EXT__
#define __UEGO_NUMMODPROBS1B2_EXT__
extern uint8 UEGO_numModProbS1B2;
#endif /* __UEGO_NUMMODPROBS1B2_EXT__ */

#ifndef __UEGO_NUMPACBLCKNS1B1_EXT__
#define __UEGO_NUMPACBLCKNS1B1_EXT__
extern uint8 UEGO_numPacBlcknS1B1;
#endif /* __UEGO_NUMPACBLCKNS1B1_EXT__ */

#ifndef __UEGO_NUMPACBLCKNS1B2_EXT__
#define __UEGO_NUMPACBLCKNS1B2_EXT__
extern uint8 UEGO_numPacBlcknS1B2;
#endif /* __UEGO_NUMPACBLCKNS1B2_EXT__ */

#ifndef __UEGO_NUMREGSETCNTRS1B1_EXT__
#define __UEGO_NUMREGSETCNTRS1B1_EXT__
extern uint8 UEGO_numRegSetCntrS1B1;
#endif /* __UEGO_NUMREGSETCNTRS1B1_EXT__ */

#ifndef __UEGO_NUMREGSETCNTRS1B2_EXT__
#define __UEGO_NUMREGSETCNTRS1B2_EXT__
extern uint8 UEGO_numRegSetCntrS1B2;
#endif /* __UEGO_NUMREGSETCNTRS1B2_EXT__ */

#ifndef __UEGO_STDSQIPMPS1B1_EXT__
#define __UEGO_STDSQIPMPS1B1_EXT__
extern uint8 UEGO_stDSQIPmpS1B1;
#endif /* __UEGO_STDSQIPMPS1B1_EXT__ */

#ifndef __UEGO_STDSQIPMPS1B2_EXT__
#define __UEGO_STDSQIPMPS1B2_EXT__
extern uint8 UEGO_stDSQIPmpS1B2;
#endif /* __UEGO_STDSQIPMPS1B2_EXT__ */

#ifndef __UEGO_FLGALLVLVACTV_EXT__
#define __UEGO_FLGALLVLVACTV_EXT__
extern _bit                     UEGO_flgAllVlvActv;
#endif /* __UEGO_FLGALLVLVACTV_EXT__ */

#ifndef __UEGO_FLGCJ135RSTCLBS1B1_EXT__
#define __UEGO_FLGCJ135RSTCLBS1B1_EXT__
extern _bit                     UEGO_flgCJ135RstClbS1B1;
#endif /* __UEGO_FLGCJ135RSTCLBS1B1_EXT__ */

#ifndef __UEGO_FLGCJ135RSTCLBS1B2_EXT__
#define __UEGO_FLGCJ135RSTCLBS1B2_EXT__
extern _bit                     UEGO_flgCJ135RstClbS1B2;
#endif /* __UEGO_FLGCJ135RSTCLBS1B2_EXT__ */

#ifndef __UEGO_FLGCJ135RSTMEASS1B1_EXT__
#define __UEGO_FLGCJ135RSTMEASS1B1_EXT__
extern _bit                     UEGO_flgCJ135RstMeasS1B1;
#endif /* __UEGO_FLGCJ135RSTMEASS1B1_EXT__ */

#ifndef __UEGO_FLGCJ135RSTMEASS1B2_EXT__
#define __UEGO_FLGCJ135RSTMEASS1B2_EXT__
extern _bit                     UEGO_flgCJ135RstMeasS1B2;
#endif /* __UEGO_FLGCJ135RSTMEASS1B2_EXT__ */

#ifndef __UEGO_FLGCMEASS1B1_EXT__
#define __UEGO_FLGCMEASS1B1_EXT__
extern _bit                     UEGO_flgCMeasS1B1;
#endif /* __UEGO_FLGCMEASS1B1_EXT__ */

#ifndef __UEGO_FLGCMEASS1B2_EXT__
#define __UEGO_FLGCMEASS1B2_EXT__
extern _bit                     UEGO_flgCMeasS1B2;
#endif /* __UEGO_FLGCMEASS1B2_EXT__ */

#ifndef __UEGO_FLGCIPESNSRADPNRELSS1B1_EXT__
#define __UEGO_FLGCIPESNSRADPNRELSS1B1_EXT__
extern _bit                     UEGO_flgCipeSnsrAdpnRelsS1B1;
#endif /* __UEGO_FLGCIPESNSRADPNRELSS1B1_EXT__ */

#ifndef __UEGO_FLGCIPESNSRADPNRELSS1B2_EXT__
#define __UEGO_FLGCIPESNSRADPNRELSS1B2_EXT__
extern _bit                     UEGO_flgCipeSnsrAdpnRelsS1B2;
#endif /* __UEGO_FLGCIPESNSRADPNRELSS1B2_EXT__ */

#ifndef __UEGO_FLGCMBENGTMPSTOP_EXT__
#define __UEGO_FLGCMBENGTMPSTOP_EXT__
extern _bit                     UEGO_flgCmbEngTmpStop;
#endif /* __UEGO_FLGCMBENGTMPSTOP_EXT__ */

#ifndef __UEGO_FLGDEWPNTRELSS1B1_EXT__
#define __UEGO_FLGDEWPNTRELSS1B1_EXT__
extern _bit                     UEGO_flgDewPntRelsS1B1;
#endif /* __UEGO_FLGDEWPNTRELSS1B1_EXT__ */

#ifndef __UEGO_FLGDEWPNTRELSS1B2_EXT__
#define __UEGO_FLGDEWPNTRELSS1B2_EXT__
extern _bit                     UEGO_flgDewPntRelsS1B2;
#endif /* __UEGO_FLGDEWPNTRELSS1B2_EXT__ */

#ifndef __UEGO_FLGENGRUNNG_EXT__
#define __UEGO_FLGENGRUNNG_EXT__
extern _bit                     UEGO_flgEngRunng;
#endif /* __UEGO_FLGENGRUNNG_EXT__ */

#ifndef __UEGO_FLGENGSPDLO_EXT__
#define __UEGO_FLGENGSPDLO_EXT__
extern _bit                     UEGO_flgEngSpdLo;
#endif /* __UEGO_FLGENGSPDLO_EXT__ */

#ifndef __UEGO_FLGENGSTOPPHA_EXT__
#define __UEGO_FLGENGSTOPPHA_EXT__
extern _bit                     UEGO_flgEngStopPha;
#endif /* __UEGO_FLGENGSTOPPHA_EXT__ */

#ifndef __UEGO_FLGFACRIERIACALCDS1B1_EXT__
#define __UEGO_FLGFACRIERIACALCDS1B1_EXT__
extern _bit                     UEGO_flgFacRieRiaCalcdS1B1;
#endif /* __UEGO_FLGFACRIERIACALCDS1B1_EXT__ */

#ifndef __UEGO_FLGFACRIERIACALCDS1B2_EXT__
#define __UEGO_FLGFACRIERIACALCDS1B2_EXT__
extern _bit                     UEGO_flgFacRieRiaCalcdS1B2;
#endif /* __UEGO_FLGFACRIERIACALCDS1B2_EXT__ */

#ifndef __UEGO_FLGFACRIERIPCALCDS1B1_EXT__
#define __UEGO_FLGFACRIERIPCALCDS1B1_EXT__
extern _bit                     UEGO_flgFacRieRipCalcdS1B1;
#endif /* __UEGO_FLGFACRIERIPCALCDS1B1_EXT__ */

#ifndef __UEGO_FLGFACRIERIPCALCDS1B2_EXT__
#define __UEGO_FLGFACRIERIPCALCDS1B2_EXT__
extern _bit                     UEGO_flgFacRieRipCalcdS1B2;
#endif /* __UEGO_FLGFACRIERIPCALCDS1B2_EXT__ */

#ifndef __UEGO_FLGIPMPACTVDS1B1_EXT__
#define __UEGO_FLGIPMPACTVDS1B1_EXT__
extern _bit                     UEGO_flgIPmpActvdS1B1;
#endif /* __UEGO_FLGIPMPACTVDS1B1_EXT__ */

#ifndef __UEGO_FLGIPMPACTVDS1B2_EXT__
#define __UEGO_FLGIPMPACTVDS1B2_EXT__
extern _bit                     UEGO_flgIPmpActvdS1B2;
#endif /* __UEGO_FLGIPMPACTVDS1B2_EXT__ */

#ifndef __UEGO_FLGIPMPCTRLDSBCS1B1_EXT__
#define __UEGO_FLGIPMPCTRLDSBCS1B1_EXT__
extern _bit                     UEGO_flgIPmpCtrlDsbcS1B1;
#endif /* __UEGO_FLGIPMPCTRLDSBCS1B1_EXT__ */

#ifndef __UEGO_FLGIPMPCTRLDSBCS1B2_EXT__
#define __UEGO_FLGIPMPCTRLDSBCS1B2_EXT__
extern _bit                     UEGO_flgIPmpCtrlDsbcS1B2;
#endif /* __UEGO_FLGIPMPCTRLDSBCS1B2_EXT__ */

#ifndef __UEGO_FLGIPMPDICOND_EXT__
#define __UEGO_FLGIPMPDICOND_EXT__
extern _bit                     UEGO_flgIPmpDiCond;
#endif /* __UEGO_FLGIPMPDICOND_EXT__ */

#ifndef __UEGO_FLGIPMPDIS1B1_EXT__
#define __UEGO_FLGIPMPDIS1B1_EXT__
extern _bit                     UEGO_flgIPmpDiS1B1;
#endif /* __UEGO_FLGIPMPDIS1B1_EXT__ */

#ifndef __UEGO_FLGIPMPDIS1B2_EXT__
#define __UEGO_FLGIPMPDIS1B2_EXT__
extern _bit                     UEGO_flgIPmpDiS1B2;
#endif /* __UEGO_FLGIPMPDIS1B2_EXT__ */

#ifndef __UEGO_FLGIPMPEVLNVLDS1B1_EXT__
#define __UEGO_FLGIPMPEVLNVLDS1B1_EXT__
extern _bit                     UEGO_flgIPmpEvlnVldS1B1;
#endif /* __UEGO_FLGIPMPEVLNVLDS1B1_EXT__ */

#ifndef __UEGO_FLGIPMPEVLNVLDS1B2_EXT__
#define __UEGO_FLGIPMPEVLNVLDS1B2_EXT__
extern _bit                     UEGO_flgIPmpEvlnVldS1B2;
#endif /* __UEGO_FLGIPMPEVLNVLDS1B2_EXT__ */

#ifndef __UEGO_FLGIPMPRVSCHRGVLDS1B1_EXT__
#define __UEGO_FLGIPMPRVSCHRGVLDS1B1_EXT__
extern _bit                     UEGO_flgIPmpRvsChrgVldS1B1;
#endif /* __UEGO_FLGIPMPRVSCHRGVLDS1B1_EXT__ */

#ifndef __UEGO_FLGIPMPRVSCHRGVLDS1B2_EXT__
#define __UEGO_FLGIPMPRVSCHRGVLDS1B2_EXT__
extern _bit                     UEGO_flgIPmpRvsChrgVldS1B2;
#endif /* __UEGO_FLGIPMPRVSCHRGVLDS1B2_EXT__ */

#ifndef __UEGO_FLGISQSTRTDS1B1_EXT__
#define __UEGO_FLGISQSTRTDS1B1_EXT__
extern _bit                     UEGO_flgIsqStrtdS1B1;
#endif /* __UEGO_FLGISQSTRTDS1B1_EXT__ */

#ifndef __UEGO_FLGISQSTRTDS1B2_EXT__
#define __UEGO_FLGISQSTRTDS1B2_EXT__
extern _bit                     UEGO_flgIsqStrtdS1B2;
#endif /* __UEGO_FLGISQSTRTDS1B2_EXT__ */

#ifndef __UEGO_FLGISQRSTRTDS1B1_EXT__
#define __UEGO_FLGISQRSTRTDS1B1_EXT__
extern _bit                     UEGO_flgIsqrStrtdS1B1;
#endif /* __UEGO_FLGISQRSTRTDS1B1_EXT__ */

#ifndef __UEGO_FLGISQRSTRTDS1B2_EXT__
#define __UEGO_FLGISQRSTRTDS1B2_EXT__
extern _bit                     UEGO_flgIsqrStrtdS1B2;
#endif /* __UEGO_FLGISQRSTRTDS1B2_EXT__ */

#ifndef __UEGO_FLGLAMRECPRMDLVLD_EXT__
#define __UEGO_FLGLAMRECPRMDLVLD_EXT__
extern _bit                     UEGO_flgLamRecprMdlVld;
#endif /* __UEGO_FLGLAMRECPRMDLVLD_EXT__ */

#ifndef __UEGO_FLGLOUPENS1B1_EXT__
#define __UEGO_FLGLOUPENS1B1_EXT__
extern _bit                     UEGO_flgLoupeNS1B1;
#endif /* __UEGO_FLGLOUPENS1B1_EXT__ */

#ifndef __UEGO_FLGLOUPENS1B2_EXT__
#define __UEGO_FLGLOUPENS1B2_EXT__
extern _bit                     UEGO_flgLoupeNS1B2;
#endif /* __UEGO_FLGLOUPENS1B2_EXT__ */

#ifndef __UEGO_FLGLOUPEPS1B1_EXT__
#define __UEGO_FLGLOUPEPS1B1_EXT__
extern _bit                     UEGO_flgLoupePS1B1;
#endif /* __UEGO_FLGLOUPEPS1B1_EXT__ */

#ifndef __UEGO_FLGLOUPEPS1B2_EXT__
#define __UEGO_FLGLOUPEPS1B2_EXT__
extern _bit                     UEGO_flgLoupePS1B2;
#endif /* __UEGO_FLGLOUPEPS1B2_EXT__ */

#ifndef __UEGO_FLGNEWIPMPRVSCHRGS1B1_EXT__
#define __UEGO_FLGNEWIPMPRVSCHRGS1B1_EXT__
extern _bit                     UEGO_flgNewIPmpRvsChrgS1B1;
#endif /* __UEGO_FLGNEWIPMPRVSCHRGS1B1_EXT__ */

#ifndef __UEGO_FLGNEWIPMPRVSCHRGS1B2_EXT__
#define __UEGO_FLGNEWIPMPRVSCHRGS1B2_EXT__
extern _bit                     UEGO_flgNewIPmpRvsChrgS1B2;
#endif /* __UEGO_FLGNEWIPMPRVSCHRGS1B2_EXT__ */

#ifndef __UEGO_FLGNEWPACS1B1_EXT__
#define __UEGO_FLGNEWPACS1B1_EXT__
extern _bit                     UEGO_flgNewPacS1B1;
#endif /* __UEGO_FLGNEWPACS1B1_EXT__ */

#ifndef __UEGO_FLGNEWPACS1B2_EXT__
#define __UEGO_FLGNEWPACS1B2_EXT__
extern _bit                     UEGO_flgNewPacS1B2;
#endif /* __UEGO_FLGNEWPACS1B2_EXT__ */

#ifndef __UEGO_FLGPOSTDRVEXTN_EXT__
#define __UEGO_FLGPOSTDRVEXTN_EXT__
extern _bit                     UEGO_flgPostDrvExtn;
#endif /* __UEGO_FLGPOSTDRVEXTN_EXT__ */

#ifndef __UEGO_FLGRTEVLNVLDS1B1_EXT__
#define __UEGO_FLGRTEVLNVLDS1B1_EXT__
extern _bit                     UEGO_flgRTEvlnVldS1B1;
#endif /* __UEGO_FLGRTEVLNVLDS1B1_EXT__ */

#ifndef __UEGO_FLGRTEVLNVLDS1B2_EXT__
#define __UEGO_FLGRTEVLNVLDS1B2_EXT__
extern _bit                     UEGO_flgRTEvlnVldS1B2;
#endif /* __UEGO_FLGRTEVLNVLDS1B2_EXT__ */

#ifndef __UEGO_FLGRPCRELSS1B1_EXT__
#define __UEGO_FLGRPCRELSS1B1_EXT__
extern _bit                     UEGO_flgRpcRelsS1B1;
#endif /* __UEGO_FLGRPCRELSS1B1_EXT__ */

#ifndef __UEGO_FLGRPCRELSS1B2_EXT__
#define __UEGO_FLGRPCRELSS1B2_EXT__
extern _bit                     UEGO_flgRpcRelsS1B2;
#endif /* __UEGO_FLGRPCRELSS1B2_EXT__ */

#ifndef __UEGO_FLGRPCREQDS1B1_EXT__
#define __UEGO_FLGRPCREQDS1B1_EXT__
extern _bit                     UEGO_flgRpcReqdS1B1;
#endif /* __UEGO_FLGRPCREQDS1B1_EXT__ */

#ifndef __UEGO_FLGRPCREQDS1B2_EXT__
#define __UEGO_FLGRPCREQDS1B2_EXT__
extern _bit                     UEGO_flgRpcReqdS1B2;
#endif /* __UEGO_FLGRPCREQDS1B2_EXT__ */

#ifndef __UEGO_FLGTESTGETREVC1_EXT__
#define __UEGO_FLGTESTGETREVC1_EXT__
extern _bit                     UEGO_flgTestGetRevC1;
#endif /* __UEGO_FLGTESTGETREVC1_EXT__ */

#ifndef __UEGO_FLGUBATTMAX_EXT__
#define __UEGO_FLGUBATTMAX_EXT__
extern _bit                     UEGO_flgUBattMax;
#endif /* __UEGO_FLGUBATTMAX_EXT__ */

#ifndef __UEGO_FLGUBATTMIN_EXT__
#define __UEGO_FLGUBATTMIN_EXT__
extern _bit                     UEGO_flgUBattMin;
#endif /* __UEGO_FLGUBATTMIN_EXT__ */

#ifndef __UEGO_FLGURIAS1B1_EXT__
#define __UEGO_FLGURIAS1B1_EXT__
extern _bit                     UEGO_flgURIAS1B1;
#endif /* __UEGO_FLGURIAS1B1_EXT__ */

#ifndef __UEGO_FLGURIAS1B2_EXT__
#define __UEGO_FLGURIAS1B2_EXT__
extern _bit                     UEGO_flgURIAS1B2;
#endif /* __UEGO_FLGURIAS1B2_EXT__ */

#ifndef __UEGO_FLGUIALLMEASS1B1_EXT__
#define __UEGO_FLGUIALLMEASS1B1_EXT__
extern _bit                     UEGO_flgUiAllMeasS1B1;
#endif /* __UEGO_FLGUIALLMEASS1B1_EXT__ */

#ifndef __UEGO_FLGUIALLMEASS1B2_EXT__
#define __UEGO_FLGUIALLMEASS1B2_EXT__
extern _bit                     UEGO_flgUiAllMeasS1B2;
#endif /* __UEGO_FLGUIALLMEASS1B2_EXT__ */

#ifndef __UEGO_FLGUOFFIPE1Z1STRTDS1B1_EXT__
#define __UEGO_FLGUOFFIPE1Z1STRTDS1B1_EXT__
extern _bit                     UEGO_flgUoffipe1Z1StrtdS1B1;
#endif /* __UEGO_FLGUOFFIPE1Z1STRTDS1B1_EXT__ */

#ifndef __UEGO_FLGUOFFIPE1Z1STRTDS1B2_EXT__
#define __UEGO_FLGUOFFIPE1Z1STRTDS1B2_EXT__
extern _bit                     UEGO_flgUoffipe1Z1StrtdS1B2;
#endif /* __UEGO_FLGUOFFIPE1Z1STRTDS1B2_EXT__ */

#ifndef __UEGO_FLGUOFFIPE1Z2STRTDS1B1_EXT__
#define __UEGO_FLGUOFFIPE1Z2STRTDS1B1_EXT__
extern _bit                     UEGO_flgUoffipe1Z2StrtdS1B1;
#endif /* __UEGO_FLGUOFFIPE1Z2STRTDS1B1_EXT__ */

#ifndef __UEGO_FLGUOFFIPE1Z2STRTDS1B2_EXT__
#define __UEGO_FLGUOFFIPE1Z2STRTDS1B2_EXT__
extern _bit                     UEGO_flgUoffipe1Z2StrtdS1B2;
#endif /* __UEGO_FLGUOFFIPE1Z2STRTDS1B2_EXT__ */

#ifndef __UEGO_FLGUOFFIPE2Z1STRTDS1B1_EXT__
#define __UEGO_FLGUOFFIPE2Z1STRTDS1B1_EXT__
extern _bit                     UEGO_flgUoffipe2Z1StrtdS1B1;
#endif /* __UEGO_FLGUOFFIPE2Z1STRTDS1B1_EXT__ */

#ifndef __UEGO_FLGUOFFIPE2Z1STRTDS1B2_EXT__
#define __UEGO_FLGUOFFIPE2Z1STRTDS1B2_EXT__
extern _bit                     UEGO_flgUoffipe2Z1StrtdS1B2;
#endif /* __UEGO_FLGUOFFIPE2Z1STRTDS1B2_EXT__ */

#ifndef __UEGO_FLGUOFFIPE2Z2STRTDS1B1_EXT__
#define __UEGO_FLGUOFFIPE2Z2STRTDS1B1_EXT__
extern _bit                     UEGO_flgUoffipe2Z2StrtdS1B1;
#endif /* __UEGO_FLGUOFFIPE2Z2STRTDS1B1_EXT__ */

#ifndef __UEGO_FLGUOFFIPE2Z2STRTDS1B2_EXT__
#define __UEGO_FLGUOFFIPE2Z2STRTDS1B2_EXT__
extern _bit                     UEGO_flgUoffipe2Z2StrtdS1B2;
#endif /* __UEGO_FLGUOFFIPE2Z2STRTDS1B2_EXT__ */

#ifndef __UEGO_FLGUOFFVCC1STRTDS1B1_EXT__
#define __UEGO_FLGUOFFVCC1STRTDS1B1_EXT__
extern _bit                     UEGO_flgUoffvcc1StrtdS1B1;
#endif /* __UEGO_FLGUOFFVCC1STRTDS1B1_EXT__ */

#ifndef __UEGO_FLGUOFFVCC1STRTDS1B2_EXT__
#define __UEGO_FLGUOFFVCC1STRTDS1B2_EXT__
extern _bit                     UEGO_flgUoffvcc1StrtdS1B2;
#endif /* __UEGO_FLGUOFFVCC1STRTDS1B2_EXT__ */

#ifndef __UEGO_FLGUOFFVCC2STRTDS1B1_EXT__
#define __UEGO_FLGUOFFVCC2STRTDS1B1_EXT__
extern _bit                     UEGO_flgUoffvcc2StrtdS1B1;
#endif /* __UEGO_FLGUOFFVCC2STRTDS1B1_EXT__ */

#ifndef __UEGO_FLGUOFFVCC2STRTDS1B2_EXT__
#define __UEGO_FLGUOFFVCC2STRTDS1B2_EXT__
extern _bit                     UEGO_flgUoffvcc2StrtdS1B2;
#endif /* __UEGO_FLGUOFFVCC2STRTDS1B2_EXT__ */

#ifndef __UEGO_FLGUOFFVCC3STRTDS1B1_EXT__
#define __UEGO_FLGUOFFVCC3STRTDS1B1_EXT__
extern _bit                     UEGO_flgUoffvcc3StrtdS1B1;
#endif /* __UEGO_FLGUOFFVCC3STRTDS1B1_EXT__ */

#ifndef __UEGO_FLGUOFFVCC3STRTDS1B2_EXT__
#define __UEGO_FLGUOFFVCC3STRTDS1B2_EXT__
extern _bit                     UEGO_flgUoffvcc3StrtdS1B2;
#endif /* __UEGO_FLGUOFFVCC3STRTDS1B2_EXT__ */

#ifndef __UEGO_FLGUOFFVCCI2STRTDS1B1_EXT__
#define __UEGO_FLGUOFFVCCI2STRTDS1B1_EXT__
extern _bit                     UEGO_flgUoffvcci2StrtdS1B1;
#endif /* __UEGO_FLGUOFFVCCI2STRTDS1B1_EXT__ */

#ifndef __UEGO_FLGUOFFVCCI2STRTDS1B2_EXT__
#define __UEGO_FLGUOFFVCCI2STRTDS1B2_EXT__
extern _bit                     UEGO_flgUoffvcci2StrtdS1B2;
#endif /* __UEGO_FLGUOFFVCCI2STRTDS1B2_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_CoEng_st 
#define SET_CoEng_st (CoEng_st=TRUE)
#endif
#ifndef CLR_CoEng_st 
#define CLR_CoEng_st (CoEng_st=FALSE)
#endif
#ifndef GET_CoEng_st 
#define GET_CoEng_st (CoEng_st)
#endif
#ifndef PUT_CoEng_st 
#define PUT_CoEng_st(val) ((val) ? SET_CoEng_st : CLR_CoEng_st)
#endif


#ifndef SET_UEGO_flgAllVlvActv 
#define SET_UEGO_flgAllVlvActv (UEGO_flgAllVlvActv=TRUE)
#endif
#ifndef CLR_UEGO_flgAllVlvActv 
#define CLR_UEGO_flgAllVlvActv (UEGO_flgAllVlvActv=FALSE)
#endif
#ifndef GET_UEGO_flgAllVlvActv 
#define GET_UEGO_flgAllVlvActv (UEGO_flgAllVlvActv)
#endif
#ifndef PUT_UEGO_flgAllVlvActv 
#define PUT_UEGO_flgAllVlvActv(val) ((val) ? SET_UEGO_flgAllVlvActv : CLR_UEGO_flgAllVlvActv)
#endif


#ifndef SET_UEGO_flgCJ135RstClbS1B1 
#define SET_UEGO_flgCJ135RstClbS1B1 (UEGO_flgCJ135RstClbS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgCJ135RstClbS1B1 
#define CLR_UEGO_flgCJ135RstClbS1B1 (UEGO_flgCJ135RstClbS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgCJ135RstClbS1B1 
#define GET_UEGO_flgCJ135RstClbS1B1 (UEGO_flgCJ135RstClbS1B1)
#endif
#ifndef PUT_UEGO_flgCJ135RstClbS1B1 
#define PUT_UEGO_flgCJ135RstClbS1B1(val) ((val) ? SET_UEGO_flgCJ135RstClbS1B1 : CLR_UEGO_flgCJ135RstClbS1B1)
#endif


#ifndef SET_UEGO_flgCJ135RstClbS1B2 
#define SET_UEGO_flgCJ135RstClbS1B2 (UEGO_flgCJ135RstClbS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgCJ135RstClbS1B2 
#define CLR_UEGO_flgCJ135RstClbS1B2 (UEGO_flgCJ135RstClbS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgCJ135RstClbS1B2 
#define GET_UEGO_flgCJ135RstClbS1B2 (UEGO_flgCJ135RstClbS1B2)
#endif
#ifndef PUT_UEGO_flgCJ135RstClbS1B2 
#define PUT_UEGO_flgCJ135RstClbS1B2(val) ((val) ? SET_UEGO_flgCJ135RstClbS1B2 : CLR_UEGO_flgCJ135RstClbS1B2)
#endif


#ifndef SET_UEGO_flgCJ135RstMeasS1B1 
#define SET_UEGO_flgCJ135RstMeasS1B1 (UEGO_flgCJ135RstMeasS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgCJ135RstMeasS1B1 
#define CLR_UEGO_flgCJ135RstMeasS1B1 (UEGO_flgCJ135RstMeasS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgCJ135RstMeasS1B1 
#define GET_UEGO_flgCJ135RstMeasS1B1 (UEGO_flgCJ135RstMeasS1B1)
#endif
#ifndef PUT_UEGO_flgCJ135RstMeasS1B1 
#define PUT_UEGO_flgCJ135RstMeasS1B1(val) ((val) ? SET_UEGO_flgCJ135RstMeasS1B1 : CLR_UEGO_flgCJ135RstMeasS1B1)
#endif


#ifndef SET_UEGO_flgCJ135RstMeasS1B2 
#define SET_UEGO_flgCJ135RstMeasS1B2 (UEGO_flgCJ135RstMeasS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgCJ135RstMeasS1B2 
#define CLR_UEGO_flgCJ135RstMeasS1B2 (UEGO_flgCJ135RstMeasS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgCJ135RstMeasS1B2 
#define GET_UEGO_flgCJ135RstMeasS1B2 (UEGO_flgCJ135RstMeasS1B2)
#endif
#ifndef PUT_UEGO_flgCJ135RstMeasS1B2 
#define PUT_UEGO_flgCJ135RstMeasS1B2(val) ((val) ? SET_UEGO_flgCJ135RstMeasS1B2 : CLR_UEGO_flgCJ135RstMeasS1B2)
#endif


#ifndef SET_UEGO_flgCMeasS1B1 
#define SET_UEGO_flgCMeasS1B1 (UEGO_flgCMeasS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgCMeasS1B1 
#define CLR_UEGO_flgCMeasS1B1 (UEGO_flgCMeasS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgCMeasS1B1 
#define GET_UEGO_flgCMeasS1B1 (UEGO_flgCMeasS1B1)
#endif
#ifndef PUT_UEGO_flgCMeasS1B1 
#define PUT_UEGO_flgCMeasS1B1(val) ((val) ? SET_UEGO_flgCMeasS1B1 : CLR_UEGO_flgCMeasS1B1)
#endif


#ifndef SET_UEGO_flgCMeasS1B2 
#define SET_UEGO_flgCMeasS1B2 (UEGO_flgCMeasS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgCMeasS1B2 
#define CLR_UEGO_flgCMeasS1B2 (UEGO_flgCMeasS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgCMeasS1B2 
#define GET_UEGO_flgCMeasS1B2 (UEGO_flgCMeasS1B2)
#endif
#ifndef PUT_UEGO_flgCMeasS1B2 
#define PUT_UEGO_flgCMeasS1B2(val) ((val) ? SET_UEGO_flgCMeasS1B2 : CLR_UEGO_flgCMeasS1B2)
#endif


#ifndef SET_UEGO_flgCipeSnsrAdpnRelsS1B1 
#define SET_UEGO_flgCipeSnsrAdpnRelsS1B1 (UEGO_flgCipeSnsrAdpnRelsS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgCipeSnsrAdpnRelsS1B1 
#define CLR_UEGO_flgCipeSnsrAdpnRelsS1B1 (UEGO_flgCipeSnsrAdpnRelsS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgCipeSnsrAdpnRelsS1B1 
#define GET_UEGO_flgCipeSnsrAdpnRelsS1B1 (UEGO_flgCipeSnsrAdpnRelsS1B1)
#endif
#ifndef PUT_UEGO_flgCipeSnsrAdpnRelsS1B1 
#define PUT_UEGO_flgCipeSnsrAdpnRelsS1B1(val) ((val) ? SET_UEGO_flgCipeSnsrAdpnRelsS1B1 : CLR_UEGO_flgCipeSnsrAdpnRelsS1B1)
#endif


#ifndef SET_UEGO_flgCipeSnsrAdpnRelsS1B2 
#define SET_UEGO_flgCipeSnsrAdpnRelsS1B2 (UEGO_flgCipeSnsrAdpnRelsS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgCipeSnsrAdpnRelsS1B2 
#define CLR_UEGO_flgCipeSnsrAdpnRelsS1B2 (UEGO_flgCipeSnsrAdpnRelsS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgCipeSnsrAdpnRelsS1B2 
#define GET_UEGO_flgCipeSnsrAdpnRelsS1B2 (UEGO_flgCipeSnsrAdpnRelsS1B2)
#endif
#ifndef PUT_UEGO_flgCipeSnsrAdpnRelsS1B2 
#define PUT_UEGO_flgCipeSnsrAdpnRelsS1B2(val) ((val) ? SET_UEGO_flgCipeSnsrAdpnRelsS1B2 : CLR_UEGO_flgCipeSnsrAdpnRelsS1B2)
#endif


#ifndef SET_UEGO_flgCmbEngTmpStop 
#define SET_UEGO_flgCmbEngTmpStop (UEGO_flgCmbEngTmpStop=TRUE)
#endif
#ifndef CLR_UEGO_flgCmbEngTmpStop 
#define CLR_UEGO_flgCmbEngTmpStop (UEGO_flgCmbEngTmpStop=FALSE)
#endif
#ifndef GET_UEGO_flgCmbEngTmpStop 
#define GET_UEGO_flgCmbEngTmpStop (UEGO_flgCmbEngTmpStop)
#endif
#ifndef PUT_UEGO_flgCmbEngTmpStop 
#define PUT_UEGO_flgCmbEngTmpStop(val) ((val) ? SET_UEGO_flgCmbEngTmpStop : CLR_UEGO_flgCmbEngTmpStop)
#endif


#ifndef SET_UEGO_flgDewPntRelsS1B1 
#define SET_UEGO_flgDewPntRelsS1B1 (UEGO_flgDewPntRelsS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgDewPntRelsS1B1 
#define CLR_UEGO_flgDewPntRelsS1B1 (UEGO_flgDewPntRelsS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgDewPntRelsS1B1 
#define GET_UEGO_flgDewPntRelsS1B1 (UEGO_flgDewPntRelsS1B1)
#endif
#ifndef PUT_UEGO_flgDewPntRelsS1B1 
#define PUT_UEGO_flgDewPntRelsS1B1(val) ((val) ? SET_UEGO_flgDewPntRelsS1B1 : CLR_UEGO_flgDewPntRelsS1B1)
#endif


#ifndef SET_UEGO_flgDewPntRelsS1B2 
#define SET_UEGO_flgDewPntRelsS1B2 (UEGO_flgDewPntRelsS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgDewPntRelsS1B2 
#define CLR_UEGO_flgDewPntRelsS1B2 (UEGO_flgDewPntRelsS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgDewPntRelsS1B2 
#define GET_UEGO_flgDewPntRelsS1B2 (UEGO_flgDewPntRelsS1B2)
#endif
#ifndef PUT_UEGO_flgDewPntRelsS1B2 
#define PUT_UEGO_flgDewPntRelsS1B2(val) ((val) ? SET_UEGO_flgDewPntRelsS1B2 : CLR_UEGO_flgDewPntRelsS1B2)
#endif


#ifndef SET_UEGO_flgEngRunng 
#define SET_UEGO_flgEngRunng (UEGO_flgEngRunng=TRUE)
#endif
#ifndef CLR_UEGO_flgEngRunng 
#define CLR_UEGO_flgEngRunng (UEGO_flgEngRunng=FALSE)
#endif
#ifndef GET_UEGO_flgEngRunng 
#define GET_UEGO_flgEngRunng (UEGO_flgEngRunng)
#endif
#ifndef PUT_UEGO_flgEngRunng 
#define PUT_UEGO_flgEngRunng(val) ((val) ? SET_UEGO_flgEngRunng : CLR_UEGO_flgEngRunng)
#endif


#ifndef SET_UEGO_flgEngSpdLo 
#define SET_UEGO_flgEngSpdLo (UEGO_flgEngSpdLo=TRUE)
#endif
#ifndef CLR_UEGO_flgEngSpdLo 
#define CLR_UEGO_flgEngSpdLo (UEGO_flgEngSpdLo=FALSE)
#endif
#ifndef GET_UEGO_flgEngSpdLo 
#define GET_UEGO_flgEngSpdLo (UEGO_flgEngSpdLo)
#endif
#ifndef PUT_UEGO_flgEngSpdLo 
#define PUT_UEGO_flgEngSpdLo(val) ((val) ? SET_UEGO_flgEngSpdLo : CLR_UEGO_flgEngSpdLo)
#endif


#ifndef SET_UEGO_flgEngStopPha 
#define SET_UEGO_flgEngStopPha (UEGO_flgEngStopPha=TRUE)
#endif
#ifndef CLR_UEGO_flgEngStopPha 
#define CLR_UEGO_flgEngStopPha (UEGO_flgEngStopPha=FALSE)
#endif
#ifndef GET_UEGO_flgEngStopPha 
#define GET_UEGO_flgEngStopPha (UEGO_flgEngStopPha)
#endif
#ifndef PUT_UEGO_flgEngStopPha 
#define PUT_UEGO_flgEngStopPha(val) ((val) ? SET_UEGO_flgEngStopPha : CLR_UEGO_flgEngStopPha)
#endif


#ifndef SET_UEGO_flgFacRieRiaCalcdS1B1 
#define SET_UEGO_flgFacRieRiaCalcdS1B1 (UEGO_flgFacRieRiaCalcdS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgFacRieRiaCalcdS1B1 
#define CLR_UEGO_flgFacRieRiaCalcdS1B1 (UEGO_flgFacRieRiaCalcdS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgFacRieRiaCalcdS1B1 
#define GET_UEGO_flgFacRieRiaCalcdS1B1 (UEGO_flgFacRieRiaCalcdS1B1)
#endif
#ifndef PUT_UEGO_flgFacRieRiaCalcdS1B1 
#define PUT_UEGO_flgFacRieRiaCalcdS1B1(val) ((val) ? SET_UEGO_flgFacRieRiaCalcdS1B1 : CLR_UEGO_flgFacRieRiaCalcdS1B1)
#endif


#ifndef SET_UEGO_flgFacRieRiaCalcdS1B2 
#define SET_UEGO_flgFacRieRiaCalcdS1B2 (UEGO_flgFacRieRiaCalcdS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgFacRieRiaCalcdS1B2 
#define CLR_UEGO_flgFacRieRiaCalcdS1B2 (UEGO_flgFacRieRiaCalcdS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgFacRieRiaCalcdS1B2 
#define GET_UEGO_flgFacRieRiaCalcdS1B2 (UEGO_flgFacRieRiaCalcdS1B2)
#endif
#ifndef PUT_UEGO_flgFacRieRiaCalcdS1B2 
#define PUT_UEGO_flgFacRieRiaCalcdS1B2(val) ((val) ? SET_UEGO_flgFacRieRiaCalcdS1B2 : CLR_UEGO_flgFacRieRiaCalcdS1B2)
#endif


#ifndef SET_UEGO_flgFacRieRipCalcdS1B1 
#define SET_UEGO_flgFacRieRipCalcdS1B1 (UEGO_flgFacRieRipCalcdS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgFacRieRipCalcdS1B1 
#define CLR_UEGO_flgFacRieRipCalcdS1B1 (UEGO_flgFacRieRipCalcdS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgFacRieRipCalcdS1B1 
#define GET_UEGO_flgFacRieRipCalcdS1B1 (UEGO_flgFacRieRipCalcdS1B1)
#endif
#ifndef PUT_UEGO_flgFacRieRipCalcdS1B1 
#define PUT_UEGO_flgFacRieRipCalcdS1B1(val) ((val) ? SET_UEGO_flgFacRieRipCalcdS1B1 : CLR_UEGO_flgFacRieRipCalcdS1B1)
#endif


#ifndef SET_UEGO_flgFacRieRipCalcdS1B2 
#define SET_UEGO_flgFacRieRipCalcdS1B2 (UEGO_flgFacRieRipCalcdS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgFacRieRipCalcdS1B2 
#define CLR_UEGO_flgFacRieRipCalcdS1B2 (UEGO_flgFacRieRipCalcdS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgFacRieRipCalcdS1B2 
#define GET_UEGO_flgFacRieRipCalcdS1B2 (UEGO_flgFacRieRipCalcdS1B2)
#endif
#ifndef PUT_UEGO_flgFacRieRipCalcdS1B2 
#define PUT_UEGO_flgFacRieRipCalcdS1B2(val) ((val) ? SET_UEGO_flgFacRieRipCalcdS1B2 : CLR_UEGO_flgFacRieRipCalcdS1B2)
#endif


#ifndef SET_UEGO_flgIPmpActvdS1B1 
#define SET_UEGO_flgIPmpActvdS1B1 (UEGO_flgIPmpActvdS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgIPmpActvdS1B1 
#define CLR_UEGO_flgIPmpActvdS1B1 (UEGO_flgIPmpActvdS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgIPmpActvdS1B1 
#define GET_UEGO_flgIPmpActvdS1B1 (UEGO_flgIPmpActvdS1B1)
#endif
#ifndef PUT_UEGO_flgIPmpActvdS1B1 
#define PUT_UEGO_flgIPmpActvdS1B1(val) ((val) ? SET_UEGO_flgIPmpActvdS1B1 : CLR_UEGO_flgIPmpActvdS1B1)
#endif


#ifndef SET_UEGO_flgIPmpActvdS1B2 
#define SET_UEGO_flgIPmpActvdS1B2 (UEGO_flgIPmpActvdS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgIPmpActvdS1B2 
#define CLR_UEGO_flgIPmpActvdS1B2 (UEGO_flgIPmpActvdS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgIPmpActvdS1B2 
#define GET_UEGO_flgIPmpActvdS1B2 (UEGO_flgIPmpActvdS1B2)
#endif
#ifndef PUT_UEGO_flgIPmpActvdS1B2 
#define PUT_UEGO_flgIPmpActvdS1B2(val) ((val) ? SET_UEGO_flgIPmpActvdS1B2 : CLR_UEGO_flgIPmpActvdS1B2)
#endif


#ifndef SET_UEGO_flgIPmpCtrlDsbcS1B1 
#define SET_UEGO_flgIPmpCtrlDsbcS1B1 (UEGO_flgIPmpCtrlDsbcS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgIPmpCtrlDsbcS1B1 
#define CLR_UEGO_flgIPmpCtrlDsbcS1B1 (UEGO_flgIPmpCtrlDsbcS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgIPmpCtrlDsbcS1B1 
#define GET_UEGO_flgIPmpCtrlDsbcS1B1 (UEGO_flgIPmpCtrlDsbcS1B1)
#endif
#ifndef PUT_UEGO_flgIPmpCtrlDsbcS1B1 
#define PUT_UEGO_flgIPmpCtrlDsbcS1B1(val) ((val) ? SET_UEGO_flgIPmpCtrlDsbcS1B1 : CLR_UEGO_flgIPmpCtrlDsbcS1B1)
#endif


#ifndef SET_UEGO_flgIPmpCtrlDsbcS1B2 
#define SET_UEGO_flgIPmpCtrlDsbcS1B2 (UEGO_flgIPmpCtrlDsbcS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgIPmpCtrlDsbcS1B2 
#define CLR_UEGO_flgIPmpCtrlDsbcS1B2 (UEGO_flgIPmpCtrlDsbcS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgIPmpCtrlDsbcS1B2 
#define GET_UEGO_flgIPmpCtrlDsbcS1B2 (UEGO_flgIPmpCtrlDsbcS1B2)
#endif
#ifndef PUT_UEGO_flgIPmpCtrlDsbcS1B2 
#define PUT_UEGO_flgIPmpCtrlDsbcS1B2(val) ((val) ? SET_UEGO_flgIPmpCtrlDsbcS1B2 : CLR_UEGO_flgIPmpCtrlDsbcS1B2)
#endif


#ifndef SET_UEGO_flgIPmpDiCond 
#define SET_UEGO_flgIPmpDiCond (UEGO_flgIPmpDiCond=TRUE)
#endif
#ifndef CLR_UEGO_flgIPmpDiCond 
#define CLR_UEGO_flgIPmpDiCond (UEGO_flgIPmpDiCond=FALSE)
#endif
#ifndef GET_UEGO_flgIPmpDiCond 
#define GET_UEGO_flgIPmpDiCond (UEGO_flgIPmpDiCond)
#endif
#ifndef PUT_UEGO_flgIPmpDiCond 
#define PUT_UEGO_flgIPmpDiCond(val) ((val) ? SET_UEGO_flgIPmpDiCond : CLR_UEGO_flgIPmpDiCond)
#endif


#ifndef SET_UEGO_flgIPmpDiS1B1 
#define SET_UEGO_flgIPmpDiS1B1 (UEGO_flgIPmpDiS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgIPmpDiS1B1 
#define CLR_UEGO_flgIPmpDiS1B1 (UEGO_flgIPmpDiS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgIPmpDiS1B1 
#define GET_UEGO_flgIPmpDiS1B1 (UEGO_flgIPmpDiS1B1)
#endif
#ifndef PUT_UEGO_flgIPmpDiS1B1 
#define PUT_UEGO_flgIPmpDiS1B1(val) ((val) ? SET_UEGO_flgIPmpDiS1B1 : CLR_UEGO_flgIPmpDiS1B1)
#endif


#ifndef SET_UEGO_flgIPmpDiS1B2 
#define SET_UEGO_flgIPmpDiS1B2 (UEGO_flgIPmpDiS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgIPmpDiS1B2 
#define CLR_UEGO_flgIPmpDiS1B2 (UEGO_flgIPmpDiS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgIPmpDiS1B2 
#define GET_UEGO_flgIPmpDiS1B2 (UEGO_flgIPmpDiS1B2)
#endif
#ifndef PUT_UEGO_flgIPmpDiS1B2 
#define PUT_UEGO_flgIPmpDiS1B2(val) ((val) ? SET_UEGO_flgIPmpDiS1B2 : CLR_UEGO_flgIPmpDiS1B2)
#endif


#ifndef SET_UEGO_flgIPmpEvlnVldS1B1 
#define SET_UEGO_flgIPmpEvlnVldS1B1 (UEGO_flgIPmpEvlnVldS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgIPmpEvlnVldS1B1 
#define CLR_UEGO_flgIPmpEvlnVldS1B1 (UEGO_flgIPmpEvlnVldS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgIPmpEvlnVldS1B1 
#define GET_UEGO_flgIPmpEvlnVldS1B1 (UEGO_flgIPmpEvlnVldS1B1)
#endif
#ifndef PUT_UEGO_flgIPmpEvlnVldS1B1 
#define PUT_UEGO_flgIPmpEvlnVldS1B1(val) ((val) ? SET_UEGO_flgIPmpEvlnVldS1B1 : CLR_UEGO_flgIPmpEvlnVldS1B1)
#endif


#ifndef SET_UEGO_flgIPmpEvlnVldS1B2 
#define SET_UEGO_flgIPmpEvlnVldS1B2 (UEGO_flgIPmpEvlnVldS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgIPmpEvlnVldS1B2 
#define CLR_UEGO_flgIPmpEvlnVldS1B2 (UEGO_flgIPmpEvlnVldS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgIPmpEvlnVldS1B2 
#define GET_UEGO_flgIPmpEvlnVldS1B2 (UEGO_flgIPmpEvlnVldS1B2)
#endif
#ifndef PUT_UEGO_flgIPmpEvlnVldS1B2 
#define PUT_UEGO_flgIPmpEvlnVldS1B2(val) ((val) ? SET_UEGO_flgIPmpEvlnVldS1B2 : CLR_UEGO_flgIPmpEvlnVldS1B2)
#endif


#ifndef SET_UEGO_flgIPmpRvsChrgVldS1B1 
#define SET_UEGO_flgIPmpRvsChrgVldS1B1 (UEGO_flgIPmpRvsChrgVldS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgIPmpRvsChrgVldS1B1 
#define CLR_UEGO_flgIPmpRvsChrgVldS1B1 (UEGO_flgIPmpRvsChrgVldS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgIPmpRvsChrgVldS1B1 
#define GET_UEGO_flgIPmpRvsChrgVldS1B1 (UEGO_flgIPmpRvsChrgVldS1B1)
#endif
#ifndef PUT_UEGO_flgIPmpRvsChrgVldS1B1 
#define PUT_UEGO_flgIPmpRvsChrgVldS1B1(val) ((val) ? SET_UEGO_flgIPmpRvsChrgVldS1B1 : CLR_UEGO_flgIPmpRvsChrgVldS1B1)
#endif


#ifndef SET_UEGO_flgIPmpRvsChrgVldS1B2 
#define SET_UEGO_flgIPmpRvsChrgVldS1B2 (UEGO_flgIPmpRvsChrgVldS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgIPmpRvsChrgVldS1B2 
#define CLR_UEGO_flgIPmpRvsChrgVldS1B2 (UEGO_flgIPmpRvsChrgVldS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgIPmpRvsChrgVldS1B2 
#define GET_UEGO_flgIPmpRvsChrgVldS1B2 (UEGO_flgIPmpRvsChrgVldS1B2)
#endif
#ifndef PUT_UEGO_flgIPmpRvsChrgVldS1B2 
#define PUT_UEGO_flgIPmpRvsChrgVldS1B2(val) ((val) ? SET_UEGO_flgIPmpRvsChrgVldS1B2 : CLR_UEGO_flgIPmpRvsChrgVldS1B2)
#endif


#ifndef SET_UEGO_flgIsqStrtdS1B1 
#define SET_UEGO_flgIsqStrtdS1B1 (UEGO_flgIsqStrtdS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgIsqStrtdS1B1 
#define CLR_UEGO_flgIsqStrtdS1B1 (UEGO_flgIsqStrtdS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgIsqStrtdS1B1 
#define GET_UEGO_flgIsqStrtdS1B1 (UEGO_flgIsqStrtdS1B1)
#endif
#ifndef PUT_UEGO_flgIsqStrtdS1B1 
#define PUT_UEGO_flgIsqStrtdS1B1(val) ((val) ? SET_UEGO_flgIsqStrtdS1B1 : CLR_UEGO_flgIsqStrtdS1B1)
#endif


#ifndef SET_UEGO_flgIsqStrtdS1B2 
#define SET_UEGO_flgIsqStrtdS1B2 (UEGO_flgIsqStrtdS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgIsqStrtdS1B2 
#define CLR_UEGO_flgIsqStrtdS1B2 (UEGO_flgIsqStrtdS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgIsqStrtdS1B2 
#define GET_UEGO_flgIsqStrtdS1B2 (UEGO_flgIsqStrtdS1B2)
#endif
#ifndef PUT_UEGO_flgIsqStrtdS1B2 
#define PUT_UEGO_flgIsqStrtdS1B2(val) ((val) ? SET_UEGO_flgIsqStrtdS1B2 : CLR_UEGO_flgIsqStrtdS1B2)
#endif


#ifndef SET_UEGO_flgIsqrStrtdS1B1 
#define SET_UEGO_flgIsqrStrtdS1B1 (UEGO_flgIsqrStrtdS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgIsqrStrtdS1B1 
#define CLR_UEGO_flgIsqrStrtdS1B1 (UEGO_flgIsqrStrtdS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgIsqrStrtdS1B1 
#define GET_UEGO_flgIsqrStrtdS1B1 (UEGO_flgIsqrStrtdS1B1)
#endif
#ifndef PUT_UEGO_flgIsqrStrtdS1B1 
#define PUT_UEGO_flgIsqrStrtdS1B1(val) ((val) ? SET_UEGO_flgIsqrStrtdS1B1 : CLR_UEGO_flgIsqrStrtdS1B1)
#endif


#ifndef SET_UEGO_flgIsqrStrtdS1B2 
#define SET_UEGO_flgIsqrStrtdS1B2 (UEGO_flgIsqrStrtdS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgIsqrStrtdS1B2 
#define CLR_UEGO_flgIsqrStrtdS1B2 (UEGO_flgIsqrStrtdS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgIsqrStrtdS1B2 
#define GET_UEGO_flgIsqrStrtdS1B2 (UEGO_flgIsqrStrtdS1B2)
#endif
#ifndef PUT_UEGO_flgIsqrStrtdS1B2 
#define PUT_UEGO_flgIsqrStrtdS1B2(val) ((val) ? SET_UEGO_flgIsqrStrtdS1B2 : CLR_UEGO_flgIsqrStrtdS1B2)
#endif


#ifndef SET_UEGO_flgLamRecprMdlVld 
#define SET_UEGO_flgLamRecprMdlVld (UEGO_flgLamRecprMdlVld=TRUE)
#endif
#ifndef CLR_UEGO_flgLamRecprMdlVld 
#define CLR_UEGO_flgLamRecprMdlVld (UEGO_flgLamRecprMdlVld=FALSE)
#endif
#ifndef GET_UEGO_flgLamRecprMdlVld 
#define GET_UEGO_flgLamRecprMdlVld (UEGO_flgLamRecprMdlVld)
#endif
#ifndef PUT_UEGO_flgLamRecprMdlVld 
#define PUT_UEGO_flgLamRecprMdlVld(val) ((val) ? SET_UEGO_flgLamRecprMdlVld : CLR_UEGO_flgLamRecprMdlVld)
#endif


#ifndef SET_UEGO_flgLoupeNS1B1 
#define SET_UEGO_flgLoupeNS1B1 (UEGO_flgLoupeNS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgLoupeNS1B1 
#define CLR_UEGO_flgLoupeNS1B1 (UEGO_flgLoupeNS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgLoupeNS1B1 
#define GET_UEGO_flgLoupeNS1B1 (UEGO_flgLoupeNS1B1)
#endif
#ifndef PUT_UEGO_flgLoupeNS1B1 
#define PUT_UEGO_flgLoupeNS1B1(val) ((val) ? SET_UEGO_flgLoupeNS1B1 : CLR_UEGO_flgLoupeNS1B1)
#endif


#ifndef SET_UEGO_flgLoupeNS1B2 
#define SET_UEGO_flgLoupeNS1B2 (UEGO_flgLoupeNS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgLoupeNS1B2 
#define CLR_UEGO_flgLoupeNS1B2 (UEGO_flgLoupeNS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgLoupeNS1B2 
#define GET_UEGO_flgLoupeNS1B2 (UEGO_flgLoupeNS1B2)
#endif
#ifndef PUT_UEGO_flgLoupeNS1B2 
#define PUT_UEGO_flgLoupeNS1B2(val) ((val) ? SET_UEGO_flgLoupeNS1B2 : CLR_UEGO_flgLoupeNS1B2)
#endif


#ifndef SET_UEGO_flgLoupePS1B1 
#define SET_UEGO_flgLoupePS1B1 (UEGO_flgLoupePS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgLoupePS1B1 
#define CLR_UEGO_flgLoupePS1B1 (UEGO_flgLoupePS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgLoupePS1B1 
#define GET_UEGO_flgLoupePS1B1 (UEGO_flgLoupePS1B1)
#endif
#ifndef PUT_UEGO_flgLoupePS1B1 
#define PUT_UEGO_flgLoupePS1B1(val) ((val) ? SET_UEGO_flgLoupePS1B1 : CLR_UEGO_flgLoupePS1B1)
#endif


#ifndef SET_UEGO_flgLoupePS1B2 
#define SET_UEGO_flgLoupePS1B2 (UEGO_flgLoupePS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgLoupePS1B2 
#define CLR_UEGO_flgLoupePS1B2 (UEGO_flgLoupePS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgLoupePS1B2 
#define GET_UEGO_flgLoupePS1B2 (UEGO_flgLoupePS1B2)
#endif
#ifndef PUT_UEGO_flgLoupePS1B2 
#define PUT_UEGO_flgLoupePS1B2(val) ((val) ? SET_UEGO_flgLoupePS1B2 : CLR_UEGO_flgLoupePS1B2)
#endif


#ifndef SET_UEGO_flgNewIPmpRvsChrgS1B1 
#define SET_UEGO_flgNewIPmpRvsChrgS1B1 (UEGO_flgNewIPmpRvsChrgS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgNewIPmpRvsChrgS1B1 
#define CLR_UEGO_flgNewIPmpRvsChrgS1B1 (UEGO_flgNewIPmpRvsChrgS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgNewIPmpRvsChrgS1B1 
#define GET_UEGO_flgNewIPmpRvsChrgS1B1 (UEGO_flgNewIPmpRvsChrgS1B1)
#endif
#ifndef PUT_UEGO_flgNewIPmpRvsChrgS1B1 
#define PUT_UEGO_flgNewIPmpRvsChrgS1B1(val) ((val) ? SET_UEGO_flgNewIPmpRvsChrgS1B1 : CLR_UEGO_flgNewIPmpRvsChrgS1B1)
#endif


#ifndef SET_UEGO_flgNewIPmpRvsChrgS1B2 
#define SET_UEGO_flgNewIPmpRvsChrgS1B2 (UEGO_flgNewIPmpRvsChrgS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgNewIPmpRvsChrgS1B2 
#define CLR_UEGO_flgNewIPmpRvsChrgS1B2 (UEGO_flgNewIPmpRvsChrgS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgNewIPmpRvsChrgS1B2 
#define GET_UEGO_flgNewIPmpRvsChrgS1B2 (UEGO_flgNewIPmpRvsChrgS1B2)
#endif
#ifndef PUT_UEGO_flgNewIPmpRvsChrgS1B2 
#define PUT_UEGO_flgNewIPmpRvsChrgS1B2(val) ((val) ? SET_UEGO_flgNewIPmpRvsChrgS1B2 : CLR_UEGO_flgNewIPmpRvsChrgS1B2)
#endif


#ifndef SET_UEGO_flgNewPacS1B1 
#define SET_UEGO_flgNewPacS1B1 (UEGO_flgNewPacS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgNewPacS1B1 
#define CLR_UEGO_flgNewPacS1B1 (UEGO_flgNewPacS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgNewPacS1B1 
#define GET_UEGO_flgNewPacS1B1 (UEGO_flgNewPacS1B1)
#endif
#ifndef PUT_UEGO_flgNewPacS1B1 
#define PUT_UEGO_flgNewPacS1B1(val) ((val) ? SET_UEGO_flgNewPacS1B1 : CLR_UEGO_flgNewPacS1B1)
#endif


#ifndef SET_UEGO_flgNewPacS1B2 
#define SET_UEGO_flgNewPacS1B2 (UEGO_flgNewPacS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgNewPacS1B2 
#define CLR_UEGO_flgNewPacS1B2 (UEGO_flgNewPacS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgNewPacS1B2 
#define GET_UEGO_flgNewPacS1B2 (UEGO_flgNewPacS1B2)
#endif
#ifndef PUT_UEGO_flgNewPacS1B2 
#define PUT_UEGO_flgNewPacS1B2(val) ((val) ? SET_UEGO_flgNewPacS1B2 : CLR_UEGO_flgNewPacS1B2)
#endif


#ifndef SET_UEGO_flgPostDrvExtn 
#define SET_UEGO_flgPostDrvExtn (UEGO_flgPostDrvExtn=TRUE)
#endif
#ifndef CLR_UEGO_flgPostDrvExtn 
#define CLR_UEGO_flgPostDrvExtn (UEGO_flgPostDrvExtn=FALSE)
#endif
#ifndef GET_UEGO_flgPostDrvExtn 
#define GET_UEGO_flgPostDrvExtn (UEGO_flgPostDrvExtn)
#endif
#ifndef PUT_UEGO_flgPostDrvExtn 
#define PUT_UEGO_flgPostDrvExtn(val) ((val) ? SET_UEGO_flgPostDrvExtn : CLR_UEGO_flgPostDrvExtn)
#endif


#ifndef SET_UEGO_flgRTEvlnVldS1B1 
#define SET_UEGO_flgRTEvlnVldS1B1 (UEGO_flgRTEvlnVldS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgRTEvlnVldS1B1 
#define CLR_UEGO_flgRTEvlnVldS1B1 (UEGO_flgRTEvlnVldS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgRTEvlnVldS1B1 
#define GET_UEGO_flgRTEvlnVldS1B1 (UEGO_flgRTEvlnVldS1B1)
#endif
#ifndef PUT_UEGO_flgRTEvlnVldS1B1 
#define PUT_UEGO_flgRTEvlnVldS1B1(val) ((val) ? SET_UEGO_flgRTEvlnVldS1B1 : CLR_UEGO_flgRTEvlnVldS1B1)
#endif


#ifndef SET_UEGO_flgRTEvlnVldS1B2 
#define SET_UEGO_flgRTEvlnVldS1B2 (UEGO_flgRTEvlnVldS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgRTEvlnVldS1B2 
#define CLR_UEGO_flgRTEvlnVldS1B2 (UEGO_flgRTEvlnVldS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgRTEvlnVldS1B2 
#define GET_UEGO_flgRTEvlnVldS1B2 (UEGO_flgRTEvlnVldS1B2)
#endif
#ifndef PUT_UEGO_flgRTEvlnVldS1B2 
#define PUT_UEGO_flgRTEvlnVldS1B2(val) ((val) ? SET_UEGO_flgRTEvlnVldS1B2 : CLR_UEGO_flgRTEvlnVldS1B2)
#endif


#ifndef SET_UEGO_flgRpcRelsS1B1 
#define SET_UEGO_flgRpcRelsS1B1 (UEGO_flgRpcRelsS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgRpcRelsS1B1 
#define CLR_UEGO_flgRpcRelsS1B1 (UEGO_flgRpcRelsS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgRpcRelsS1B1 
#define GET_UEGO_flgRpcRelsS1B1 (UEGO_flgRpcRelsS1B1)
#endif
#ifndef PUT_UEGO_flgRpcRelsS1B1 
#define PUT_UEGO_flgRpcRelsS1B1(val) ((val) ? SET_UEGO_flgRpcRelsS1B1 : CLR_UEGO_flgRpcRelsS1B1)
#endif


#ifndef SET_UEGO_flgRpcRelsS1B2 
#define SET_UEGO_flgRpcRelsS1B2 (UEGO_flgRpcRelsS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgRpcRelsS1B2 
#define CLR_UEGO_flgRpcRelsS1B2 (UEGO_flgRpcRelsS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgRpcRelsS1B2 
#define GET_UEGO_flgRpcRelsS1B2 (UEGO_flgRpcRelsS1B2)
#endif
#ifndef PUT_UEGO_flgRpcRelsS1B2 
#define PUT_UEGO_flgRpcRelsS1B2(val) ((val) ? SET_UEGO_flgRpcRelsS1B2 : CLR_UEGO_flgRpcRelsS1B2)
#endif


#ifndef SET_UEGO_flgRpcReqdS1B1 
#define SET_UEGO_flgRpcReqdS1B1 (UEGO_flgRpcReqdS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgRpcReqdS1B1 
#define CLR_UEGO_flgRpcReqdS1B1 (UEGO_flgRpcReqdS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgRpcReqdS1B1 
#define GET_UEGO_flgRpcReqdS1B1 (UEGO_flgRpcReqdS1B1)
#endif
#ifndef PUT_UEGO_flgRpcReqdS1B1 
#define PUT_UEGO_flgRpcReqdS1B1(val) ((val) ? SET_UEGO_flgRpcReqdS1B1 : CLR_UEGO_flgRpcReqdS1B1)
#endif


#ifndef SET_UEGO_flgRpcReqdS1B2 
#define SET_UEGO_flgRpcReqdS1B2 (UEGO_flgRpcReqdS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgRpcReqdS1B2 
#define CLR_UEGO_flgRpcReqdS1B2 (UEGO_flgRpcReqdS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgRpcReqdS1B2 
#define GET_UEGO_flgRpcReqdS1B2 (UEGO_flgRpcReqdS1B2)
#endif
#ifndef PUT_UEGO_flgRpcReqdS1B2 
#define PUT_UEGO_flgRpcReqdS1B2(val) ((val) ? SET_UEGO_flgRpcReqdS1B2 : CLR_UEGO_flgRpcReqdS1B2)
#endif


#ifndef SET_UEGO_flgTestGetRevC1 
#define SET_UEGO_flgTestGetRevC1 (UEGO_flgTestGetRevC1=TRUE)
#endif
#ifndef CLR_UEGO_flgTestGetRevC1 
#define CLR_UEGO_flgTestGetRevC1 (UEGO_flgTestGetRevC1=FALSE)
#endif
#ifndef GET_UEGO_flgTestGetRevC1 
#define GET_UEGO_flgTestGetRevC1 (UEGO_flgTestGetRevC1)
#endif
#ifndef PUT_UEGO_flgTestGetRevC1 
#define PUT_UEGO_flgTestGetRevC1(val) ((val) ? SET_UEGO_flgTestGetRevC1 : CLR_UEGO_flgTestGetRevC1)
#endif


#ifndef SET_UEGO_flgUBattMax 
#define SET_UEGO_flgUBattMax (UEGO_flgUBattMax=TRUE)
#endif
#ifndef CLR_UEGO_flgUBattMax 
#define CLR_UEGO_flgUBattMax (UEGO_flgUBattMax=FALSE)
#endif
#ifndef GET_UEGO_flgUBattMax 
#define GET_UEGO_flgUBattMax (UEGO_flgUBattMax)
#endif
#ifndef PUT_UEGO_flgUBattMax 
#define PUT_UEGO_flgUBattMax(val) ((val) ? SET_UEGO_flgUBattMax : CLR_UEGO_flgUBattMax)
#endif


#ifndef SET_UEGO_flgUBattMin 
#define SET_UEGO_flgUBattMin (UEGO_flgUBattMin=TRUE)
#endif
#ifndef CLR_UEGO_flgUBattMin 
#define CLR_UEGO_flgUBattMin (UEGO_flgUBattMin=FALSE)
#endif
#ifndef GET_UEGO_flgUBattMin 
#define GET_UEGO_flgUBattMin (UEGO_flgUBattMin)
#endif
#ifndef PUT_UEGO_flgUBattMin 
#define PUT_UEGO_flgUBattMin(val) ((val) ? SET_UEGO_flgUBattMin : CLR_UEGO_flgUBattMin)
#endif


#ifndef SET_UEGO_flgURIAS1B1 
#define SET_UEGO_flgURIAS1B1 (UEGO_flgURIAS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgURIAS1B1 
#define CLR_UEGO_flgURIAS1B1 (UEGO_flgURIAS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgURIAS1B1 
#define GET_UEGO_flgURIAS1B1 (UEGO_flgURIAS1B1)
#endif
#ifndef PUT_UEGO_flgURIAS1B1 
#define PUT_UEGO_flgURIAS1B1(val) ((val) ? SET_UEGO_flgURIAS1B1 : CLR_UEGO_flgURIAS1B1)
#endif


#ifndef SET_UEGO_flgURIAS1B2 
#define SET_UEGO_flgURIAS1B2 (UEGO_flgURIAS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgURIAS1B2 
#define CLR_UEGO_flgURIAS1B2 (UEGO_flgURIAS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgURIAS1B2 
#define GET_UEGO_flgURIAS1B2 (UEGO_flgURIAS1B2)
#endif
#ifndef PUT_UEGO_flgURIAS1B2 
#define PUT_UEGO_flgURIAS1B2(val) ((val) ? SET_UEGO_flgURIAS1B2 : CLR_UEGO_flgURIAS1B2)
#endif


#ifndef SET_UEGO_flgUiAllMeasS1B1 
#define SET_UEGO_flgUiAllMeasS1B1 (UEGO_flgUiAllMeasS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgUiAllMeasS1B1 
#define CLR_UEGO_flgUiAllMeasS1B1 (UEGO_flgUiAllMeasS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgUiAllMeasS1B1 
#define GET_UEGO_flgUiAllMeasS1B1 (UEGO_flgUiAllMeasS1B1)
#endif
#ifndef PUT_UEGO_flgUiAllMeasS1B1 
#define PUT_UEGO_flgUiAllMeasS1B1(val) ((val) ? SET_UEGO_flgUiAllMeasS1B1 : CLR_UEGO_flgUiAllMeasS1B1)
#endif


#ifndef SET_UEGO_flgUiAllMeasS1B2 
#define SET_UEGO_flgUiAllMeasS1B2 (UEGO_flgUiAllMeasS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgUiAllMeasS1B2 
#define CLR_UEGO_flgUiAllMeasS1B2 (UEGO_flgUiAllMeasS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgUiAllMeasS1B2 
#define GET_UEGO_flgUiAllMeasS1B2 (UEGO_flgUiAllMeasS1B2)
#endif
#ifndef PUT_UEGO_flgUiAllMeasS1B2 
#define PUT_UEGO_flgUiAllMeasS1B2(val) ((val) ? SET_UEGO_flgUiAllMeasS1B2 : CLR_UEGO_flgUiAllMeasS1B2)
#endif


#ifndef SET_UEGO_flgUoffipe1Z1StrtdS1B1 
#define SET_UEGO_flgUoffipe1Z1StrtdS1B1 (UEGO_flgUoffipe1Z1StrtdS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgUoffipe1Z1StrtdS1B1 
#define CLR_UEGO_flgUoffipe1Z1StrtdS1B1 (UEGO_flgUoffipe1Z1StrtdS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgUoffipe1Z1StrtdS1B1 
#define GET_UEGO_flgUoffipe1Z1StrtdS1B1 (UEGO_flgUoffipe1Z1StrtdS1B1)
#endif
#ifndef PUT_UEGO_flgUoffipe1Z1StrtdS1B1 
#define PUT_UEGO_flgUoffipe1Z1StrtdS1B1(val) ((val) ? SET_UEGO_flgUoffipe1Z1StrtdS1B1 : CLR_UEGO_flgUoffipe1Z1StrtdS1B1)
#endif


#ifndef SET_UEGO_flgUoffipe1Z1StrtdS1B2 
#define SET_UEGO_flgUoffipe1Z1StrtdS1B2 (UEGO_flgUoffipe1Z1StrtdS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgUoffipe1Z1StrtdS1B2 
#define CLR_UEGO_flgUoffipe1Z1StrtdS1B2 (UEGO_flgUoffipe1Z1StrtdS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgUoffipe1Z1StrtdS1B2 
#define GET_UEGO_flgUoffipe1Z1StrtdS1B2 (UEGO_flgUoffipe1Z1StrtdS1B2)
#endif
#ifndef PUT_UEGO_flgUoffipe1Z1StrtdS1B2 
#define PUT_UEGO_flgUoffipe1Z1StrtdS1B2(val) ((val) ? SET_UEGO_flgUoffipe1Z1StrtdS1B2 : CLR_UEGO_flgUoffipe1Z1StrtdS1B2)
#endif


#ifndef SET_UEGO_flgUoffipe1Z2StrtdS1B1 
#define SET_UEGO_flgUoffipe1Z2StrtdS1B1 (UEGO_flgUoffipe1Z2StrtdS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgUoffipe1Z2StrtdS1B1 
#define CLR_UEGO_flgUoffipe1Z2StrtdS1B1 (UEGO_flgUoffipe1Z2StrtdS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgUoffipe1Z2StrtdS1B1 
#define GET_UEGO_flgUoffipe1Z2StrtdS1B1 (UEGO_flgUoffipe1Z2StrtdS1B1)
#endif
#ifndef PUT_UEGO_flgUoffipe1Z2StrtdS1B1 
#define PUT_UEGO_flgUoffipe1Z2StrtdS1B1(val) ((val) ? SET_UEGO_flgUoffipe1Z2StrtdS1B1 : CLR_UEGO_flgUoffipe1Z2StrtdS1B1)
#endif


#ifndef SET_UEGO_flgUoffipe1Z2StrtdS1B2 
#define SET_UEGO_flgUoffipe1Z2StrtdS1B2 (UEGO_flgUoffipe1Z2StrtdS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgUoffipe1Z2StrtdS1B2 
#define CLR_UEGO_flgUoffipe1Z2StrtdS1B2 (UEGO_flgUoffipe1Z2StrtdS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgUoffipe1Z2StrtdS1B2 
#define GET_UEGO_flgUoffipe1Z2StrtdS1B2 (UEGO_flgUoffipe1Z2StrtdS1B2)
#endif
#ifndef PUT_UEGO_flgUoffipe1Z2StrtdS1B2 
#define PUT_UEGO_flgUoffipe1Z2StrtdS1B2(val) ((val) ? SET_UEGO_flgUoffipe1Z2StrtdS1B2 : CLR_UEGO_flgUoffipe1Z2StrtdS1B2)
#endif


#ifndef SET_UEGO_flgUoffipe2Z1StrtdS1B1 
#define SET_UEGO_flgUoffipe2Z1StrtdS1B1 (UEGO_flgUoffipe2Z1StrtdS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgUoffipe2Z1StrtdS1B1 
#define CLR_UEGO_flgUoffipe2Z1StrtdS1B1 (UEGO_flgUoffipe2Z1StrtdS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgUoffipe2Z1StrtdS1B1 
#define GET_UEGO_flgUoffipe2Z1StrtdS1B1 (UEGO_flgUoffipe2Z1StrtdS1B1)
#endif
#ifndef PUT_UEGO_flgUoffipe2Z1StrtdS1B1 
#define PUT_UEGO_flgUoffipe2Z1StrtdS1B1(val) ((val) ? SET_UEGO_flgUoffipe2Z1StrtdS1B1 : CLR_UEGO_flgUoffipe2Z1StrtdS1B1)
#endif


#ifndef SET_UEGO_flgUoffipe2Z1StrtdS1B2 
#define SET_UEGO_flgUoffipe2Z1StrtdS1B2 (UEGO_flgUoffipe2Z1StrtdS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgUoffipe2Z1StrtdS1B2 
#define CLR_UEGO_flgUoffipe2Z1StrtdS1B2 (UEGO_flgUoffipe2Z1StrtdS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgUoffipe2Z1StrtdS1B2 
#define GET_UEGO_flgUoffipe2Z1StrtdS1B2 (UEGO_flgUoffipe2Z1StrtdS1B2)
#endif
#ifndef PUT_UEGO_flgUoffipe2Z1StrtdS1B2 
#define PUT_UEGO_flgUoffipe2Z1StrtdS1B2(val) ((val) ? SET_UEGO_flgUoffipe2Z1StrtdS1B2 : CLR_UEGO_flgUoffipe2Z1StrtdS1B2)
#endif


#ifndef SET_UEGO_flgUoffipe2Z2StrtdS1B1 
#define SET_UEGO_flgUoffipe2Z2StrtdS1B1 (UEGO_flgUoffipe2Z2StrtdS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgUoffipe2Z2StrtdS1B1 
#define CLR_UEGO_flgUoffipe2Z2StrtdS1B1 (UEGO_flgUoffipe2Z2StrtdS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgUoffipe2Z2StrtdS1B1 
#define GET_UEGO_flgUoffipe2Z2StrtdS1B1 (UEGO_flgUoffipe2Z2StrtdS1B1)
#endif
#ifndef PUT_UEGO_flgUoffipe2Z2StrtdS1B1 
#define PUT_UEGO_flgUoffipe2Z2StrtdS1B1(val) ((val) ? SET_UEGO_flgUoffipe2Z2StrtdS1B1 : CLR_UEGO_flgUoffipe2Z2StrtdS1B1)
#endif


#ifndef SET_UEGO_flgUoffipe2Z2StrtdS1B2 
#define SET_UEGO_flgUoffipe2Z2StrtdS1B2 (UEGO_flgUoffipe2Z2StrtdS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgUoffipe2Z2StrtdS1B2 
#define CLR_UEGO_flgUoffipe2Z2StrtdS1B2 (UEGO_flgUoffipe2Z2StrtdS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgUoffipe2Z2StrtdS1B2 
#define GET_UEGO_flgUoffipe2Z2StrtdS1B2 (UEGO_flgUoffipe2Z2StrtdS1B2)
#endif
#ifndef PUT_UEGO_flgUoffipe2Z2StrtdS1B2 
#define PUT_UEGO_flgUoffipe2Z2StrtdS1B2(val) ((val) ? SET_UEGO_flgUoffipe2Z2StrtdS1B2 : CLR_UEGO_flgUoffipe2Z2StrtdS1B2)
#endif


#ifndef SET_UEGO_flgUoffvcc1StrtdS1B1 
#define SET_UEGO_flgUoffvcc1StrtdS1B1 (UEGO_flgUoffvcc1StrtdS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgUoffvcc1StrtdS1B1 
#define CLR_UEGO_flgUoffvcc1StrtdS1B1 (UEGO_flgUoffvcc1StrtdS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgUoffvcc1StrtdS1B1 
#define GET_UEGO_flgUoffvcc1StrtdS1B1 (UEGO_flgUoffvcc1StrtdS1B1)
#endif
#ifndef PUT_UEGO_flgUoffvcc1StrtdS1B1 
#define PUT_UEGO_flgUoffvcc1StrtdS1B1(val) ((val) ? SET_UEGO_flgUoffvcc1StrtdS1B1 : CLR_UEGO_flgUoffvcc1StrtdS1B1)
#endif


#ifndef SET_UEGO_flgUoffvcc1StrtdS1B2 
#define SET_UEGO_flgUoffvcc1StrtdS1B2 (UEGO_flgUoffvcc1StrtdS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgUoffvcc1StrtdS1B2 
#define CLR_UEGO_flgUoffvcc1StrtdS1B2 (UEGO_flgUoffvcc1StrtdS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgUoffvcc1StrtdS1B2 
#define GET_UEGO_flgUoffvcc1StrtdS1B2 (UEGO_flgUoffvcc1StrtdS1B2)
#endif
#ifndef PUT_UEGO_flgUoffvcc1StrtdS1B2 
#define PUT_UEGO_flgUoffvcc1StrtdS1B2(val) ((val) ? SET_UEGO_flgUoffvcc1StrtdS1B2 : CLR_UEGO_flgUoffvcc1StrtdS1B2)
#endif


#ifndef SET_UEGO_flgUoffvcc2StrtdS1B1 
#define SET_UEGO_flgUoffvcc2StrtdS1B1 (UEGO_flgUoffvcc2StrtdS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgUoffvcc2StrtdS1B1 
#define CLR_UEGO_flgUoffvcc2StrtdS1B1 (UEGO_flgUoffvcc2StrtdS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgUoffvcc2StrtdS1B1 
#define GET_UEGO_flgUoffvcc2StrtdS1B1 (UEGO_flgUoffvcc2StrtdS1B1)
#endif
#ifndef PUT_UEGO_flgUoffvcc2StrtdS1B1 
#define PUT_UEGO_flgUoffvcc2StrtdS1B1(val) ((val) ? SET_UEGO_flgUoffvcc2StrtdS1B1 : CLR_UEGO_flgUoffvcc2StrtdS1B1)
#endif


#ifndef SET_UEGO_flgUoffvcc2StrtdS1B2 
#define SET_UEGO_flgUoffvcc2StrtdS1B2 (UEGO_flgUoffvcc2StrtdS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgUoffvcc2StrtdS1B2 
#define CLR_UEGO_flgUoffvcc2StrtdS1B2 (UEGO_flgUoffvcc2StrtdS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgUoffvcc2StrtdS1B2 
#define GET_UEGO_flgUoffvcc2StrtdS1B2 (UEGO_flgUoffvcc2StrtdS1B2)
#endif
#ifndef PUT_UEGO_flgUoffvcc2StrtdS1B2 
#define PUT_UEGO_flgUoffvcc2StrtdS1B2(val) ((val) ? SET_UEGO_flgUoffvcc2StrtdS1B2 : CLR_UEGO_flgUoffvcc2StrtdS1B2)
#endif


#ifndef SET_UEGO_flgUoffvcc3StrtdS1B1 
#define SET_UEGO_flgUoffvcc3StrtdS1B1 (UEGO_flgUoffvcc3StrtdS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgUoffvcc3StrtdS1B1 
#define CLR_UEGO_flgUoffvcc3StrtdS1B1 (UEGO_flgUoffvcc3StrtdS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgUoffvcc3StrtdS1B1 
#define GET_UEGO_flgUoffvcc3StrtdS1B1 (UEGO_flgUoffvcc3StrtdS1B1)
#endif
#ifndef PUT_UEGO_flgUoffvcc3StrtdS1B1 
#define PUT_UEGO_flgUoffvcc3StrtdS1B1(val) ((val) ? SET_UEGO_flgUoffvcc3StrtdS1B1 : CLR_UEGO_flgUoffvcc3StrtdS1B1)
#endif


#ifndef SET_UEGO_flgUoffvcc3StrtdS1B2 
#define SET_UEGO_flgUoffvcc3StrtdS1B2 (UEGO_flgUoffvcc3StrtdS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgUoffvcc3StrtdS1B2 
#define CLR_UEGO_flgUoffvcc3StrtdS1B2 (UEGO_flgUoffvcc3StrtdS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgUoffvcc3StrtdS1B2 
#define GET_UEGO_flgUoffvcc3StrtdS1B2 (UEGO_flgUoffvcc3StrtdS1B2)
#endif
#ifndef PUT_UEGO_flgUoffvcc3StrtdS1B2 
#define PUT_UEGO_flgUoffvcc3StrtdS1B2(val) ((val) ? SET_UEGO_flgUoffvcc3StrtdS1B2 : CLR_UEGO_flgUoffvcc3StrtdS1B2)
#endif


#ifndef SET_UEGO_flgUoffvcci2StrtdS1B1 
#define SET_UEGO_flgUoffvcci2StrtdS1B1 (UEGO_flgUoffvcci2StrtdS1B1=TRUE)
#endif
#ifndef CLR_UEGO_flgUoffvcci2StrtdS1B1 
#define CLR_UEGO_flgUoffvcci2StrtdS1B1 (UEGO_flgUoffvcci2StrtdS1B1=FALSE)
#endif
#ifndef GET_UEGO_flgUoffvcci2StrtdS1B1 
#define GET_UEGO_flgUoffvcci2StrtdS1B1 (UEGO_flgUoffvcci2StrtdS1B1)
#endif
#ifndef PUT_UEGO_flgUoffvcci2StrtdS1B1 
#define PUT_UEGO_flgUoffvcci2StrtdS1B1(val) ((val) ? SET_UEGO_flgUoffvcci2StrtdS1B1 : CLR_UEGO_flgUoffvcci2StrtdS1B1)
#endif


#ifndef SET_UEGO_flgUoffvcci2StrtdS1B2 
#define SET_UEGO_flgUoffvcci2StrtdS1B2 (UEGO_flgUoffvcci2StrtdS1B2=TRUE)
#endif
#ifndef CLR_UEGO_flgUoffvcci2StrtdS1B2 
#define CLR_UEGO_flgUoffvcci2StrtdS1B2 (UEGO_flgUoffvcci2StrtdS1B2=FALSE)
#endif
#ifndef GET_UEGO_flgUoffvcci2StrtdS1B2 
#define GET_UEGO_flgUoffvcci2StrtdS1B2 (UEGO_flgUoffvcci2StrtdS1B2)
#endif
#ifndef PUT_UEGO_flgUoffvcci2StrtdS1B2 
#define PUT_UEGO_flgUoffvcci2StrtdS1B2(val) ((val) ? SET_UEGO_flgUoffvcci2StrtdS1B2 : CLR_UEGO_flgUoffvcci2StrtdS1B2)
#endif

#endif
