/********************************************************************************
FILE:         coeng_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _COENG_MSG_H
#define _COENG_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __COENG_TIAFTERRUN_EXT__
#define __COENG_TIAFTERRUN_EXT__
extern uint32 CoEng_tiAfterrun;
#endif /* __COENG_TIAFTERRUN_EXT__ */

#ifndef __COENG_TICRANKING_EXT__
#define __COENG_TICRANKING_EXT__
extern uint32 CoEng_tiCranking;
#endif /* __COENG_TICRANKING_EXT__ */

#ifndef __COENG_TINORMAL_EXT__
#define __COENG_TINORMAL_EXT__
extern uint32 CoEng_tiNormal;
#endif /* __COENG_TINORMAL_EXT__ */

#ifndef __COENG_TIST_EXT__
#define __COENG_TIST_EXT__
extern uint32 CoEng_tiSt[];
#endif /* __COENG_TIST_EXT__ */

#ifndef __COENG_TISTANDBY_EXT__
#define __COENG_TISTANDBY_EXT__
extern uint32 CoEng_tiStandby;
#endif /* __COENG_TISTANDBY_EXT__ */

#ifndef __COENG_TISTART_EXT__
#define __COENG_TISTART_EXT__
extern uint32 CoEng_tiStart;
#endif /* __COENG_TISTART_EXT__ */

#ifndef __COENG_TIAFTERRUNRED_EXT__
#define __COENG_TIAFTERRUNRED_EXT__
extern sint16 CoEng_tiAfterrunRed;
#endif /* __COENG_TIAFTERRUNRED_EXT__ */

#ifndef __COENG_TICRANKINGRED_EXT__
#define __COENG_TICRANKINGRED_EXT__
extern sint16 CoEng_tiCrankingRed;
#endif /* __COENG_TICRANKINGRED_EXT__ */

#ifndef __COENG_TINORMALRED_EXT__
#define __COENG_TINORMALRED_EXT__
extern sint16 CoEng_tiNormalRed;
#endif /* __COENG_TINORMALRED_EXT__ */

#ifndef __COENG_TISTANDBYRED_EXT__
#define __COENG_TISTANDBYRED_EXT__
extern sint16 CoEng_tiStandbyRed;
#endif /* __COENG_TISTANDBYRED_EXT__ */

#ifndef __COENG_TISTARTRED_EXT__
#define __COENG_TISTARTRED_EXT__
extern sint16 CoEng_tiStartRed;
#endif /* __COENG_TISTARTRED_EXT__ */

#ifndef __EPM_NENG_EXT__
#define __EPM_NENG_EXT__
extern sint16 Epm_nEng;
#endif /* __EPM_NENG_EXT__ */

#ifndef __COENG_ST_EXT__
#define __COENG_ST_EXT__
extern uint8                    CoEng_st;
#endif /* __COENG_ST_EXT__ */

#ifndef __COENG_STOLD_EXT__
#define __COENG_STOLD_EXT__
extern uint8                    CoEng_stOld;
#endif /* __COENG_STOLD_EXT__ */

#ifndef __SYC_STSUB_EXT__
#define __SYC_STSUB_EXT__
extern uint8                    SyC_stSub;
#endif /* __SYC_STSUB_EXT__ */

#ifndef __COENG_BSTALENG_EXT__
#define __COENG_BSTALENG_EXT__
extern _bit                     CoEng_bStalEng;
#endif /* __COENG_BSTALENG_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_CoEng_st 
#define SET_CoEng_st (CoEng_st=TRUE)
#endif
#ifndef CLR_CoEng_st 
#define CLR_CoEng_st (CoEng_st=FALSE)
#endif
#ifndef GET_CoEng_st 
#define GET_CoEng_st (CoEng_st)
#endif
#ifndef PUT_CoEng_st 
#define PUT_CoEng_st(val) ((val) ? SET_CoEng_st : CLR_CoEng_st)
#endif


#ifndef SET_CoEng_stOld 
#define SET_CoEng_stOld (CoEng_stOld=TRUE)
#endif
#ifndef CLR_CoEng_stOld 
#define CLR_CoEng_stOld (CoEng_stOld=FALSE)
#endif
#ifndef GET_CoEng_stOld 
#define GET_CoEng_stOld (CoEng_stOld)
#endif
#ifndef PUT_CoEng_stOld 
#define PUT_CoEng_stOld(val) ((val) ? SET_CoEng_stOld : CLR_CoEng_stOld)
#endif


#ifndef SET_SyC_stSub 
#define SET_SyC_stSub (SyC_stSub=TRUE)
#endif
#ifndef CLR_SyC_stSub 
#define CLR_SyC_stSub (SyC_stSub=FALSE)
#endif
#ifndef GET_SyC_stSub 
#define GET_SyC_stSub (SyC_stSub)
#endif
#ifndef PUT_SyC_stSub 
#define PUT_SyC_stSub(val) ((val) ? SET_SyC_stSub : CLR_SyC_stSub)
#endif


#ifndef SET_CoEng_bStalEng 
#define SET_CoEng_bStalEng (CoEng_bStalEng=TRUE)
#endif
#ifndef CLR_CoEng_bStalEng 
#define CLR_CoEng_bStalEng (CoEng_bStalEng=FALSE)
#endif
#ifndef GET_CoEng_bStalEng 
#define GET_CoEng_bStalEng (CoEng_bStalEng)
#endif
#ifndef PUT_CoEng_bStalEng 
#define PUT_CoEng_bStalEng(val) ((val) ? SET_CoEng_bStalEng : CLR_CoEng_bStalEng)
#endif

#endif
