/********************************************************************************
FILE:         dsmappl_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _DSMAPPL_MSG_H
#define _DSMAPPL_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __SYC_TIDRV_EXT__
#define __SYC_TIDRV_EXT__
extern uint32 SyC_tiDrv;
#endif /* __SYC_TIDRV_EXT__ */

#ifndef __EPM_NENG_EXT__
#define __EPM_NENG_EXT__
extern sint16 Epm_nEng;
#endif /* __EPM_NENG_EXT__ */

#ifndef __COENG_ST_EXT__
#define __COENG_ST_EXT__
extern uint8                    CoEng_st;
#endif /* __COENG_ST_EXT__ */

#ifndef __SYC_STSUB_EXT__
#define __SYC_STSUB_EXT__
extern uint8                    SyC_stSub;
#endif /* __SYC_STSUB_EXT__ */

#ifndef __SYC_STSUBOLD_EXT__
#define __SYC_STSUBOLD_EXT__
extern uint8                    SyC_stSubOld;
#endif /* __SYC_STSUBOLD_EXT__ */

#ifndef __T15_STRAW_EXT__
#define __T15_STRAW_EXT__
extern uint8                    T15_stRaw;
#endif /* __T15_STRAW_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_CoEng_st 
#define SET_CoEng_st (CoEng_st=TRUE)
#endif
#ifndef CLR_CoEng_st 
#define CLR_CoEng_st (CoEng_st=FALSE)
#endif
#ifndef GET_CoEng_st 
#define GET_CoEng_st (CoEng_st)
#endif
#ifndef PUT_CoEng_st 
#define PUT_CoEng_st(val) ((val) ? SET_CoEng_st : CLR_CoEng_st)
#endif


#ifndef SET_SyC_stSub 
#define SET_SyC_stSub (SyC_stSub=TRUE)
#endif
#ifndef CLR_SyC_stSub 
#define CLR_SyC_stSub (SyC_stSub=FALSE)
#endif
#ifndef GET_SyC_stSub 
#define GET_SyC_stSub (SyC_stSub)
#endif
#ifndef PUT_SyC_stSub 
#define PUT_SyC_stSub(val) ((val) ? SET_SyC_stSub : CLR_SyC_stSub)
#endif


#ifndef SET_SyC_stSubOld 
#define SET_SyC_stSubOld (SyC_stSubOld=TRUE)
#endif
#ifndef CLR_SyC_stSubOld 
#define CLR_SyC_stSubOld (SyC_stSubOld=FALSE)
#endif
#ifndef GET_SyC_stSubOld 
#define GET_SyC_stSubOld (SyC_stSubOld)
#endif
#ifndef PUT_SyC_stSubOld 
#define PUT_SyC_stSubOld(val) ((val) ? SET_SyC_stSubOld : CLR_SyC_stSubOld)
#endif


#ifndef SET_T15_stRaw 
#define SET_T15_stRaw (T15_stRaw=TRUE)
#endif
#ifndef CLR_T15_stRaw 
#define CLR_T15_stRaw (T15_stRaw=FALSE)
#endif
#ifndef GET_T15_stRaw 
#define GET_T15_stRaw (T15_stRaw)
#endif
#ifndef PUT_T15_stRaw 
#define PUT_T15_stRaw(val) ((val) ? SET_T15_stRaw : CLR_T15_stRaw)
#endif

#endif
