/*****************************************************************************
   time.h
   Generated By:
   Raptor 2022b_1.1.14772 (6969)
   Matlab (R2022b) 9.13

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Feb 22 21:12:12 2023
 *****************************************************************************/

#ifndef TIME_H
#define TIME_H

uint32_T ticks(void);
uint32_T ticks_i(void);
uint32_T ticks_us(void);
uint32_T ticks_us_i(void);

#endif
