/********************************************************************************
FILE:         ats_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _ATS_MSG_H
#define _ATS_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __ATS_CTCURRUNTST_EXT__
#define __ATS_CTCURRUNTST_EXT__
extern uint8                    ATS_ctCurRunTst;
#endif /* __ATS_CTCURRUNTST_EXT__ */

#ifndef __ATS_STMON_EXT__
#define __ATS_STMON_EXT__
extern uint8                    ATS_stMon;
#endif /* __ATS_STMON_EXT__ */

#ifndef __ATS_STMONTIMELIMIT_EXT__
#define __ATS_STMONTIMELIMIT_EXT__
extern uint8                    ATS_stMonTimeLimit;
#endif /* __ATS_STMONTIMELIMIT_EXT__ */

#ifndef __EPM_NENGLRES_EXT__
#define __EPM_NENGLRES_EXT__
extern uint8                    Epm_nEngLRes;
#endif /* __EPM_NENGLRES_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_ATS_ctCurRunTst 
#define SET_ATS_ctCurRunTst (ATS_ctCurRunTst=TRUE)
#endif
#ifndef CLR_ATS_ctCurRunTst 
#define CLR_ATS_ctCurRunTst (ATS_ctCurRunTst=FALSE)
#endif
#ifndef GET_ATS_ctCurRunTst 
#define GET_ATS_ctCurRunTst (ATS_ctCurRunTst)
#endif
#ifndef PUT_ATS_ctCurRunTst 
#define PUT_ATS_ctCurRunTst(val) ((val) ? SET_ATS_ctCurRunTst : CLR_ATS_ctCurRunTst)
#endif


#ifndef SET_ATS_stMon 
#define SET_ATS_stMon (ATS_stMon=TRUE)
#endif
#ifndef CLR_ATS_stMon 
#define CLR_ATS_stMon (ATS_stMon=FALSE)
#endif
#ifndef GET_ATS_stMon 
#define GET_ATS_stMon (ATS_stMon)
#endif
#ifndef PUT_ATS_stMon 
#define PUT_ATS_stMon(val) ((val) ? SET_ATS_stMon : CLR_ATS_stMon)
#endif


#ifndef SET_ATS_stMonTimeLimit 
#define SET_ATS_stMonTimeLimit (ATS_stMonTimeLimit=TRUE)
#endif
#ifndef CLR_ATS_stMonTimeLimit 
#define CLR_ATS_stMonTimeLimit (ATS_stMonTimeLimit=FALSE)
#endif
#ifndef GET_ATS_stMonTimeLimit 
#define GET_ATS_stMonTimeLimit (ATS_stMonTimeLimit)
#endif
#ifndef PUT_ATS_stMonTimeLimit 
#define PUT_ATS_stMonTimeLimit(val) ((val) ? SET_ATS_stMonTimeLimit : CLR_ATS_stMonTimeLimit)
#endif


#ifndef SET_Epm_nEngLRes 
#define SET_Epm_nEngLRes (Epm_nEngLRes=TRUE)
#endif
#ifndef CLR_Epm_nEngLRes 
#define CLR_Epm_nEngLRes (Epm_nEngLRes=FALSE)
#endif
#ifndef GET_Epm_nEngLRes 
#define GET_Epm_nEngLRes (Epm_nEngLRes)
#endif
#ifndef PUT_Epm_nEngLRes 
#define PUT_Epm_nEngLRes(val) ((val) ? SET_Epm_nEngLRes : CLR_Epm_nEngLRes)
#endif

#endif
