
/*<RBHead>
 *************************************************************************
 *                                                                       *
 *                      ROBERT BOSCH GMBH                                *
 *                          STUTTGART                                    *
 *                                                                       *
 *          Alle Rechte vorbehalten - All rights reserved                *
 *                                                                       *
 *************************************************************************  
 *
 *    __   __   ___  ___
 *   /_ / /  / /__  /    /__/
 *  /__/ /__/ __ / /__  /  /
 *
 *
 *************************************************************************
 *    Administrative Information (automatically filled in by eASEE)      *
 *************************************************************************
 *
 * $Filename__:uego_censrv.h$
 *
 * $Author____:PEDOEBLE$
 *
 * $Function__:providing UEGO internal interface for several UEGO functions$
 *
 *************************************************************************
 * $Domain____:SDOM$
 * $User______:POU2ABT$
 * $Date______:28.12.2015$
 * $Class_____:SWHDR$
 * $Name______:uego_censrv$
 * $Variant___:5.0.0$
 * $Revision__:0$
 * $Type______:H$
 * $State_____:AVAILABLE$
 * $Generated_:$
 *************************************************************************
 *
 * $UniqueName:$
 * $Component_:$
 *
 * $FDEF______:$
 *
 *************************************************************************
 * List Of Changes
 *
 * $History
 * 
 * 5.0.0; 0     28.12.2015 POU2ABT
 *   Modification for the feature to collect all the SyC_WaitPostDrv in the FC :
 *    SYC_PROPOSTDRV for Ferrari project.
 * 
 * 1.8.0; 4     17.04.2013 RSU1COB
 *   doku update and COENG_FINISH made as  a macro
 * 
 * 1.8.0; 3     08.04.2013 HAB1COB
 *   Added ExhMod_tWallSxSy
 * 
 * 1.8.0; 2     04.04.2013 RSU1COB
 *   The memory of UEGO_flgCipeAdpnEomTOFFV_I and UEGO_flgRpcEomTOFFV_I are 
 *   changed from MediumNoReini to MediumReIni
 * 
 * 1.8.0; 1     03.04.2013 RSU1COB
 *   Changes after review
 * 
 * 1.8.0; 0     28.03.2013 RSU1COB
 *   Changes for RQONE00115880
 * 
 * 1.5.0; 1     14.06.2012 CABRAUN
 *   Abfangen Division 0:0 mit AFS_mAirPerCyl
 * 
 * 1.5.0; 0     12.06.2012 CABRAUN
 *   lambda model for LSU 5.1
 * 
 * 1.4.0; 0     19.09.2011 CIA2ST
 *   remove chip detection,  combi SW not longer required
 *   activation of DifChkSnsr by tester interface
 *   allocation dew point release
 * 
 * 1.3.0; 0     04.05.2011 LZE2ST
 *   stop detection
 * 
 * $
 *
 ***************************************************************************************************
 *
 *   T H I S   I S   A   G E N E R A T E D   F I L E   F R O M      A  S  C  E  T
 *
 ***************************************************************************************************
 * Autor:              sun6cob
 * Date:               12/28/2015  11:40:05
 * Modulname:          UEGO_CenSrv
 * Filename:           UEGO_CenSrv.h
 * Filetype:           header
 * Implementation:     Impl
 *
 * $Generated by ASCET-SD: V6.1.4 RB-DGS 2.4
 * Expander:           Generic  CID: 610
 * Codegenerator:      ASCET-SE-RBPT V6.1.4.28.20
 * Target:             Generic:DGS-MEDC17 [V6.1.4.28.20]
 * CgenOptions:
 *             Allow Double bit Size for Division Numerators=true
 *             Generate Round Operation on float to integer Assignment=false
 *             Generate Access Methods for dT (Alternative: use OS dT directly)=false
 *             Temp Vars always 32 bit (integer)=false
 *             Generate Limiters (may be changed locally)=true
 *             Use SHIFT Operation on Signed Values instead of DIV Operation=true
 *             Optimize Direct Access Methods (Multiple Levels)=true
 *             Protected Vector Indices=false
 *             Optimize Direct Access Methods (One Level)=true
 *             Add Comment with Generation Information for each Component=false
 *             Add Comment with Implementation Information for each Assignment Statement=true
 *             Add Comment with Specification Source for each Statement=true
 *             Add Implementation Definitions=true
 *             Add parenthesis for readability=true
 *             Allow Limit Service for Assignment Limitation=true
 *             Arithmetic Service Set=rb-services
 *             Auto-inline private methods (Smaller code-size - may be changed locally)=false
 *             Casting=Legacy
 *             Code Generator=Object Based Controller Implementation
 *             Compiler=DGS-MEDC17 (dummy compiler)
 *             Division truncation direction=Zero (T-division)
 *             Force Parenthesis for Binary Logical Operators=true
 *             Generate Access Macros for=()
 *             Generate Data Structures=YESALL
 *             Generate Define Directives for Enum Values=true
 *             Generate Map File=false
 *             Generate OS Configuration=false
 *             Generate well-formed switch=true
 *             Hierarchical Code-Generation (may be changed locally)=false
 *             Initialise history variable with zero=true
 *             Inline directive=INLINE_FUNCTION
 *             Integer Bit Size=32
 *             Maximum bit Length (float)=32
 *             Maximum bit Length (int)=32
 *             Operating System=GENERIC_OSEK
 *             Optimize Static Actions (Restricted Modelling)=false
 *             Outline Generated Methods (may be changed locally)=false
 *             Prefix for Component Names=
 *             Private directive=static
 *             Protected against division by zero=false
 *             Protected Division against Signed Overflow=false
 *             Public directive=
 *             Result on Division by Zero=numerator
 *             Target=Generic:DGS-MEDC17
 *             Use Customized Data Type Names=false
 *             Use power of 2 approximations of literals=false
 *             Use SHIFT Operation on Signed Values instead of MUL Operation=true
 *
 ***************************************************************************************************
</RBHead>*/
#ifndef _UEGO_CENSRV_H
#define _UEGO_CENSRV_H

/* public method prototypes for UEGO_SRVTESTCLASS_IMPL */
#ifdef _UEGO_SRVTESTCLASS_IMPL_

#define START_SECTION_Fast_Codemem
#include "pragma.h"

uint8 UEGO_SRVTESTCLASS_IMPL_UEGO_GetStatus(void);

#define STOP_SECTION_Fast_Codemem
#include "pragma.h"

#define START_SECTION_Fast_Codemem
#include "pragma.h"

uint8 UEGO_SRVTESTCLASS_IMPL_UEGO_GetStopPerm(void);

#define STOP_SECTION_Fast_Codemem
#include "pragma.h"

#define START_SECTION_Fast_Codemem
#include "pragma.h"

uint8 UEGO_SRVTESTCLASS_IMPL_UEGO_GetStrtPerm(uint32 arg_numPar, uint32 arg_adPar);

#define STOP_SECTION_Fast_Codemem
#include "pragma.h"

#endif /* _UEGO_SRVTESTCLASS_IMPL_ */

/* _UEGO_CENSRV_H */
#endif
