/*****************************************************************************
   AppMonitor1.c
   Generated By:
   Raptor 2023a_2.0.15039 (7682)
   Matlab (R2022b) 9.13

   Copyright (c) 2023 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Tue Oct 17 21:06:40 2023
 *****************************************************************************/

#include "EVSR24.h"
#include "EVSR24_private.h"

typedef struct {
  uint32_T *time;
  uint32_T threshold;
  uint32_T factor;
  uint32_T raster_mask;
} S_AppMonTrig;

const S_AppMonTrig triggers[] = {
  { Foreground_Pct_Usage_Ptr(), 7000, 6000, 1 },

  { Background_Pct_Usage_Ptr(), 35000, 1200, 32 },

  { Second_Pct_Usage_Ptr(), 700000, 60, 1024 },
};

void appmonitor_Pause(uint16_T cause)
{

#ifndef __PC__

  AppMonitorState_Data() = APPMON_PAUSE;
  AppMonitorLastError_Data() = cause;
  swsh_Write_InjCDrv_InjCutOff(0xFF);
  swsh_Write_IgnCDrv_IgnCutOff(1);
  swsh_Write_HBridgeShutOff(0,1);
  swsh_Write_HBridgeShutOff(1,1);
  swsh_Write_HBridgeShutOff(2,1);

#endif                                 /* __PC__ */

}

uint16_T rasterExec = 0;
void appmonitor_Thread()
{

#ifndef __PC__

  uint8_T i;
  uint32_T totalTaskTime = 0;
  if (AppMonitorExecutionCount_Data() > 1) {
    for (i = 0; i < 3; i++) {
      S_AppMonTrig tmp_trig = triggers[i];
      if ((*(tmp_trig.time) > tmp_trig.threshold) && (AppMonitorState_Data() ==
           APPMON_RUN)) {
        AppMonitorLastError_Data() = (uint16_T)(65535 - i);
        if (i == 0) {
          AppMonitorNumForegroundOverruns_Data() =
            (AppMonitorNumForegroundOverruns_Data() < 4294967295U) ?
            AppMonitorNumForegroundOverruns_Data()+1 : 4294967295U;
        }

        if (AppMonitorForegroundOverrunAction_Data() ==
            FOREGROUND_OVERRUN_ACTION_STOP) {
          appmonitor_Pause((uint16_T)(65535 - i));
        }
      }

      if ((rasterExec & triggers[i].raster_mask) > 0U) {
        totalTaskTime += *(triggers[i].time);
      }
    }
  } else {
    Foreground_LongestRun_Data() = 0;
    Background_LongestRun_Data() = 0;
    Second_LongestRun_Data() = 0;
  }

  if (AppMonitorState_Data() != APPMON_PAUSE) {
    if (totalTaskTime == 0) {
      AppMonitorPctIdleTime_Data() = 10000;
      AppMonitorPctOverrun_Data() = 10000;
    } else if (totalTaskTime > 10000) {
      AppMonitorPctOverrun_Data() = totalTaskTime - 10000;
      AppMonitorPctIdleTime_Data() = 0;
    } else {
      AppMonitorPctIdleTime_Data() = 10000 - totalTaskTime;
      AppMonitorPctOverrun_Data() = 10000;
    }
  }

  if ((AppMonitorPctIdleTime_Data() < 1000U) && (AppMonitorState_Data() ==
       APPMON_RUN)) {
    appmonitor_Pause(2);
  }

  if (AppMonitorPctOverrun_Data() > 12000U) {
    if (AppMonitorState_Data() == APPMON_RUN &&
        AppMonitorForegroundOverrunAction_Data() ==
        FOREGROUND_OVERRUN_ACTION_STOP) {
      appmonitor_Pause(3);
    }
  }

  if (AppMonitorState_Data() == APPMON_REBOOT) {
    while (1) ;
  } else if ((AppMonitorState_Data() == APPMON_STEP) && (Timer_ooqlV_Steps_Data()
              == 0) && (Timer_BGND_G6Wyo_Steps_Data() == 0) &&
             (EVSR24_step_Steps_Data() == 0) ) {
    AppMonitorState_Data() = APPMON_PAUSE;
  }

  rasterExec = 0;
  AppMonitorExecutionCount_Data() = (AppMonitorExecutionCount_Data() <
    4294967295U) ? AppMonitorExecutionCount_Data()+1 : 4294967295U;

#endif                                 /* __PC__ */

}

void AppMon_StartCheckReset( void )
{
  boolean_T rtbOp1;
  boolean_T rtbOp2;
  rtbOp1 = (Reset_Env.xId == Reset_xHistBuf[0]);
  rtbOp2 = ((Reset_Env.xId != SWRESET_CBPROG_E) && (Reset_Env.xId !=
             SWRESET_POWERON_SIMU_E) && (Reset_Env.xId !=
             RESET_SWRESET_MOCRAM_REPEXOK));
  if (rtbOp1 && rtbOp2) {
    AppMonitorState_Data() = APPMON_PAUSE;
    AppMonitorLastError_Data() = 1;
  }
}
