/*****************************************************************************
   can_general.c
   Generated By:
   Raptor 2023a_2.0.15039 (7682)
   Matlab (R2022b) 9.13

   Copyright (c) 2023 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Tue Oct 17 21:06:40 2023
 *****************************************************************************/

#include "core_env.h"
#include "sws_can.h"
#include "can_general.h"

/* CAN Message Info Table */
volatile can_msg_id_init_t canMsgInfo[] = {
  { 0x01, CAN_TX, CAN_EXTENDED_ID_FORMAT, 0x1fffffff, CAN_BUS_A },

  { 0x02, CAN_TX, CAN_STANDARD_ID_FORMAT, 0x7ff, CAN_BUS_A },

  { 0x03, CAN_TX, CAN_EXTENDED_ID_FORMAT, 0x1fffffff, CAN_BUS_A },

  { 0x04, CAN_TX, CAN_STANDARD_ID_FORMAT, 0x7ff, CAN_BUS_A },

  { 0x05, CAN_TX, CAN_EXTENDED_ID_FORMAT, 0x1fffffff, CAN_BUS_B },

  { 0x06, CAN_TX, CAN_STANDARD_ID_FORMAT, 0x7ff, CAN_BUS_B },

  { 0x07, CAN_TX, CAN_EXTENDED_ID_FORMAT, 0x1fffffff, CAN_BUS_B },

  { 0x08, CAN_TX, CAN_STANDARD_ID_FORMAT, 0x7ff, CAN_BUS_B },

  { 0x09, CAN_TX, CAN_EXTENDED_ID_FORMAT, 0x1fffffff, CAN_BUS_C },

  { 0x10, CAN_TX, CAN_STANDARD_ID_FORMAT, 0x7ff, CAN_BUS_C },

  { 0x11, CAN_TX, CAN_EXTENDED_ID_FORMAT, 0x1fffffff, CAN_BUS_C },

  { 0x12, CAN_TX, CAN_STANDARD_ID_FORMAT, 0x7ff, CAN_BUS_C },

  /* RX Messages - CAN1 Standard ID Rx Blocks */
  { 0x174, CAN_RX, CAN_STANDARD_ID_FORMAT, 0x7FF, CAN_BUS_A },

  { 0x178, CAN_RX, CAN_STANDARD_ID_FORMAT, 0x7FF, CAN_BUS_A },

  { 0x17C, CAN_RX, CAN_STANDARD_ID_FORMAT, 0x7FF, CAN_BUS_A },

  { 0xD8, CAN_RX, CAN_STANDARD_ID_FORMAT, 0x7FF, CAN_BUS_A },

  { 0xAA, CAN_RX, CAN_STANDARD_ID_FORMAT, 0x7FF, CAN_BUS_A },

  { 0x100, CAN_RX, CAN_STANDARD_ID_FORMAT, 0x1FFFFFFF, CAN_BUS_A },

  { 0x200, CAN_RX, CAN_STANDARD_ID_FORMAT, 0x1FFFFFFF, CAN_BUS_A },
};

volatile uint8 canMsgBuffInUse[] = {
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
};

volatile can_msg_init_t can_init[1] = {
  { 19, (can_msg_id_init_t *)&canMsgInfo }
};

void CAN_NewEagle_Receive_MSG_STD_Node3(uint16 msgHandle_u16,uint32 *msgId_pu32,
  uint8 *msgDlc_pu8, uint8 *msgData_pu8)
{
  UNUSED(msgHandle_u16);
  UNUSED(msgId_pu32);
  UNUSED(msgDlc_pu8);
  UNUSED(msgData_pu8);
}

void CAN_NewEagle_Receive_MSG_EXD_Node3(uint16 msgHandle_u16,uint32 *msgId_pu32,
  uint8 *msgDlc_pu8, uint8 *msgData_pu8)
{
  UNUSED(msgHandle_u16);
  UNUSED(msgId_pu32);
  UNUSED(msgDlc_pu8);
  UNUSED(msgData_pu8);
}

void CANTx_Buffer9(uint16 msgHandle_u16,uint32 *msgId_pu32,uint8 *msgDlc_pu8,
                   uint8 *msgData_pu8)
{
  UNUSED(msgHandle_u16);
  UNUSED(msgId_pu32);
  UNUSED(msgDlc_pu8);
  UNUSED(msgData_pu8);
}

void CANTx_Buffer10(uint16 msgHandle_u16,uint32 *msgId_pu32,uint8 *msgDlc_pu8,
                    uint8 *msgData_pu8)
{
  UNUSED(msgHandle_u16);
  UNUSED(msgId_pu32);
  UNUSED(msgDlc_pu8);
  UNUSED(msgData_pu8);
}

void CANTx_Buffer11(uint16 msgHandle_u16,uint32 *msgId_pu32,uint8 *msgDlc_pu8,
                    uint8 *msgData_pu8)
{
  UNUSED(msgHandle_u16);
  UNUSED(msgId_pu32);
  UNUSED(msgDlc_pu8);
  UNUSED(msgData_pu8);
}

void CANTx_Buffer12(uint16 msgHandle_u16,uint32 *msgId_pu32,uint8 *msgDlc_pu8,
                    uint8 *msgData_pu8)
{
  UNUSED(msgHandle_u16);
  UNUSED(msgId_pu32);
  UNUSED(msgDlc_pu8);
  UNUSED(msgData_pu8);
}
