/*****************************************************************************
   data.c
   Generated By:
   Raptor 2023a_2.0.15039 (7682)
   Matlab (R2022b) 9.13

   Copyright (c) 2023 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Tue Oct 17 21:06:40 2023
 *****************************************************************************/

#include "raptor_types.h"
#include "data.h"
#include "string.h"                    /* TODO Reseach availabilty */
#include "EVSR24.h"
#include "EVSR24_private.h"

/* SS_DOUBLE  =  0,    / real32_T    /
   SS_SINGLE  =  1,    / real32_T  /
   SS_INT8    =  2,    / int8_T    /
   SS_UINT8   =  3,    / uint8_T   /
   SS_INT16   =  4,    / int16_T   /
   SS_UINT16  =  5,    / uint16_T  /
   SS_INT32   =  6,    / int32_T   /
   SS_UINT32  =  7,    / uint32_T  /
   SS_BOOLEAN =  8     / boolean_T */
#define START_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

RAMVariables_T RAMVariables ;

#define STOP_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"
#define START_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

const RAMVariables_T RAMVariables_DEFAULT = {
  55,                                  /*INIT_RAM_Variables*/
  0,                                   /* FgndTasksStopped */
  0,                                   /* KeySw_Bgnd */
  0,                                   /* KeepModuleOn */
  0,                              /* CTRL_cellSegment7TempToLVDuty_LookupX_IN */
  0,                                /* CTRL_cellSegment7TempToLVDuty_Y_IN_IDX */
  0,                              /* CTRL_cellSegment7TempToHVDuty_LookupX_IN */
  0,                                /* CTRL_cellSegment7TempToHVDuty_Y_IN_IDX */
  0,                              /* CTRL_cellSegment8TempToLVDuty_LookupX_IN */
  0,                                /* CTRL_cellSegment8TempToLVDuty_Y_IN_IDX */
  0,                              /* CTRL_cellSegment8TempToHVDuty_LookupX_IN */
  0,                                /* CTRL_cellSegment8TempToHVDuty_Y_IN_IDX */
  0,                              /* CTRL_cellSegment6TempToLVDuty_LookupX_IN */
  0,                                /* CTRL_cellSegment6TempToLVDuty_Y_IN_IDX */
  0,                              /* CTRL_cellSegment6TempToHVDuty_LookupX_IN */
  0,                                /* CTRL_cellSegment6TempToHVDuty_Y_IN_IDX */
  0,                              /* CTRL_cellSegment4TempToLVDuty_LookupX_IN */
  0,                                /* CTRL_cellSegment4TempToLVDuty_Y_IN_IDX */
  0,                              /* CTRL_cellSegment4TempToHVDuty_LookupX_IN */
  0,                                /* CTRL_cellSegment4TempToHVDuty_Y_IN_IDX */
  0,                              /* CTRL_cellSegment2TempToLVDuty_LookupX_IN */
  0,                                /* CTRL_cellSegment2TempToLVDuty_Y_IN_IDX */
  0,                              /* CTRL_cellSegment2TempToHVDuty_LookupX_IN */
  0,                                /* CTRL_cellSegment2TempToHVDuty_Y_IN_IDX */
  0,                              /* CTRL_cellSegment5TempToLVDuty_LookupX_IN */
  0,                                /* CTRL_cellSegment5TempToLVDuty_Y_IN_IDX */
  0,                              /* CTRL_cellSegment5TempToHVDuty_LookupX_IN */
  0,                                /* CTRL_cellSegment5TempToHVDuty_Y_IN_IDX */
  0,                              /* CTRL_cellSegment3TempToLVDuty_LookupX_IN */
  0,                                /* CTRL_cellSegment3TempToLVDuty_Y_IN_IDX */
  0,                              /* CTRL_cellSegment3TempToHVDuty_LookupX_IN */
  0,                                /* CTRL_cellSegment3TempToHVDuty_Y_IN_IDX */
  0,                              /* CTRL_cellSegment1TempToLVDuty_LookupX_IN */
  0,                                /* CTRL_cellSegment1TempToLVDuty_Y_IN_IDX */
  0,                              /* CTRL_cellSegment1TempToHVDuty_LookupX_IN */
  0,                                /* CTRL_cellSegment1TempToHVDuty_Y_IN_IDX */
  0,                                   /* CTRL_throttleToNm_LookupX_IN */
  0,                                   /* CTRL_throttleToNm_Y_IN_IDX */
  0.0F,                                /* CTRL_torqueCommand_Nm */
  0,                                   /* CTRL_yawRateToAimSlip_LookupY_IN */
  0,                                   /* CTRL_yawRateToAimSlip_LookupX_IN */
  0,                                   /* CTRL_yawRateToAimSlip_X_IN_IDX */
  0,                                   /* CTRL_yawRateToAimSlip_Y_IN_IDX */
  0,                                   /* CTRL_slipAim */
  0,                                   /* CTRL_slipAimError */
  0,                                   /* CTRL_tcPowerReduction_pct */
  0,                        /* CTRL_coolantTempMotorInToLeftHVDuty_LookupX_IN */
  0,                          /* CTRL_coolantTempMotorInToLeftHVDuty_Y_IN_IDX */
  0,                     /* CTRL_coolantTempInverterInToLeftHVDuty_LookupX_IN */
  0,                       /* CTRL_coolantTempInverterInToLeftHVDuty_Y_IN_IDX */
  0,                    /* CTRL_coolantTempInverterOutToLeftHVDuty_LookupX_IN */
  0,                      /* CTRL_coolantTempInverterOutToLeftHVDuty_Y_IN_IDX */
  0,                        /* CTRL_coolantTempMotorInToLeftLVDuty_LookupX_IN */
  0,                        /* CTRL_coolantTempMotorInToLeftLVDuty_LookupY_IN */
  0,                          /* CTRL_coolantTempMotorInToLeftLVDuty_X_IN_IDX */
  0,                          /* CTRL_coolantTempMotorInToLeftLVDuty_Y_IN_IDX */
  0,                     /* CTRL_coolantTempInverterInToLeftLVDuty_LookupX_IN */
  0,                     /* CTRL_coolantTempInverterInToLeftLVDuty_LookupY_IN */
  0,                       /* CTRL_coolantTempInverterInToLeftLVDuty_X_IN_IDX */
  0,                       /* CTRL_coolantTempInverterInToLeftLVDuty_Y_IN_IDX */
  0,                    /* CTRL_coolantTempInverterOutToLeftLVDuty_LookupX_IN */
  0,                    /* CTRL_coolantTempInverterOutToLeftLVDuty_LookupY_IN */
  0,                      /* CTRL_coolantTempInverterOutToLeftLVDuty_X_IN_IDX */
  0,                      /* CTRL_coolantTempInverterOutToLeftLVDuty_Y_IN_IDX */
  0,                       /* CTRL_coolantTempMotorInToRightHVDuty_LookupX_IN */
  0,                         /* CTRL_coolantTempMotorInToRightHVDuty_Y_IN_IDX */
  0,                    /* CTRL_coolantTempInverterInToRightHVDuty_LookupX_IN */
  0,                      /* CTRL_coolantTempInverterInToRightHVDuty_Y_IN_IDX */
  0,                   /* CTRL_coolantTempInverterOutToRightHVDuty_LookupX_IN */
  0,                     /* CTRL_coolantTempInverterOutToRightHVDuty_Y_IN_IDX */
  0,                       /* CTRL_coolantTempMotorInToRightLVDuty_LookupX_IN */
  0,                       /* CTRL_coolantTempMotorInToRightLVDuty_LookupY_IN */
  0,                         /* CTRL_coolantTempMotorInToRightLVDuty_X_IN_IDX */
  0,                         /* CTRL_coolantTempMotorInToRightLVDuty_Y_IN_IDX */
  0,                    /* CTRL_coolantTempInverterInToRightLVDuty_LookupX_IN */
  0,                    /* CTRL_coolantTempInverterInToRightLVDuty_LookupY_IN */
  0,                      /* CTRL_coolantTempInverterInToRightLVDuty_X_IN_IDX */
  0,                      /* CTRL_coolantTempInverterInToRightLVDuty_Y_IN_IDX */
  0,                   /* CTRL_coolantTempInverterOutToRightLVDuty_LookupX_IN */
  0,                   /* CTRL_coolantTempInverterOutToRightLVDuty_LookupY_IN */
  0,                     /* CTRL_coolantTempInverterOutToRightLVDuty_X_IN_IDX */
  0,                     /* CTRL_coolantTempInverterOutToRightLVDuty_Y_IN_IDX */
  0,                            /* CTRL_coolantTempMotorInToWpDuty_LookupX_IN */
  0,                            /* CTRL_coolantTempMotorInToWpDuty_LookupY_IN */
  0,                              /* CTRL_coolantTempMotorInToWpDuty_X_IN_IDX */
  0,                              /* CTRL_coolantTempMotorInToWpDuty_Y_IN_IDX */
  0,                         /* CTRL_coolantTempInverterInToWpDuty_LookupX_IN */
  0,                         /* CTRL_coolantTempInverterInToWpDuty_LookupY_IN */
  0,                           /* CTRL_coolantTempInverterInToWpDuty_X_IN_IDX */
  0,                           /* CTRL_coolantTempInverterInToWpDuty_Y_IN_IDX */
  0,                        /* CTRL_coolantTempInverterOutToWpDuty_LookupX_IN */
  0,                        /* CTRL_coolantTempInverterOutToWpDuty_LookupY_IN */
  0,                          /* CTRL_coolantTempInverterOutToWpDuty_X_IN_IDX */
  0,                          /* CTRL_coolantTempInverterOutToWpDuty_Y_IN_IDX */
  0,                                   /* CTRL_driveSpeed_mph */
  0,                                   /* CTRL_groundSpeed_mph */
  0,                                   /* CTRL_slipRatio */
  0.0F,                                /* IN_coolantTempInverterIn_deg */
  0.0F,                                /* IN_coolantTempInverterOut_deg */
  0.0F,                                /* IN_coolantTempMotorIn_deg */
  0.0F,                                /* IN_throttleOverride1_pct */
  0.0F,                                /* IN_throttleOverride2_pct */
  0,                                   /* IN_tcSetTable_LookupX_IN */
  0,                                   /* IN_tcSetTable_Y_IN_IDX */
  0,                                /* IN_coolantTempVToDegMotorIn_LookupX_IN */
  0,                                  /* IN_coolantTempVToDegMotorIn_Y_IN_IDX */
  0,                             /* IN_coolantTempVToDegInverterIn_LookupX_IN */
  0,                               /* IN_coolantTempVToDegInverterIn_Y_IN_IDX */
  0,                            /* IN_coolantTempVToDegInverterOut_LookupX_IN */
  0,                              /* IN_coolantTempVToDegInverterOut_Y_IN_IDX */
  0,                                   /* IN_brakePressureF_psi */
  0,                                   /* IN_brakePressureR_psi */
  0,                                   /* IN_bspdBrakeError_v */
  0,                                   /* IN_bspdStatusError_v */
  0,                                   /* IN_rotorTempVToDegFL_LookupX_IN */
  0,                                   /* IN_rotorTempVToDegFL_Y_IN_IDX */
  0.0F,                                /* IN_rotorTempFL_deg */
  0,                                   /* IN_rotorTempVToDegRL_LookupX_IN */
  0,                                   /* IN_rotorTempVToDegRL_Y_IN_IDX */
  0.0F,                                /* IN_rotorTempRL_deg */
  0,                                   /* IN_rotorTempVToDegFR_LookupX_IN */
  0,                                   /* IN_rotorTempVToDegFR_Y_IN_IDX */
  0.0F,                                /* IN_rotorTempFR_deg */
  0,                                   /* IN_rotorTempVToDegRR_LookupX_IN */
  0,                                   /* IN_rotorTempVToDegRR_Y_IN_IDX */
  0.0F,                                /* IN_rotorTempRR_deg */
  0U,                                  /* IN_startSwitchSig_v */
  0,                                   /* IN_tcSetInput */
  0,                                   /* IN_throttlePos1_deg */
  0,                                   /* IN_throttlePos2_deg */
  0,                                   /* IN_tireTempVToDegFLI_LookupX_IN */
  0,                                   /* IN_tireTempVToDegFLI_Y_IN_IDX */
  0.0F,                                /* IN_tireTempFLI_deg */
  0,                                   /* IN_tireTempVToDegFLM_LookupX_IN */
  0,                                   /* IN_tireTempVToDegFLM_Y_IN_IDX */
  0.0F,                                /* IN_tireTempFLM_deg */
  0,                                   /* IN_tireTempVToDegFLO_LookupX_IN */
  0,                                   /* IN_tireTempVToDegFLO_Y_IN_IDX */
  0.0F,                                /* IN_tireTempFLO_deg */
  0,                                   /* IN_tireTempVToDegFRI_LookupX_IN */
  0,                                   /* IN_tireTempVToDegFRI_Y_IN_IDX */
  0.0F,                                /* IN_tireTempFRI_deg */
  0,                                   /* IN_tireTempVToDegFRM_LookupX_IN */
  0,                                   /* IN_tireTempVToDegFRM_Y_IN_IDX */
  0.0F,                                /* IN_tireTempFRM_deg */
  0,                                   /* IN_tireTempVToDegFRO_LookupX_IN */
  0,                                   /* IN_tireTempVToDegFRO_Y_IN_IDX */
  0.0F,                                /* IN_tireTempFRO_deg */
  0,                                   /* IN_tireTempVToDegRLI_LookupX_IN */
  0,                                   /* IN_tireTempVToDegRLI_Y_IN_IDX */
  0.0F,                                /* IN_tireTempRLI_deg */
  0,                                   /* IN_tireTempVToDegRLM_LookupX_IN */
  0,                                   /* IN_tireTempVToDegRLM_Y_IN_IDX */
  0.0F,                                /* IN_tireTempRLM_deg */
  0,                                   /* IN_tireTempVToDegRLO_LookupX_IN */
  0,                                   /* IN_tireTempVToDegRLO_Y_IN_IDX */
  0.0F,                                /* IN_tireTempRLO_deg */
  0,                                   /* IN_tireTempVToDegRRI_LookupX_IN */
  0,                                   /* IN_tireTempVToDegRRI_Y_IN_IDX */
  0.0F,                                /* IN_tireTempRRI_deg */
  0,                                   /* IN_tireTempVToDegRRM_LookupX_IN */
  0,                                   /* IN_tireTempVToDegRRM_Y_IN_IDX */
  0.0F,                                /* IN_tireTempRRM_deg */
  0,                                   /* IN_tireTempVToDegRRO_LookupX_IN */
  0,                                   /* IN_tireTempVToDegRRO_Y_IN_IDX */
  0.0F,                                /* IN_tireTempRRO_deg */
  0U,                                  /* IN_tsSwitchSig_v */
  0,                                   /* IN_wheelSpeedFL_rpm */
  0,                                   /* IN_wheelSpeedFL_mps */
  0,                                   /* IN_groundSpeedFL_mph */
  0,                                   /* IN_wheelSpeedFR_rpm */
  0,                                   /* IN_wheelSpeedFR_mps */
  0,                                   /* IN_groundSpeedFR_mph */
  0,                                   /* IN_wheelSpeedRL_rpm */
  0,                                   /* IN_wheelSpeedRL_mps */
  0,                                   /* IN_groundSpeedRL_mph */
  0,                                   /* IN_wheelSpeedRR_rpm */
  0,                                   /* IN_wheelSpeedRR_mps */
  0,                                   /* IN_groundSpeedRR_mph */
  0,                                   /* IN_coolPolarity_bool */
  0,                                   /* IN_Polarity_bool */
  0,                                   /* IN_markPolarity_bool */
  0,                                   /* IN_pageDownPolarity_bool */
  0,                                   /* IN_pageUpPolarity_bool */
  0,                                   /* IN_pttPolarity_bool */
  0,                                   /* IN_pwrDownPolarity_bool */
  0,                                   /* IN_pwrUpPolarity_bool */
  11UL,                                /* EcuAddr_RAM */
  0UL,                                 /* XCP_DAQ_TotalUsage */
  0UL,                                 /* XCP_LongestRun */
  0UL,                                 /* XCP_Error_Count */
  0UL,                                 /* XCP_DAQ00_10ms_Pct_Usage */
  0UL,                                 /* XCP_DAQ01_100ms_Pct_Usage */
  0U,                                  /* CAN1_CANTX_QueueOverrun */
  0U,                                  /* CAN1_CANTX_QueueCount */
  0U,                                  /* CAN1_CANTX_QueueMax */
  0U,                                  /* CAN1_CANRX_QueueOverrun */
  0U,                                  /* CAN1_CANRX_QueueCount */
  0U,                                  /* CAN1_CANRX_QueueMax */
  0U,                                  /* CAN2_CANTX_QueueOverrun */
  0U,                                  /* CAN2_CANTX_QueueCount */
  0U,                                  /* CAN2_CANTX_QueueMax */

  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, },               /* raptorFaultCounts_X */

  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, },               /* raptorFaultCounts_Y */
  0U,                                  /* AppMonitorLastError */
  10000UL,                             /* AppMonitorPctIdleTime */
  0UL,                                 /* AppMonitorExecutionCount */
  10000UL,                             /* AppMonitorPctOverrun */
  0UL,                                 /* Foreground_Pct_Usage */
  10UL,                                /* Foreground_Period */
  0UL,                                 /* Foreground_LongestRun */
  0UL,                                 /* Background_Pct_Usage */
  50UL,                                /* Background_Period */
  0UL,                                 /* Background_LongestRun */
  0UL,                                 /* Second_Pct_Usage */
  1000UL,                              /* Second_Period */
  0UL,                                 /* Second_LongestRun */
  0UL,                                 /* Startup_Usage */
  0UL,                                 /* Shutdown_Usage */
  0UL,                                 /* SafetyMonitor_Usage */
  0U,                                  /* EEPROM_State */
};

#define STOP_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

void initRAMVariables(RAMVariables_T* ramVariables)
{
  memcpy(ramVariables, &RAMVariables_DEFAULT, sizeof(RAMVariables_DEFAULT));
}

#define START_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

const CONSTVariables_T CONSTVariables = {
  { 69U, 86U, 83U, 82U, 50U, 52U, },   /* ModelName */
  4UL,                                 /* BuildNumber */

  { 40U, 82U, 50U, 48U, 50U, 50U, 98U, 41U, 32U, 57U, 46U, 49U, 51U, },/* MatlabVersion */

  { 50U, 48U, 50U, 51U, 97U, 95U, 50U, 46U, 48U, 46U, 49U, 53U, 48U, 51U, 57U,
    95U, 55U, 54U, 56U, 50U, },        /* RaptorVersion */

  { 69U, 86U, 83U, 82U, 50U, 52U, 95U, 48U, 48U, 52U, },/* SwIdTxt */

  { 69U, 86U, 83U, 82U, 50U, 52U, 95U, 48U, 48U, 52U, 95U, 48U, 48U, 48U, },/* CalIdTxt */

  { 65U, 95U, 95U, 75U, 118U, 54U, 75U, 102U, 100U, 69U, 101U, 52U, 119U, 52U,
    109U, 52U, 65U, 56U, 95U, 111U, 122U, },/* BuildUID */
  3,                                   /* IdTableRev */
  2954298118UL,                        /* HardwareType */

  { 49U, 55U, 45U, 79U, 99U, 116U, 45U, 50U, 48U, 50U, 51U, 32U, 50U, 49U, 58U,
    48U, 54U, 58U, 52U, 49U, },        /* DateStamp */
  1092577498UL,                        /* LiteModeKey */
};

#define STOP_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

void initCONSTVariables(const CONSTVariables_T* cv)
{

#ifdef UNUSED

  UNUSED(cv);

#endif

}

/* Total EEPROM Structure Size: 12102U Bytes */
#define START_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

const EEVariables_T EEVariables_DEFAULT = {
  0,                                  /* Write Count: Identifies active Copy 	*/
  2675540660U,                         /* EE_UniqID 	*/

  { 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U,
    0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U,
    0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U,
    0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U,
    0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, }, /* raptorFaultNonVolatileBits */
  0UL,                                 /* AppMonitorNumForegroundOverruns */
  (uint8_T)FOREGROUND_OVERRUN_ACTION_STOP,/* AppMonitorForegroundOverrunAction */
  0.2F,                                /* KeySwHiTimeThr */
  0.2F,                                /* KeySwLoTimeThr */
  100.0F,                              /* CTRL_upperThreshCellSeg7LV */
  100.0F,                              /* CTRL_upperThreshCellSeg7HV */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                                     /* CTRL_cellSegment7TempToLVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_cellSegment7TempToLVDuty */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                                     /* CTRL_cellSegment7TempToHVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_cellSegment7TempToHVDuty */
  100.0F,                              /* CTRL_upperThreshCellSeg8LV */
  100.0F,                              /* CTRL_upperThreshCellSeg8HV */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                                     /* CTRL_cellSegment8TempToLVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_cellSegment8TempToLVDuty */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                                     /* CTRL_cellSegment8TempToHVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_cellSegment8TempToHVDuty */
  100.0F,                              /* CTRL_upperThreshCellSeg6LV */
  100.0F,                              /* CTRL_upperThreshCellSeg6HV */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                                     /* CTRL_cellSegment6TempToLVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_cellSegment6TempToLVDuty */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                                     /* CTRL_cellSegment6TempToHVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_cellSegment6TempToHVDuty */
  100.0F,                              /* CTRL_upperThreshCellSeg4LV */
  100.0F,                              /* CTRL_upperThreshCellSeg4HV */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                                     /* CTRL_cellSegment4TempToLVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_cellSegment4TempToLVDuty */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                                     /* CTRL_cellSegment4TempToHVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_cellSegment4TempToHVDuty */
  100.0F,                              /* CTRL_upperThreshCellSeg2LV */
  100.0F,                              /* CTRL_upperThreshCellSeg2HV */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                                     /* CTRL_cellSegment2TempToLVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_cellSegment2TempToLVDuty */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                                     /* CTRL_cellSegment2TempToHVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_cellSegment2TempToHVDuty */
  100.0F,                              /* CTRL_upperThreshCellSeg5LV */
  100.0F,                              /* CTRL_upperThreshCellSeg5HV */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                                     /* CTRL_cellSegment5TempToLVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_cellSegment5TempToLVDuty */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                                     /* CTRL_cellSegment5TempToHVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_cellSegment5TempToHVDuty */
  100.0F,                              /* CTRL_upperThreshCellSeg3LV */
  100.0F,                              /* CTRL_upperThreshCellSeg3HV */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                                     /* CTRL_cellSegment3TempToLVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_cellSegment3TempToLVDuty */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                                     /* CTRL_cellSegment3TempToHVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_cellSegment3TempToHVDuty */
  100.0F,                              /* CTRL_upperThreshCellSeg1LV */
  100.0F,                              /* CTRL_upperThreshCellSeg1HV */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                                     /* CTRL_cellSegment1TempToLVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_cellSegment1TempToLVDuty */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                                     /* CTRL_cellSegment1TempToHVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_cellSegment1TempToHVDuty */
  1.0F,                                /* CTRL_upperThreshBrakeBias */
  1.0F,                                /* CTRL_dbzBrakeBias */
  1U,                                  /* CTRL_brakelight_bool */
  100.0F,                              /* CTRL_upperThreshBrakelight */
  0.0F,                                /* CTRL_bspcTorqueOverride_Nm */

  { 0.0F, 1.25F, 2.5F, 3.75F, 5.0F, 6.25F, 7.5F, 8.75F, 10.0F, 11.25F, 12.5F,
    13.75F, 15.0F, 16.25F, 17.5F, 18.75F, 20.0F, 21.25F, 22.5F, 23.75F, 25.0F,
    26.25F, 27.5F, 28.75F, 30.0F, 31.25F, 32.5F, 33.75F, 35.0F, 36.25F, 37.5F,
    38.75F, 40.0F, 41.25F, 42.5F, 43.75F, 45.0F, 46.25F, 47.5F, 48.75F, 50.0F,
    51.25F, 52.5F, 53.75F, 55.0F, 56.25F, 57.5F, 58.75F, 60.0F, 61.25F, 62.5F,
    63.75F, 65.0F, 66.25F, 67.5F, 68.75F, 70.0F, 71.25F, 72.5F, 73.75F, 75.0F,
    76.25F, 77.5F, 78.75F, 80.0F, 81.25F, 82.5F, 83.75F, 85.0F, 86.25F, 87.5F,
    88.75F, 90.0F, 91.25F, 92.5F, 93.75F, 95.0F, 96.25F, 97.5F, 98.75F, 100.0F,
  },                                   /* CTRL_throttleToNm_LookupX */

  { 0.0F, 1.5F, 3.0F, 4.5F, 6.0F, 7.5F, 9.0F, 10.5F, 12.0F, 13.5F, 15.0F, 16.5F,
    18.0F, 19.5F, 21.0F, 22.5F, 24.0F, 25.5F, 27.0F, 28.5F, 30.0F, 31.5F, 33.0F,
    34.5F, 36.0F, 37.5F, 39.0F, 40.5F, 42.0F, 43.5F, 45.0F, 46.5F, 48.0F, 49.5F,
    51.0F, 52.5F, 54.0F, 55.5F, 57.0F, 58.5F, 60.0F, 61.5F, 63.0F, 64.5F, 66.0F,
    67.5F, 69.0F, 70.5F, 72.0F, 73.5F, 75.0F, 76.5F, 78.0F, 79.5F, 81.0F, 82.5F,
    84.0F, 85.5F, 87.0F, 88.5F, 90.0F, 91.5F, 93.0F, 94.5F, 96.0F, 97.5F, 99.0F,
    100.5F, 102.0F, 103.5F, 105.0F, 106.5F, 108.0F, 109.5F, 111.0F, 112.5F,
    114.0F, 115.5F, 117.0F, 118.5F, 120.0F, },/* CTRL_throttleToNm */
  0.0F,                                /* CTRL_torqueCommandOverride_bool */
  0.0F,                                /* CTRL_tcOverride_bool */

  { 100.0F, 80.0F, 70.0F, 60.0F, 50.0F, 40.0F, 30.0F, 20.0F, 10.0F, 0.0F, },/* CTRL_yawRateToAimSlip_LookupY */

  { -80.0F, -70.0F, -60.0F, -50.0F, -40.0F, -20.0F, 0.0F, 20.0F, 40.0F, 50.0F,
    60.0F, 70.0F, 80.0F, },            /* CTRL_yawRateToAimSlip_LookupX */

  { { 5.0F, 7.0F, 7.5F, 8.0F, 8.5F, 9.0F, 9.0F, 9.0F, 9.0F, 9.0F, 5.5F, 7.5F,
      8.0F, }, { 8.5F, 9.0F, 9.5F, 9.5F, 9.5F, 9.5F, 9.5F, 6.0F, 8.0F, 8.5F,
      9.0F, 9.5F, 10.0F, }, { 10.0F, 10.0F, 10.0F, 10.0F, 6.5F, 8.5F, 9.0F, 9.5F,
      10.0F, 10.5F, 10.5F, 10.5F, 10.5F, }, { 10.5F, 7.0F, 9.0F, 9.5F, 10.0F,
      10.5F, 11.0F, 11.0F, 11.0F, 11.0F, 11.0F, 7.5F, 9.5F, }, { 10.0F, 10.5F,
      11.0F, 11.5F, 11.5F, 11.5F, 11.5F, 11.5F, 8.0F, 10.0F, 10.5F, 11.0F, 11.5F,
    }, { 12.0F, 12.0F, 12.0F, 12.0F, 12.0F, 7.5F, 9.5F, 10.0F, 10.5F, 11.0F,
      11.5F, 11.5F, 11.5F, }, { 11.5F, 11.5F, 7.0F, 9.0F, 9.5F, 10.0F, 10.5F,
      11.0F, 11.0F, 11.0F, 11.0F, 11.0F, 6.5F, }, { 8.5F, 9.0F, 9.5F, 10.0F,
      10.5F, 10.5F, 10.5F, 10.5F, 10.5F, 6.0F, 8.0F, 8.5F, 9.0F, }, { 9.5F,
      10.0F, 10.0F, 10.0F, 10.0F, 10.0F, 5.5F, 7.5F, 8.0F, 8.5F, 9.0F, 9.5F,
      9.5F, }, { 9.5F, 9.5F, 9.5F, 5.0F, 7.0F, 7.5F, 8.0F, 8.5F, 9.0F, 9.0F,
      9.0F, 9.0F, 9.0F, }, },          /* CTRL_yawRateToAimSlip */
  20.0F,                               /* CTRL_upperThreshPIDIn */
  100.0F,                              /* CTRL_upperThreshPwrReduction */
  0.17F,                               /* IN_slipThreshold */
  100.0F,                          /* CTRL_upperThreshCoolantInverterInLVLeft */
  100.0F,                             /* CTRL_upperThreshCoolantMotorInLVLeft */
  100.0F,                         /* CTRL_upperThreshCoolantInverterOutLVLeft */
  100.0F,                          /* CTRL_upperThreshCoolantInverterInHVLeft */
  100.0F,                             /* CTRL_upperThreshCoolantMotorInHVLeft */
  100.0F,                         /* CTRL_upperThreshCoolantInverterOutHVLeft */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                               /* CTRL_coolantTempMotorInToLeftHVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },/* CTRL_coolantTempMotorInToLeftHVDuty */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                            /* CTRL_coolantTempInverterInToLeftHVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },
                                    /* CTRL_coolantTempInverterInToLeftHVDuty */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                           /* CTRL_coolantTempInverterOutToLeftHVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },
                                   /* CTRL_coolantTempInverterOutToLeftHVDuty */

  { 0.0F, 8.0F, 9.0F, 10.0F, 10.5F, 11.0F, 11.9F, 12.0F, 13.0F, 13.7F, 13.8F,
    13.9F, 14.2F, 14.5F, },    /* CTRL_coolantTempMotorInToLeftLVDuty_LookupX */

  { 0.0F, 60.0F, 75.0F, 75.1F, 82.0F, 82.1F, 85.0F, 85.1F, 100.0F, 100.1F,
    150.0F, },                 /* CTRL_coolantTempMotorInToLeftLVDuty_LookupY */

  { { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
      0.0F, 0.0F, }, { 15.0F, 15.0F, 15.0F, 75.0F, 100.0F, 100.0F, 100.0F,
      100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 15.0F, }, { 75.0F, 100.0F, 100.0F,
      100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 15.0F, 75.0F, 100.0F,
      100.0F, }, { 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 25.0F, 75.0F,
      100.0F, 100.0F, 100.0F, 100.0F, 0.0F, }, { 0.0F, 0.0F, 15.0F, 15.0F, 25.0F,
      75.0F, 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, }, { 15.0F,
      25.0F, 75.0F, 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F,
      15.0F, 25.0F, 75.0F, }, { 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F,
      15.0F, 15.0F, 25.0F, 75.0F, 100.0F, 100.0F, 100.0F, }, { 100.0F, 0.0F,
      0.0F, 0.0F, 15.0F, 15.0F, 25.0F, 75.0F, 100.0F, 100.0F, 100.0F, 100.0F,
      0.0F, 0.0F, }, { 0.0F, 30.0F, 50.0F, 65.0F, 75.0F, 100.0F, 100.0F, 100.0F,
      100.0F, 0.0F, 0.0F, 0.0F, 30.0F, 50.0F, }, { 65.0F, 75.0F, 100.0F, 100.0F,
      100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 30.0F, 50.0F, 65.0F, 75.0F, 100.0F, }, {
      100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 25.0F, 30.0F, 50.0F, 65.0F, 75.0F,
      100.0F, 100.0F, 100.0F, 100.0F, }, },/* CTRL_coolantTempMotorInToLeftLVDuty */

  { 0.0F, 8.0F, 9.0F, 10.0F, 10.5F, 11.0F, 11.9F, 12.0F, 13.0F, 13.7F, 13.8F,
    13.9F, 14.2F, 14.5F, }, /* CTRL_coolantTempInverterInToLeftLVDuty_LookupX */

  { 0.0F, 60.0F, 75.0F, 75.1F, 82.0F, 82.1F, 85.0F, 85.1F, 100.0F, 100.1F,
    150.0F, },              /* CTRL_coolantTempInverterInToLeftLVDuty_LookupY */

  { { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
      0.0F, 0.0F, }, { 15.0F, 15.0F, 15.0F, 75.0F, 100.0F, 100.0F, 100.0F,
      100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 15.0F, }, { 75.0F, 100.0F, 100.0F,
      100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 15.0F, 75.0F, 100.0F,
      100.0F, }, { 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 25.0F, 75.0F,
      100.0F, 100.0F, 100.0F, 100.0F, 0.0F, }, { 0.0F, 0.0F, 15.0F, 15.0F, 25.0F,
      75.0F, 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, }, { 15.0F,
      25.0F, 75.0F, 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F,
      15.0F, 25.0F, 75.0F, }, { 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F,
      15.0F, 15.0F, 25.0F, 75.0F, 100.0F, 100.0F, 100.0F, }, { 100.0F, 0.0F,
      0.0F, 0.0F, 15.0F, 15.0F, 25.0F, 75.0F, 100.0F, 100.0F, 100.0F, 100.0F,
      0.0F, 0.0F, }, { 0.0F, 30.0F, 50.0F, 65.0F, 75.0F, 100.0F, 100.0F, 100.0F,
      100.0F, 0.0F, 0.0F, 0.0F, 30.0F, 50.0F, }, { 65.0F, 75.0F, 100.0F, 100.0F,
      100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 30.0F, 50.0F, 65.0F, 75.0F, 100.0F, }, {
      100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 25.0F, 30.0F, 50.0F, 65.0F, 75.0F,
      100.0F, 100.0F, 100.0F, 100.0F, }, },
                                    /* CTRL_coolantTempInverterInToLeftLVDuty */

  { 0.0F, 8.0F, 9.0F, 10.0F, 10.5F, 11.0F, 11.9F, 12.0F, 13.0F, 13.7F, 13.8F,
    13.9F, 14.2F, 14.5F, },/* CTRL_coolantTempInverterOutToLeftLVDuty_LookupX */

  { 0.0F, 60.0F, 75.0F, 75.1F, 82.0F, 82.1F, 85.0F, 85.1F, 100.0F, 100.1F,
    150.0F, },             /* CTRL_coolantTempInverterOutToLeftLVDuty_LookupY */

  { { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
      0.0F, 0.0F, }, { 15.0F, 15.0F, 15.0F, 75.0F, 100.0F, 100.0F, 100.0F,
      100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 15.0F, }, { 75.0F, 100.0F, 100.0F,
      100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 15.0F, 75.0F, 100.0F,
      100.0F, }, { 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 25.0F, 75.0F,
      100.0F, 100.0F, 100.0F, 100.0F, 0.0F, }, { 0.0F, 0.0F, 15.0F, 15.0F, 25.0F,
      75.0F, 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, }, { 15.0F,
      25.0F, 75.0F, 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F,
      15.0F, 25.0F, 75.0F, }, { 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F,
      15.0F, 15.0F, 25.0F, 75.0F, 100.0F, 100.0F, 100.0F, }, { 100.0F, 0.0F,
      0.0F, 0.0F, 15.0F, 15.0F, 25.0F, 75.0F, 100.0F, 100.0F, 100.0F, 100.0F,
      0.0F, 0.0F, }, { 0.0F, 30.0F, 50.0F, 65.0F, 75.0F, 100.0F, 100.0F, 100.0F,
      100.0F, 0.0F, 0.0F, 0.0F, 30.0F, 50.0F, }, { 65.0F, 75.0F, 100.0F, 100.0F,
      100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 30.0F, 50.0F, 65.0F, 75.0F, 100.0F, }, {
      100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 25.0F, 30.0F, 50.0F, 65.0F, 75.0F,
      100.0F, 100.0F, 100.0F, 100.0F, }, },
                                   /* CTRL_coolantTempInverterOutToLeftLVDuty */
  100.0F,                         /* CTRL_upperThreshCoolantInverterInLVRight */
  100.0F,                            /* CTRL_upperThreshCoolantMotorInLVRight */
  100.0F,                        /* CTRL_upperThreshCoolantInverterOutLVRight */
  100.0F,                         /* CTRL_upperThreshCoolantInverterInHVRight */
  100.0F,                            /* CTRL_upperThreshCoolantMotorInHVRight */
  100.0F,                        /* CTRL_upperThreshCoolantInverterOutHVRight */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                              /* CTRL_coolantTempMotorInToRightHVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },
                                      /* CTRL_coolantTempMotorInToRightHVDuty */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                           /* CTRL_coolantTempInverterInToRightHVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },
                                   /* CTRL_coolantTempInverterInToRightHVDuty */

  { 1.0F, 2.0F, 3.0F, 4.0F, 5.0F, 6.0F, 7.0F, 8.0F, 9.0F, 10.0F, 11.0F, },
                          /* CTRL_coolantTempInverterOutToRightHVDuty_LookupX */

  { 1.0F, 1.4142135623730951F, 1.7320508075688772F, 2.0F, 2.23606797749979F,
    2.4494897427831779F, 2.6457513110645907F, 2.8284271247461903F, 3.0F,
    3.1622776601683795F, 3.3166247903554F, },
                                  /* CTRL_coolantTempInverterOutToRightHVDuty */

  { 0.0F, 8.0F, 9.0F, 10.0F, 10.5F, 11.0F, 11.9F, 12.0F, 13.0F, 13.7F, 13.8F,
    13.9F, 14.2F, 14.5F, },   /* CTRL_coolantTempMotorInToRightLVDuty_LookupX */

  { 0.0F, 60.0F, 75.0F, 75.1F, 82.0F, 82.1F, 85.0F, 85.1F, 100.0F, 100.1F,
    150.0F, },                /* CTRL_coolantTempMotorInToRightLVDuty_LookupY */

  { { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
      0.0F, 0.0F, }, { 15.0F, 15.0F, 15.0F, 75.0F, 100.0F, 100.0F, 100.0F,
      100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 15.0F, }, { 75.0F, 100.0F, 100.0F,
      100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 15.0F, 75.0F, 100.0F,
      100.0F, }, { 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 25.0F, 75.0F,
      100.0F, 100.0F, 100.0F, 100.0F, 0.0F, }, { 0.0F, 0.0F, 15.0F, 15.0F, 25.0F,
      75.0F, 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, }, { 15.0F,
      25.0F, 75.0F, 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F,
      15.0F, 25.0F, 75.0F, }, { 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F,
      15.0F, 15.0F, 25.0F, 75.0F, 100.0F, 100.0F, 100.0F, }, { 100.0F, 0.0F,
      0.0F, 0.0F, 15.0F, 15.0F, 25.0F, 75.0F, 100.0F, 100.0F, 100.0F, 100.0F,
      0.0F, 0.0F, }, { 0.0F, 30.0F, 50.0F, 65.0F, 75.0F, 100.0F, 100.0F, 100.0F,
      100.0F, 0.0F, 0.0F, 0.0F, 30.0F, 50.0F, }, { 65.0F, 75.0F, 100.0F, 100.0F,
      100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 30.0F, 50.0F, 65.0F, 75.0F, 100.0F, }, {
      100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 25.0F, 30.0F, 50.0F, 65.0F, 75.0F,
      100.0F, 100.0F, 100.0F, 100.0F, }, },
                                      /* CTRL_coolantTempMotorInToRightLVDuty */

  { 0.0F, 8.0F, 9.0F, 10.0F, 10.5F, 11.0F, 11.9F, 12.0F, 13.0F, 13.7F, 13.8F,
    13.9F, 14.2F, 14.5F, },/* CTRL_coolantTempInverterInToRightLVDuty_LookupX */

  { 0.0F, 60.0F, 75.0F, 75.1F, 82.0F, 82.1F, 85.0F, 85.1F, 100.0F, 100.1F,
    150.0F, },             /* CTRL_coolantTempInverterInToRightLVDuty_LookupY */

  { { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
      0.0F, 0.0F, }, { 15.0F, 15.0F, 15.0F, 75.0F, 100.0F, 100.0F, 100.0F,
      100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 15.0F, }, { 75.0F, 100.0F, 100.0F,
      100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 15.0F, 75.0F, 100.0F,
      100.0F, }, { 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 25.0F, 75.0F,
      100.0F, 100.0F, 100.0F, 100.0F, 0.0F, }, { 0.0F, 0.0F, 15.0F, 15.0F, 25.0F,
      75.0F, 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, }, { 15.0F,
      25.0F, 75.0F, 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F,
      15.0F, 25.0F, 75.0F, }, { 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F,
      15.0F, 15.0F, 25.0F, 75.0F, 100.0F, 100.0F, 100.0F, }, { 100.0F, 0.0F,
      0.0F, 0.0F, 15.0F, 15.0F, 25.0F, 75.0F, 100.0F, 100.0F, 100.0F, 100.0F,
      0.0F, 0.0F, }, { 0.0F, 30.0F, 50.0F, 65.0F, 75.0F, 100.0F, 100.0F, 100.0F,
      100.0F, 0.0F, 0.0F, 0.0F, 30.0F, 50.0F, }, { 65.0F, 75.0F, 100.0F, 100.0F,
      100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 30.0F, 50.0F, 65.0F, 75.0F, 100.0F, }, {
      100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 25.0F, 30.0F, 50.0F, 65.0F, 75.0F,
      100.0F, 100.0F, 100.0F, 100.0F, }, },
                                   /* CTRL_coolantTempInverterInToRightLVDuty */

  { 0.0F, 8.0F, 9.0F, 10.0F, 10.5F, 11.0F, 11.9F, 12.0F, 13.0F, 13.7F, 13.8F,
    13.9F, 14.2F, 14.5F, },
                          /* CTRL_coolantTempInverterOutToRightLVDuty_LookupX */

  { 0.0F, 60.0F, 75.0F, 75.1F, 82.0F, 82.1F, 85.0F, 85.1F, 100.0F, 100.1F,
    150.0F, },            /* CTRL_coolantTempInverterOutToRightLVDuty_LookupY */

  { { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
      0.0F, 0.0F, }, { 15.0F, 15.0F, 15.0F, 75.0F, 100.0F, 100.0F, 100.0F,
      100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 15.0F, }, { 75.0F, 100.0F, 100.0F,
      100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 15.0F, 75.0F, 100.0F,
      100.0F, }, { 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, 15.0F, 25.0F, 75.0F,
      100.0F, 100.0F, 100.0F, 100.0F, 0.0F, }, { 0.0F, 0.0F, 15.0F, 15.0F, 25.0F,
      75.0F, 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F, }, { 15.0F,
      25.0F, 75.0F, 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 15.0F,
      15.0F, 25.0F, 75.0F, }, { 100.0F, 100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 0.0F,
      15.0F, 15.0F, 25.0F, 75.0F, 100.0F, 100.0F, 100.0F, }, { 100.0F, 0.0F,
      0.0F, 0.0F, 15.0F, 15.0F, 25.0F, 75.0F, 100.0F, 100.0F, 100.0F, 100.0F,
      0.0F, 0.0F, }, { 0.0F, 30.0F, 50.0F, 65.0F, 75.0F, 100.0F, 100.0F, 100.0F,
      100.0F, 0.0F, 0.0F, 0.0F, 30.0F, 50.0F, }, { 65.0F, 75.0F, 100.0F, 100.0F,
      100.0F, 100.0F, 0.0F, 0.0F, 0.0F, 30.0F, 50.0F, 65.0F, 75.0F, 100.0F, }, {
      100.0F, 100.0F, 100.0F, 0.0F, 0.0F, 25.0F, 30.0F, 50.0F, 65.0F, 75.0F,
      100.0F, 100.0F, 100.0F, 100.0F, }, },
                                  /* CTRL_coolantTempInverterOutToRightLVDuty */
  100.0F,                              /* CTRL_upperThreshCoolantInverterIn */
  100.0F,                              /* CTRL_upperThreshCoolantMotorIn */
  100.0F,                              /* CTRL_upperThreshCoolantInverterOut */

  { 0.0F, 0.0F, 10.0F, 20.0F, 500.0F, 510.0F, 5000.0F, 15000.0F, },
                                   /* CTRL_coolantTempMotorInToWpDuty_LookupX */

  { 10.0F, 20.0F, 40.0F, 50.0F, 60.0F, 69.9F, 70.0F, 84.5F, 84.6F, 100.0F,
    150.0F, },                     /* CTRL_coolantTempMotorInToWpDuty_LookupY */

  { { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, }, { 0.0F, 0.0F, 0.0F,
      0.0F, 0.0F, 0.0F, 0.0F, 0.0F, }, { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
      0.0F, 0.0F, }, { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 25.0F, 100.0F, }, {
      100.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, }, { 0.0F, 0.0F, 0.0F,
      0.0F, 0.0F, 0.0F, 0.0F, 0.0F, }, { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
      0.0F, 20.0F, }, { 20.0F, 35.0F, 35.0F, 35.0F, 35.0F, 40.0F, 50.0F, 60.0F,
    }, { 100.0F, 100.0F, 20.0F, 20.0F, 35.0F, 35.0F, 35.0F, 35.0F, }, { 40.0F,
      50.0F, 60.0F, 100.0F, 100.0F, 0.0F, 0.0F, 15.0F, }, { 15.0F, 25.0F, 75.0F,
      40.0F, 50.0F, 60.0F, 100.0F, 100.0F, }, },/* CTRL_coolantTempMotorInToWpDuty */

  { 0.0F, 0.0F, 10.0F, 20.0F, 500.0F, 510.0F, 5000.0F, 15000.0F, },
                                /* CTRL_coolantTempInverterInToWpDuty_LookupX */

  { 10.0F, 20.0F, 40.0F, 50.0F, 60.0F, 69.9F, 70.0F, 84.5F, 84.6F, 100.0F,
    150.0F, },                  /* CTRL_coolantTempInverterInToWpDuty_LookupY */

  { { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, }, { 0.0F, 0.0F, 0.0F,
      0.0F, 0.0F, 0.0F, 0.0F, 0.0F, }, { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
      0.0F, 0.0F, }, { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 25.0F, 100.0F, }, {
      100.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, }, { 0.0F, 0.0F, 0.0F,
      0.0F, 0.0F, 0.0F, 0.0F, 0.0F, }, { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
      0.0F, 20.0F, }, { 20.0F, 35.0F, 35.0F, 35.0F, 35.0F, 40.0F, 50.0F, 60.0F,
    }, { 100.0F, 100.0F, 20.0F, 20.0F, 35.0F, 35.0F, 35.0F, 35.0F, }, { 40.0F,
      50.0F, 60.0F, 100.0F, 100.0F, 0.0F, 0.0F, 15.0F, }, { 15.0F, 25.0F, 75.0F,
      40.0F, 50.0F, 60.0F, 100.0F, 100.0F, }, },/* CTRL_coolantTempInverterInToWpDuty */

  { 0.0F, 0.0F, 10.0F, 20.0F, 500.0F, 510.0F, 5000.0F, 15000.0F, },
                               /* CTRL_coolantTempInverterOutToWpDuty_LookupX */

  { 10.0F, 20.0F, 40.0F, 50.0F, 60.0F, 69.9F, 70.0F, 84.5F, 84.6F, 100.0F,
    150.0F, },                 /* CTRL_coolantTempInverterOutToWpDuty_LookupY */

  { { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, }, { 0.0F, 0.0F, 0.0F,
      0.0F, 0.0F, 0.0F, 0.0F, 0.0F, }, { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
      0.0F, 0.0F, }, { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 25.0F, 100.0F, }, {
      100.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, }, { 0.0F, 0.0F, 0.0F,
      0.0F, 0.0F, 0.0F, 0.0F, 0.0F, }, { 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
      0.0F, 20.0F, }, { 20.0F, 35.0F, 35.0F, 35.0F, 35.0F, 40.0F, 50.0F, 60.0F,
    }, { 100.0F, 100.0F, 20.0F, 20.0F, 35.0F, 35.0F, 35.0F, 35.0F, }, { 40.0F,
      50.0F, 60.0F, 100.0F, 100.0F, 0.0F, 0.0F, 15.0F, }, { 15.0F, 25.0F, 75.0F,
      40.0F, 50.0F, 60.0F, 100.0F, 100.0F, }, },/* CTRL_coolantTempInverterOutToWpDuty */
  1.0F,                                /* CTRL_slipRatioUpperThresh */
  1.0F,                                /* CTRL_slipConstant */
  0U,                                  /* IN_brakePosF_zero */
  0U,                                  /* IN_brakePosOverrideF_bool */
  0U,                                  /* IN_brakePosR_zero */
  0U,                                  /* IN_brakePosOverrideR_bool */
  0.0F,                                /* IN_throttlePos1_zero */
  0U,                                  /* IN_throttleOverride1_bool */
  0.0F,                                /* IN_throttlePos2_zero */
  0U,                                  /* IN_throttleOverride2_bool */
  0.02F,                               /* IN_brakePressureF_vToPsi */
  0.02F,                               /* IN_brakePressureR_vToPsi */
  4.5F,                                /* IN_brakeHighF_v */
  0.5F,                                /* IN_brakeLowF_v */
  0.05F,                               /* IN_brakePressureF_psiToPct */
  4.5F,                                /* IN_throttleHigh1_v */
  0.5F,                                /* IN_throttleLow1_v */
  72.0F,                               /* IN_throttle1_degPerV */
  0.0F,                                /* IN_throttleOffset1_deg */
  1.6666666666666667F,                 /* IN_throttlePos1_pctPerDeg */
  25.0F,                               /* CTRL_bspcThrottleThresh_pct */
  4.5F,                                /* IN_throttleHigh2_v */
  0.5F,                                /* IN_throttleLow2_v */
  72.0F,                               /* IN_throttle2_degPerV */
  0.0F,                                /* IN_throttleOffset2_deg */
  1.6666666666666667F,                 /* IN_throttlePos2_pctPerDeg */
  0.0F,                                /* CTRL_bspcBrakeThresh_pct */
  4.5F,                                /* IN_brakeHighR_v */
  0.5F,                                /* IN_brakeLowR_v */
  0.05F,                               /* IN_brakePressureR_psiToPct */

  { 390.0F, 790.0F, 1190.0F, 1580.0F, 1970.0F, 2360.0F, 3000.0F, 3400.0F,
    3790.0F, 4190.0F, 4590.0F, 4990.0F, },/* IN_tcSetTable_LookupX */

  { 11.0F, 10.0F, 9.0F, 8.0F, 7.0F, 6.0F, 5.0F, 4.0F, 3.0F, 2.0F, 1.0F, -1.0F, },/* IN_tcSetTable */

  { 0.2267F, 0.2793F, 0.3452F, 0.4303F, 0.5357F, 0.6741F, 0.842F, 1.0604F,
    1.3325F, 1.6592F, 2.0501F, 2.4737F, 2.936F, 3.3784F, 3.7981F, 4.1545F,
    4.4338F, 4.6399F, 4.7803F, 4.871F, },/* IN_coolantTempVToDegMotorIn_LookupX */

  { 150.0F, 140.0F, 130.0F, 120.0F, 110.0F, 100.0F, 90.0F, 80.0F, 70.0F, 60.0F,
    50.0F, 40.0F, 30.0F, 20.0F, 10.0F, 0.0F, -10.0F, -20.0F, -30.0F, -40.0F, },/* IN_coolantTempVToDegMotorIn */
  0U,                                  /* IN_coolantTempMotorIn_bool */

  { 0.2267F, 0.2793F, 0.3452F, 0.4303F, 0.5357F, 0.6741F, 0.842F, 1.0604F,
    1.3325F, 1.6592F, 2.0501F, 2.4737F, 2.936F, 3.3784F, 3.7981F, 4.1545F,
    4.4338F, 4.6399F, 4.7803F, 4.871F, },
                                    /* IN_coolantTempVToDegInverterIn_LookupX */

  { 150.0F, 140.0F, 130.0F, 120.0F, 110.0F, 100.0F, 90.0F, 80.0F, 70.0F, 60.0F,
    50.0F, 40.0F, 30.0F, 20.0F, 10.0F, 0.0F, -10.0F, -20.0F, -30.0F, -40.0F, },/* IN_coolantTempVToDegInverterIn */
  0U,                                  /* IN_coolantTempInverterIn_bool */

  { 0.2267F, 0.2793F, 0.3452F, 0.4303F, 0.5357F, 0.6741F, 0.842F, 1.0604F,
    1.3325F, 1.6592F, 2.0501F, 2.4737F, 2.936F, 3.3784F, 3.7981F, 4.1545F,
    4.4338F, 4.6399F, 4.7803F, 4.871F, },
                                   /* IN_coolantTempVToDegInverterOut_LookupX */

  { 150.0F, 140.0F, 130.0F, 120.0F, 110.0F, 100.0F, 90.0F, 80.0F, 70.0F, 60.0F,
    50.0F, 40.0F, 30.0F, 20.0F, 10.0F, 0.0F, -10.0F, -20.0F, -30.0F, -40.0F, },/* IN_coolantTempVToDegInverterOut */
  0U,                                  /* IN_coolantTempInverterOut_bool */
  25UL,                                /* IN_brakeVLowF_bool_X_Limit */
  50UL,                                /* IN_brakeVLowF_bool_Y_Limit */
  25UL,                                /* IN_brakeVHighF_bool_X_Limit */
  50UL,                                /* IN_brakeVHighF_bool_Y_Limit */
  25UL,                                /* IN_brakeErrorF_bool_X_Limit */
  50UL,                                /* IN_brakeErrorF_bool_Y_Limit */
  25UL,                                /* IN_brakeVLowR_bool_X_Limit */
  50UL,                                /* IN_brakeVLowR_bool_Y_Limit */
  25UL,                                /* IN_brakeVHighR_bool_X_Limit */
  50UL,                                /* IN_brakeVHighR_bool_Y_Limit */
  25UL,                                /* IN_brakeErrorR_bool_X_Limit */
  50UL,                                /* IN_brakeErrorR_bool_Y_Limit */
  1.5F,                                /* IN_bspdBrakeBadHigh */
  0.5F,                                /* IN_bspdBrakeBadLow */
  3.5F,                                /* IN_bspdBrakeGoodLow */
  4.5F,                                /* IN_bspdBrakeGoodHigh */
  25UL,                                /* IN_bspdBrakeError_bool_X_Limit */
  50UL,                                /* IN_bspdBrakeError_bool_Y_Limit */
  1.5F,                                /* IN_bspdStatusBadHigh */
  0.5F,                                /* IN_bspdStatusBadLow */
  3.5F,                                /* IN_bspdStatusGoodLow */
  4.5F,                                /* IN_bspdStatusGoodHigh */
  25UL,                                /* IN_bspdStatusError_bool_X_Limit */
  50UL,                                /* IN_bspdStatusError_bool_Y_Limit */
  0.5F,                                /* IN_coolantTempLowInverterIn_v */
  25UL,                          /* IN_coolantTempVLowInverterIn_bool_X_Limit */
  50UL,                          /* IN_coolantTempVLowInverterIn_bool_Y_Limit */
  4.5F,                                /* IN_coolantTempHighInverterIn_v */
  25UL,                         /* IN_coolantTempVHighInverterIn_bool_X_Limit */
  50UL,                         /* IN_coolantTempVHighInverterIn_bool_Y_Limit */
  25UL,                         /* IN_coolantTempErrorInverterIn_bool_X_Limit */
  50UL,                         /* IN_coolantTempErrorInverterIn_bool_Y_Limit */
  0.5F,                                /* IN_coolantTempLowInverterOut_v */
  25UL,                         /* IN_coolantTempVLowInverterOut_bool_X_Limit */
  50UL,                         /* IN_coolantTempVLowInverterOut_bool_Y_Limit */
  4.5F,                                /* IN_coolantTempHighInverterOut_v */
  25UL,                        /* IN_coolantTempVHighInverterOut_bool_X_Limit */
  50UL,                        /* IN_coolantTempVHighInverterOut_bool_Y_Limit */
  25UL,                        /* IN_coolantTempErrorInverterOut_bool_X_Limit */
  50UL,                        /* IN_coolantTempErrorInverterOut_bool_Y_Limit */
  0.5F,                                /* IN_coolantTempLowMotorIn_v */
  25UL,                             /* IN_coolantTempVLowMotorIn_bool_X_Limit */
  50UL,                             /* IN_coolantTempVLowMotorIn_bool_Y_Limit */
  4.5F,                                /* IN_coolantTempHighMotorIn_v */
  25UL,                            /* IN_coolantTempVHighMotorIn_bool_X_Limit */
  50UL,                            /* IN_coolantTempVHighMotorIn_bool_Y_Limit */
  25UL,                            /* IN_coolantTempErrorMotorIn_bool_X_Limit */
  50UL,                            /* IN_coolantTempErrorMotorIn_bool_Y_Limit */
  0.5F,                                /* IN_rotorTempLowFL_v */
  25UL,                                /* IN_rotorTempVLowFL_bool_X_Limit */
  50UL,                                /* IN_rotorTempVLowFL_bool_Y_Limit */
  4.5F,                                /* IN_rotorTempHighFL_v */
  25UL,                                /* IN_rotorTempVHighFL_bool_X_Limit */
  50UL,                                /* IN_rotorTempVHighFL_bool_Y_Limit */
  25UL,                                /* IN_rotorTempErrorFL_bool_X_Limit */
  50UL,                                /* IN_rotorTempErrorFL_bool_Y_Limit */

  { 0.5F, 0.6F, 0.7F, 0.8F, 0.9F, 1.0F, 1.1F, 1.2F, 1.3F, 1.4F, 1.5F, 2.0F, 2.5F,
    3.0F, 3.5F, 4.0F, 4.5F, },         /* IN_rotorTempVToDegFL_LookupX */

  { 0.0F, 20.0F, 40.0F, 60.0F, 80.0F, 100.0F, 120.0F, 140.0F, 160.0F, 180.0F,
    200.0F, 300.0F, 400.0F, 500.0F, 600.0F, 700.0F, 800.0F, },/* IN_rotorTempVToDegFL */
  0U,                                  /* IN_rotorTempFL_bool */
  0.5F,                                /* IN_rotorTempLowRL_v */
  25UL,                                /* IN_rotorTempVLowRL_bool_X_Limit */
  50UL,                                /* IN_rotorTempVLowRL_bool_Y_Limit */
  4.5F,                                /* IN_rotorTempHighRL_v */
  25UL,                                /* IN_rotorTempVHighRL_bool_X_Limit */
  50UL,                                /* IN_rotorTempVHighRL_bool_Y_Limit */
  25UL,                                /* IN_rotorTempErrorRL_bool_X_Limit */
  50UL,                                /* IN_rotorTempErrorRL_bool_Y_Limit */

  { 0.5F, 0.6F, 0.7F, 0.8F, 0.9F, 1.0F, 1.1F, 1.2F, 1.3F, 1.4F, 1.5F, 2.0F, 2.5F,
    3.0F, 3.5F, 4.0F, 4.5F, },         /* IN_rotorTempVToDegRL_LookupX */

  { 0.0F, 20.0F, 40.0F, 60.0F, 80.0F, 100.0F, 120.0F, 140.0F, 160.0F, 180.0F,
    200.0F, 300.0F, 400.0F, 500.0F, 600.0F, 700.0F, 800.0F, },/* IN_rotorTempVToDegRL */
  0U,                                  /* IN_rotorTempRL_bool */
  0.5F,                                /* IN_rotorTempLowFR_v */
  25UL,                                /* IN_rotorTempVLowFR_bool_X_Limit */
  50UL,                                /* IN_rotorTempVLowFR_bool_Y_Limit */
  4.5F,                                /* IN_rotorTempHighFR_v */
  25UL,                                /* IN_rotorTempVHighFR_bool_X_Limit */
  50UL,                                /* IN_rotorTempVHighFR_bool_Y_Limit */
  25UL,                                /* IN_rotorTempErrorFR_bool_X_Limit */
  50UL,                                /* IN_rotorTempErrorFR_bool_Y_Limit */

  { 0.5F, 0.6F, 0.7F, 0.8F, 0.9F, 1.0F, 1.1F, 1.2F, 1.3F, 1.4F, 1.5F, 2.0F, 2.5F,
    3.0F, 3.5F, 4.0F, 4.5F, },         /* IN_rotorTempVToDegFR_LookupX */

  { 0.0F, 20.0F, 40.0F, 60.0F, 80.0F, 100.0F, 120.0F, 140.0F, 160.0F, 180.0F,
    200.0F, 300.0F, 400.0F, 500.0F, 600.0F, 700.0F, 800.0F, },/* IN_rotorTempVToDegFR */
  0U,                                  /* IN_rotorTempFR_bool */
  0.5F,                                /* IN_rotorTempLowRR_v */
  25UL,                                /* IN_rotorTempVLowRR_bool_X_Limit */
  50UL,                                /* IN_rotorTempVLowRR_bool_Y_Limit */
  4.5F,                                /* IN_rotorTempHighRR_v */
  25UL,                                /* IN_rotorTempVHighRR_bool_X_Limit */
  50UL,                                /* IN_rotorTempVHighRR_bool_Y_Limit */
  25UL,                                /* IN_rotorTempErrorRR_bool_X_Limit */
  50UL,                                /* IN_rotorTempErrorRR_bool_Y_Limit */

  { 0.5F, 0.6F, 0.7F, 0.8F, 0.9F, 1.0F, 1.1F, 1.2F, 1.3F, 1.4F, 1.5F, 2.0F, 2.5F,
    3.0F, 3.5F, 4.0F, 4.5F, },         /* IN_rotorTempVToDegRR_LookupX */

  { 0.0F, 20.0F, 40.0F, 60.0F, 80.0F, 100.0F, 120.0F, 140.0F, 160.0F, 180.0F,
    200.0F, 300.0F, 400.0F, 500.0F, 600.0F, 700.0F, 800.0F, },/* IN_rotorTempVToDegRR */
  0U,                                  /* IN_rotorTempRR_bool */
  3.5F,                                /* IN_startSwitchNOHighUpperThresh */
  4.5F,                                /* IN_startSwitchNOHighLowerThresh */
  0.01F,                               /* IN_startSwitchNOLowLowerThresh */
  10.0F,                               /* IN_appsThreshold */
  25UL,                                /* IN_appsError_bool_X_Limit */
  50UL,                                /* IN_appsError_bool_Y_Limit */
  25UL,                                /* IN_throttleVLow1_bool_X_Limit */
  50UL,                                /* IN_throttleVLow1_bool_Y_Limit */
  25UL,                                /* IN_throttleVHigh1_bool_X_Limit */
  50UL,                                /* IN_throttleVHigh1_bool_Y_Limit */
  25UL,                                /* IN_throttleError1_bool_X_Limit */
  50UL,                                /* IN_throttleError1_bool_Y_Limit */
  25UL,                                /* IN_throttleVLow2_bool_X_Limit */
  50UL,                                /* IN_throttleVLow2_bool_Y_Limit */
  25UL,                                /* IN_throttleVHigh2_bool_X_Limit */
  50UL,                                /* IN_throttleVHigh2_bool_Y_Limit */
  25UL,                                /* IN_throttleError2_bool_X_Limit */
  50UL,                                /* IN_throttleError2_bool_Y_Limit */
  0.4F,                                /* IN_tireTempLowFLI_v */
  25UL,                                /* IN_tireTempVLowFLI_bool_X_Limit */
  50UL,                                /* IN_tireTempVLowFLI_bool_Y_Limit */
  4.6F,                                /* IN_tireTempHighFLI_v */
  25UL,                                /* IN_tireTempVHighFLI_bool_X_Limit */
  50UL,                                /* IN_tireTempVHighFLI_bool_Y_Limit */
  25UL,                                /* IN_tireTempErrorFLI_bool_X_Limit */
  50UL,                                /* IN_tireTempErrorFLI_bool_Y_Limit */

  { 0.4F, 1.0F, 1.6F, 2.2F, 2.8F, 3.4F, 4.0F, 4.6F, },/* IN_tireTempVToDegFLI_LookupX */

  { 0.0F, 20.0F, 40.0F, 60.0F, 80.0F, 100.0F, 120.0F, 140.0F, },/* IN_tireTempVToDegFLI */
  0U,                                  /* IN_tireTempFLI_bool */
  0.4F,                                /* IN_tireTempLowFLM_v */
  25UL,                                /* IN_tireTempVLowFLM_bool_X_Limit */
  50UL,                                /* IN_tireTempVLowFLM_bool_Y_Limit */
  4.6F,                                /* IN_tireTempHighFLM_v */
  25UL,                                /* IN_tireTempVHighFLM_bool_X_Limit */
  50UL,                                /* IN_tireTempVHighFLM_bool_Y_Limit */
  25UL,                                /* IN_tireTempErrorFLM_bool_X_Limit */
  50UL,                                /* IN_tireTempErrorFLM_bool_Y_Limit */

  { 0.4F, 1.0F, 1.6F, 2.2F, 2.8F, 3.4F, 4.0F, 4.6F, },/* IN_tireTempVToDegFLM_LookupX */

  { 0.0F, 20.0F, 40.0F, 60.0F, 80.0F, 100.0F, 120.0F, 140.0F, },/* IN_tireTempVToDegFLM */
  0U,                                  /* IN_tireTempFLM_bool */
  0.4F,                                /* IN_tireTempLowFLO_v */
  25UL,                                /* IN_tireTempVLowFLO_bool_X_Limit */
  50UL,                                /* IN_tireTempVLowFLO_bool_Y_Limit */
  4.6F,                                /* IN_tireTempHighFLO_v */
  25UL,                                /* IN_tireTempVHighFLO_bool_X_Limit */
  50UL,                                /* IN_tireTempVHighFLO_bool_Y_Limit */
  25UL,                                /* IN_tireTempErrorFLO_bool_X_Limit */
  50UL,                                /* IN_tireTempErrorFLO_bool_Y_Limit */

  { 0.4F, 1.0F, 1.6F, 2.2F, 2.8F, 3.4F, 4.0F, 4.6F, },/* IN_tireTempVToDegFLO_LookupX */

  { 0.0F, 20.0F, 40.0F, 60.0F, 80.0F, 100.0F, 120.0F, 140.0F, },/* IN_tireTempVToDegFLO */
  0U,                                  /* IN_tireTempFLO_bool */
  0.4F,                                /* IN_tireTempLowFRI_v */
  25UL,                                /* IN_tireTempVLowFRI_bool_X_Limit */
  50UL,                                /* IN_tireTempVLowFRI_bool_Y_Limit */
  4.6F,                                /* IN_tireTempHighFRI_v */
  25UL,                                /* IN_tireTempVHighFRI_bool_X_Limit */
  50UL,                                /* IN_tireTempVHighFRI_bool_Y_Limit */
  25UL,                                /* IN_tireTempErrorFRI_bool_X_Limit */
  50UL,                                /* IN_tireTempErrorFRI_bool_Y_Limit */

  { 0.4F, 1.0F, 1.6F, 2.2F, 2.8F, 3.4F, 4.0F, 4.6F, },/* IN_tireTempVToDegFRI_LookupX */

  { 0.0F, 20.0F, 40.0F, 60.0F, 80.0F, 100.0F, 120.0F, 140.0F, },/* IN_tireTempVToDegFRI */
  0U,                                  /* IN_tireTempFRI_bool */
  0.4F,                                /* IN_tireTempLowFRM_v */
  25UL,                                /* IN_tireTempVLowFRM_bool_X_Limit */
  50UL,                                /* IN_tireTempVLowFRM_bool_Y_Limit */
  4.6F,                                /* IN_tireTempHighFRM_v */
  25UL,                                /* IN_tireTempVHighFRM_bool_X_Limit */
  50UL,                                /* IN_tireTempVHighFRM_bool_Y_Limit */
  25UL,                                /* IN_tireTempErrorFRM_bool_X_Limit */
  50UL,                                /* IN_tireTempErrorFRM_bool_Y_Limit */

  { 0.4F, 1.0F, 1.6F, 2.2F, 2.8F, 3.4F, 4.0F, 4.6F, },/* IN_tireTempVToDegFRM_LookupX */

  { 0.0F, 20.0F, 40.0F, 60.0F, 80.0F, 100.0F, 120.0F, 140.0F, },/* IN_tireTempVToDegFRM */
  0U,                                  /* IN_tireTempFRM_bool */
  0.4F,                                /* IN_tireTempLowFRO_v */
  25UL,                                /* IN_tireTempVLowFRO_bool_X_Limit */
  50UL,                                /* IN_tireTempVLowFRO_bool_Y_Limit */
  4.6F,                                /* IN_tireTempHighFRO_v */
  25UL,                                /* IN_tireTempVHighFRO_bool_X_Limit */
  50UL,                                /* IN_tireTempVHighFRO_bool_Y_Limit */
  25UL,                                /* IN_tireTempErrorFRO_bool_X_Limit */
  50UL,                                /* IN_tireTempErrorFRO_bool_Y_Limit */

  { 0.4F, 1.0F, 1.6F, 2.2F, 2.8F, 3.4F, 4.0F, 4.6F, },/* IN_tireTempVToDegFRO_LookupX */

  { 0.0F, 20.0F, 40.0F, 60.0F, 80.0F, 100.0F, 120.0F, 140.0F, },/* IN_tireTempVToDegFRO */
  0U,                                  /* IN_tireTempFRO_bool */
  0.4F,                                /* IN_tireTempLowRLI_v */
  25UL,                                /* IN_tireTempVLowRLI_bool_X_Limit */
  50UL,                                /* IN_tireTempVLowRLI_bool_Y_Limit */
  4.6F,                                /* IN_tireTempHighRLI_v */
  25UL,                                /* IN_tireTempVHighRLI_bool_X_Limit */
  50UL,                                /* IN_tireTempVHighRLI_bool_Y_Limit */
  25UL,                                /* IN_tireTempErrorRLI_bool_X_Limit */
  50UL,                                /* IN_tireTempErrorRLI_bool_Y_Limit */

  { 0.4F, 1.0F, 1.6F, 2.2F, 2.8F, 3.4F, 4.0F, 4.6F, },/* IN_tireTempVToDegRLI_LookupX */

  { 0.0F, 20.0F, 40.0F, 60.0F, 80.0F, 100.0F, 120.0F, 140.0F, },/* IN_tireTempVToDegRLI */
  0U,                                  /* IN_tireTempRLI_bool */
  0.4F,                                /* IN_tireTempLowRLM_v */
  25UL,                                /* IN_tireTempVLowRLM_bool_X_Limit */
  50UL,                                /* IN_tireTempVLowRLM_bool_Y_Limit */
  4.6F,                                /* IN_tireTempHighRLM_v */
  25UL,                                /* IN_tireTempVHighRLM_bool_X_Limit */
  50UL,                                /* IN_tireTempVHighRLM_bool_Y_Limit */
  25UL,                                /* IN_tireTempErrorRLM_bool_X_Limit */
  50UL,                                /* IN_tireTempErrorRLM_bool_Y_Limit */

  { 0.4F, 1.0F, 1.6F, 2.2F, 2.8F, 3.4F, 4.0F, 4.6F, },/* IN_tireTempVToDegRLM_LookupX */

  { 0.0F, 20.0F, 40.0F, 60.0F, 80.0F, 100.0F, 120.0F, 140.0F, },/* IN_tireTempVToDegRLM */
  0U,                                  /* IN_tireTempRLM_bool */
  0.4F,                                /* IN_tireTempLowRLO_v */
  25UL,                                /* IN_tireTempVLowRLO_bool_X_Limit */
  50UL,                                /* IN_tireTempVLowRLO_bool_Y_Limit */
  4.6F,                                /* IN_tireTempHighRLO_v */
  25UL,                                /* IN_tireTempVHighRLO_bool_X_Limit */
  50UL,                                /* IN_tireTempVHighRLO_bool_Y_Limit */
  25UL,                                /* IN_tireTempErrorRLO_bool_X_Limit */
  50UL,                                /* IN_tireTempErrorRLO_bool_Y_Limit */

  { 0.4F, 1.0F, 1.6F, 2.2F, 2.8F, 3.4F, 4.0F, 4.6F, },/* IN_tireTempVToDegRLO_LookupX */

  { 0.0F, 20.0F, 40.0F, 60.0F, 80.0F, 100.0F, 120.0F, 140.0F, },/* IN_tireTempVToDegRLO */
  0U,                                  /* IN_tireTempRLO_bool */
  0.4F,                                /* IN_tireTempLowRRI_v */
  25UL,                                /* IN_tireTempVLowRRI_bool_X_Limit */
  50UL,                                /* IN_tireTempVLowRRI_bool_Y_Limit */
  4.6F,                                /* IN_tireTempHighRRI_v */
  25UL,                                /* IN_tireTempVHighRRI_bool_X_Limit */
  50UL,                                /* IN_tireTempVHighRRI_bool_Y_Limit */
  25UL,                                /* IN_tireTempErrorRRI_bool_X_Limit */
  50UL,                                /* IN_tireTempErrorRRI_bool_Y_Limit */

  { 0.4F, 1.0F, 1.6F, 2.2F, 2.8F, 3.4F, 4.0F, 4.6F, },/* IN_tireTempVToDegRRI_LookupX */

  { 0.0F, 20.0F, 40.0F, 60.0F, 80.0F, 100.0F, 120.0F, 140.0F, },/* IN_tireTempVToDegRRI */
  0U,                                  /* IN_tireTempRRI_bool */
  0.4F,                                /* IN_tireTempLowRRM_v */
  25UL,                                /* IN_tireTempVLowRRM_bool_X_Limit */
  50UL,                                /* IN_tireTempVLowRRM_bool_Y_Limit */
  4.6F,                                /* IN_tireTempHighRRM_v */
  25UL,                                /* IN_tireTempVHighRRM_bool_X_Limit */
  50UL,                                /* IN_tireTempVHighRRM_bool_Y_Limit */
  25UL,                                /* IN_tireTempErrorRRM_bool_X_Limit */
  50UL,                                /* IN_tireTempErrorRRM_bool_Y_Limit */

  { 0.4F, 1.0F, 1.6F, 2.2F, 2.8F, 3.4F, 4.0F, 4.6F, },/* IN_tireTempVToDegRRM_LookupX */

  { 0.0F, 20.0F, 40.0F, 60.0F, 80.0F, 100.0F, 120.0F, 140.0F, },/* IN_tireTempVToDegRRM */
  0U,                                  /* IN_tireTempRRM_bool */
  0.4F,                                /* IN_tireTempLowRRO_v */
  25UL,                                /* IN_tireTempVLowRRO_bool_X_Limit */
  50UL,                                /* IN_tireTempVLowRRO_bool_Y_Limit */
  4.6F,                                /* IN_tireTempHighRRO_v */
  25UL,                                /* IN_tireTempVHighRRO_bool_X_Limit */
  50UL,                                /* IN_tireTempVHighRRO_bool_Y_Limit */
  25UL,                                /* IN_tireTempErrorRRO_bool_X_Limit */
  50UL,                                /* IN_tireTempErrorRRO_bool_Y_Limit */

  { 0.4F, 1.0F, 1.6F, 2.2F, 2.8F, 3.4F, 4.0F, 4.6F, },/* IN_tireTempVToDegRRO_LookupX */

  { 0.0F, 20.0F, 40.0F, 60.0F, 80.0F, 100.0F, 120.0F, 140.0F, },/* IN_tireTempVToDegRRO */
  0U,                                  /* IN_tireTempRRO_bool */
  3.5F,                                /* IN_tsSwitchNOHighUpperThresh */
  4.5F,                                /* IN_tsSwitchNOHighLowerThresh */
  0.01F,                               /* IN_tsSwitchNOLowLowerThresh */
  0.0F,                                /* IN_hallEffectLowFL_hz */
  25UL,                                /* IN_hallEffectVLowFL_bool_X_Limit */
  50UL,                                /* IN_hallEffectVLowFL_bool_Y_Limit */
  1680.0F,                             /* IN_hallEffectHighFL_hz */
  25UL,                                /* IN_hallEffectVHighFL_bool_X_Limit */
  50UL,                                /* IN_hallEffectVHighFL_bool_Y_Limit */
  25UL,                                /* IN_hallEffectErrorFL_bool_X_Limit */
  50UL,                                /* IN_hallEffectErrorFL_bool_Y_Limit */
  0.0F,                                /* IN_hallEffectLowFR_hz */
  25UL,                                /* IN_hallEffectVLowFR_bool_X_Limit */
  50UL,                                /* IN_hallEffectVLowFR_bool_Y_Limit */
  1680.0F,                             /* IN_hallEffectHighFR_hz */
  25UL,                                /* IN_hallEffectVHighFR_bool_X_Limit */
  50UL,                                /* IN_hallEffectVHighFR_bool_Y_Limit */
  25UL,                                /* IN_hallEffectErrorFR_bool_X_Limit */
  50UL,                                /* IN_hallEffectErrorFR_bool_Y_Limit */
  0.0F,                                /* IN_hallEffectLowRL_hz */
  25UL,                                /* IN_hallEffectVLowRL_bool_X_Limit */
  50UL,                                /* IN_hallEffectVLowRL_bool_Y_Limit */
  1680.0F,                             /* IN_hallEffectHighRL_hz */
  25UL,                                /* IN_hallEffectVHighRL_bool_X_Limit */
  50UL,                                /* IN_hallEffectVHighRL_bool_Y_Limit */
  25UL,                                /* IN_hallEffectErrorRL_bool_X_Limit */
  50UL,                                /* IN_hallEffectErrorRL_bool_Y_Limit */
  0.0F,                                /* IN_hallEffectLowRR_hz */
  25UL,                                /* IN_hallEffectVLowRR_bool_X_Limit */
  50UL,                                /* IN_hallEffectVLowRR_bool_Y_Limit */
  1680.0F,                             /* IN_hallEffectHighRR_hz */
  25UL,                                /* IN_hallEffectVHighRR_bool_X_Limit */
  50UL,                                /* IN_hallEffectVHighRR_bool_Y_Limit */
  25UL,                                /* IN_hallEffectErrorRR_bool_X_Limit */
  50UL,                                /* IN_hallEffectErrorRR_bool_Y_Limit */
  0U,                                  /* IN_coolPolarityOverride_bool */
  0U,                                  /* IN_PolarityOverride_bool */
  0U,                                  /* IN_markPolarityOverride_bool */
  0U,                                  /* IN_pageDownPolarityOverride_bool */
  0U,                                  /* IN_pageUpPolarityOverride_bool */
  0U,                                  /* IN_pttPolarityOverride_bool */
  0U,                                  /* IN_pwrDownPolarityOverride_bool */
  0U,                                  /* IN_pwrUpPolarityOverride_bool */
  0U,                                  /* OUT_speedModeEnable_bool */
  1U,                                  /* OUT_dischargeEnable_bool */
  1U,                                  /* OUT_inverterEnable_bool */
  0U,                                  /* OUT_directionCommand_bool */
  0.0F,                                /* OUT_speedCommand_rpm */
  256UL,                               /* XCP1__XCP_BC_ID */
  512UL,                               /* XCP1__XCP_RX_ID */
  768UL,                               /* XCP1__XCP_TX_ID */
  0.2032F,                             /* DATA_unloadedWheelRadius_m */
  48.0F,                               /* DATA_wheelTooth_ct */
  231.0F,                              /* DATA_maxMotorTorque_Nm */
  3U,                                  /* INPUT29_ADCMon_HoldCount */
  20038U,                              /* XCP1__XCP_Security */
  500U,                                /* CAN1_Startup_Delay */
  20U,                                 /* CAN1_ErrorCheck_Interval */
  20U,                                 /* CAN1_ErrorPassive_Delay */
  500U,                                /* CAN2_Startup_Delay */
  20U,                                 /* CAN2_ErrorCheck_Interval */
  20U,                                 /* CAN2_ErrorPassive_Delay */

  { FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, },/* raptorFaultOperation */
  1U,                                  /* InjCDrv_EndOfStart */
  1U,                                  /* EndOfStart */
  0,                                   /* CRC Initial Value */
};

#define STOP_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"
#define START_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

EEVariables_T EEVariables_RAMShadow ;

#define STOP_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

uint32_T g_EE_LoadedCopy = 0;

#define FEE_NUM_PAGES                  18

uint16_T read_eeprom(void);

#define EE_PAGE_SIZE                   120
#define FEE_MAX_NUM_PAGES              18
#define FEE_SIZE_CALC()                (((uint32_T)&FEEVariables_RAMShadow.CRC - (uint32_T)&FEEVariables_RAMShadow) + 2)
#define EE_SIZE_CALC()                 (((uint32_T)&EEVariables_RAMShadow.CRC - (uint32_T)&EEVariables_RAMShadow) + 2)
#define RETRY_MAX                      1000

bool g_feeWrite_Started = 0;

/* MANAGE EE PROM MEMORY */
void App_EE_Defaults(void)
{
  memcpy(&EEVariables_RAMShadow, &EEVariables_DEFAULT, sizeof(EEVariables_T));
  EEPROM_State_Data() = EE_LOADED_DEFAULTS;
}

void App_EE_Init(void);
void App_EE_Init(void)
{
  uint8_T firstStart= 0;
  uint32_T ee_size = EE_SIZE_CALC();
  if (Reset_Env.xId == SWRESET_POWERON_SIMU_E || Reset_Env.xId ==
      SWRESET_CBPROG_E) {
    /* SWRESET_CBPROG_E */
    /* SWRESET_POWERON_SIMU_E, SWRESET_CBPROG_E */
    firstStart = (Reset_Env.xGrp == 0x06);
  } else if ((Reset_xHistBuf[0] == RESET_SWRESET_MOCRAM_REPEXOK) &&
             (Reset_xHistBuf[1] == SWRESET_POWERON_SIMU_E) && (Reset_xHistBuf[2]
              == SWRESET_CBPROG_E)) {
    /*RESET_SWRESET_MOCRAM_REPEXOK, SWRESET_POWERON_SIMU_E, SWRESET_CBPROG_E */
    firstStart = (Reset_Env.xGrp == 0x07);
  }

  /* Fixed NV Read */
  if (firstStart) {
    /* Load defaults after programming - new values may have been merged into EEVariables_DEFAULT */
    App_EE_Defaults();
    EEPROM_State_Data() = EE_LOADED_DEFAULTS_AFTER_PROGRAMMING;
  } else if (read_eeprom() != SWS_EEP_SUCCEEDED) {
    /* Revert to defaults - error reading stored data */
    App_EE_Defaults();
    EEPROM_State_Data() = EE_LOADED_DEFAULTS_ERROR_READING;
  } else if (EEVariables_RAMShadow.EE_UniqID != EEVariables_DEFAULT.EE_UniqID) {
    /* Revert to defaults - the data stored previously doesn't match the format for the current application */
    App_EE_Defaults();
    EEPROM_State_Data() = EE_LOADED_DEFAULTS_INCORRECT_EEID;
  } else if (!is_crc_valid((void*)&EEVariables_RAMShadow, ee_size-2,
              EEVariables_RAMShadow.CRC)) {
    /* Revert to defaults - stored data is corrupted */
    App_EE_Defaults();
    EEPROM_State_Data() = EE_LOADED_DEFAULTS_INCORRECT_CRC;
  } else {
    /* Normal case startup, reloaded values */
    EEPROM_State_Data() = EE_LOADED_SAVED_VALUES;
                                      /* Normal case startup, reloaded values */
  }
}

void App_EE_Store(void)
{
  if (EEPROM_State_Data() != EE_STORE_IN_PROGESS) {
    EEPROM_State_Data() = EE_STORE_IN_PROGESS;
    App_EE_WriteAsync(1);
  }
}

/* Extra Funcitons Definitions for EEPROM */
uint16_T read_eeprom(void)
{
  swsEEP_ret result;
  uint16_T eeReadIdx = 20;
  uint8_T readBuf[120];
  uint8_T retryCnt = 0;
  uint8_T* wrPtr = (uint8_T*)&EEVariables_RAMShadow;
  uint32_T ee_size = EE_SIZE_CALC();
  uint16_T total_EE_PgCnt = (ee_size / EE_PAGE_SIZE) + ((ee_size % EE_PAGE_SIZE)
    > 0);
  uint16_T lastPageIdx = total_EE_PgCnt + 20;
  uint16_T lastFullpageIndx = 0;
  eeReadIdx = 20;
  lastPageIdx = total_EE_PgCnt + eeReadIdx;
  if ((EE_SIZE_CALC() % EE_PAGE_SIZE) == 0) {
    lastFullpageIndx = lastPageIdx;
  } else {
    lastFullpageIndx = lastPageIdx - 1;
  }

  /* READ Full EEPROM */
  for (; eeReadIdx < lastPageIdx; eeReadIdx++) {
    retryCnt = 0;
    for (retryCnt = 0; retryCnt < 25; retryCnt++) {
      result = swsEEP_Read_Directly((void*)&readBuf, eeReadIdx);
      if (result == SWS_EEP_SUCCEEDED) {
        break;
      }
    }

    if (result == SWS_EEP_SUCCEEDED) {
      /* copy into EEVariables_RAMShadow	*/
      if (eeReadIdx < lastFullpageIndx) {
        memcpy(wrPtr, &readBuf, EE_PAGE_SIZE);
        wrPtr += EE_PAGE_SIZE;
      } else {
        uint16_T eeReadSize = (EE_SIZE_CALC() % EE_PAGE_SIZE);
        if (eeReadSize == 0) {
          eeReadSize = EE_PAGE_SIZE;
        }

        memcpy(wrPtr, &readBuf, eeReadSize);
      }
    } else {
      break;
    }
  }

  return result;
}

void App_EE_WriteAsync(uint8_T startWrite)
{
  static uint32_T ee_size = 0;
  static uint16_T total_EE_PgCnt = 0;
  static bool eeWrite_Started = 0;
  static uint16_T eeWrite_RetryCnt = 0;
  static uint8_T* eeWrite_Ptr;
  static uint16_T eeWrite_Idx = 20;
  static uint16_T runningCRC = 0xFFFF;
  static uint32_T ee_WriteLen = 0;
  static uint16_T lastPageIdx = 0;
  static uint8_T writeBuffer[EE_PAGE_SIZE] = { 0 };

  swsEEP_ret result;

  //only execute if we are starting a write or already have one in progress
  if (!startWrite && !eeWrite_Started) {
    return;
  }

  if (!eeWrite_Started) {
    eeWrite_RetryCnt = 0;
    eeWrite_Ptr = (void*)&EEVariables_RAMShadow;
    EEPROM_State_Data() = EE_STORE_IN_PROGESS;
    ee_size = EE_SIZE_CALC();
    total_EE_PgCnt = (ee_size / EE_PAGE_SIZE) + ((ee_size % EE_PAGE_SIZE) > 0);
    eeWrite_Started = 1;
    eeWrite_Idx = 20;
    ee_WriteLen = EE_PAGE_SIZE;
    lastPageIdx = total_EE_PgCnt + eeWrite_Idx - 1;
    runningCRC = 0xFFFF;
    if (total_EE_PgCnt == 1) {
      SuspInt();                     //suspend interrupts while we calculate CRC

      //and copy to write buffer so data is not modified elsewhere

      //EE is a single page
      ee_WriteLen = ee_size;
      runningCRC = crc16_spd((void*)&EEVariables_RAMShadow, ee_WriteLen-2,
        runningCRC);
      EEVariables_RAMShadow.CRC = runningCRC;
      memcpy((void*)&writeBuffer, eeWrite_Ptr, ee_WriteLen);
      ResInt();
    } else {
      memcpy((void*)&writeBuffer, eeWrite_Ptr, ee_WriteLen);
      runningCRC = crc16_spd((void*)&writeBuffer, ee_WriteLen, runningCRC);
    }

    // Write the first set of pages to the queue
    result = swsEEP_Write_Directly((void*)&writeBuffer, eeWrite_Idx);
  } else {
    // Check status of previous page writes
    result = swsEEP_Write_Directly((void*)&writeBuffer, eeWrite_Idx);
    if (result == SWS_EEP_SUCCEEDED) {
      //Success
      eeWrite_RetryCnt = 0;
      eeWrite_Idx++;
      eeWrite_Ptr += EE_PAGE_SIZE;
      if (eeWrite_Idx == lastPageIdx ) {
        //last page, update crc
        SuspInt();                   //suspend interrupts while we calculate CRC

        //and copy to write buffer so data is not modified elsewhere
        ee_WriteLen = ee_size % EE_PAGE_SIZE;
        if (ee_WriteLen == 0) {
          ee_WriteLen = EE_PAGE_SIZE;
        }

        runningCRC = crc16_spd((void*)eeWrite_Ptr, ee_WriteLen-2, runningCRC);
        EEVariables_RAMShadow.CRC = runningCRC;
        memcpy((void*)&writeBuffer, (void*)eeWrite_Ptr, ee_WriteLen);
        ResInt();
      } else if (eeWrite_Idx < lastPageIdx) {
        memcpy((void*)&writeBuffer, eeWrite_Ptr, ee_WriteLen);
        runningCRC = crc16_spd((void*)&writeBuffer, ee_WriteLen, runningCRC);
      }

      /* Queue up the write operatation */
      if (eeWrite_Idx <= lastPageIdx) {
        // write new page
        result = swsEEP_Write_Directly((void*)&writeBuffer, eeWrite_Idx);
      } else {
        //finished
        eeWrite_Started = 0;
        EEPROM_State_Data() = EE_STORE_SUCCESS;
      }
    } else if (eeWrite_RetryCnt < RETRY_MAX) {
      //we will check next time
      eeWrite_RetryCnt++;
    } else {
      //Abort Operation
      EEPROM_State_Data() = EE_STORE_FAILED;
      eeWrite_Started = 0;
    }
  }
}

#define START_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

RAMEditVariables_T RAMEditVariables ;

#define STOP_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"
#define START_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

const RAMEditVariables_T RAMEditVariables_DEFAULT = {
  55,                                  /*INIT_RAM_EditVariables*/
  0U,                                  /* CTRL_brakelight_bool_OvrVal */
  0U,                                  /* CTRL_brakelight_bool_OvrSts */
  0.0F,                                /* CTRL_torqueCommand_Nm_OvrVal */
  0U,                                  /* CTRL_torqueCommand_Nm_OvrSts */
  0.0F,                                /* IN_tcSet_OvrVal */
  0U,                                  /* IN_tcSet_OvrSts */
  0.0F,                                /* IN_brakePosOverrideF_pct_OvrVal */
  0U,                                  /* IN_brakePosOverrideF_pct_OvrSts */
  0.0F,                                /* IN_brakePosOverrideR_pct_OvrVal */
  0U,                                  /* IN_brakePosOverrideR_pct_OvrSts */
  0.0F,                                /* IN_coolantTempInverterIn_deg_OvrVal */
  0U,                                  /* IN_coolantTempInverterIn_deg_OvrSts */
  0.0F,                               /* IN_coolantTempInverterOut_deg_OvrVal */
  0U,                                 /* IN_coolantTempInverterOut_deg_OvrSts */
  0.0F,                                /* IN_coolantTempMotorIn_deg_OvrVal */
  0U,                                  /* IN_coolantTempMotorIn_deg_OvrSts */
  0.0F,                                /* IN_throttleOverride1_pct_OvrVal */
  0U,                                  /* IN_throttleOverride1_pct_OvrSts */
  0.0F,                                /* IN_throttleOverride2_pct_OvrVal */
  0U,                                  /* IN_throttleOverride2_pct_OvrSts */
  0.0F,                                /* IN_rotorTempFL_deg_OvrVal */
  0U,                                  /* IN_rotorTempFL_deg_OvrSts */
  0.0F,                                /* IN_rotorTempRL_deg_OvrVal */
  0U,                                  /* IN_rotorTempRL_deg_OvrSts */
  0.0F,                                /* IN_rotorTempFR_deg_OvrVal */
  0U,                                  /* IN_rotorTempFR_deg_OvrSts */
  0.0F,                                /* IN_rotorTempRR_deg_OvrVal */
  0U,                                  /* IN_rotorTempRR_deg_OvrSts */
  0.0F,                                /* IN_tireTempFLI_deg_OvrVal */
  0U,                                  /* IN_tireTempFLI_deg_OvrSts */
  0.0F,                                /* IN_tireTempFLM_deg_OvrVal */
  0U,                                  /* IN_tireTempFLM_deg_OvrSts */
  0.0F,                                /* IN_tireTempFLO_deg_OvrVal */
  0U,                                  /* IN_tireTempFLO_deg_OvrSts */
  0.0F,                                /* IN_tireTempFRI_deg_OvrVal */
  0U,                                  /* IN_tireTempFRI_deg_OvrSts */
  0.0F,                                /* IN_tireTempFRM_deg_OvrVal */
  0U,                                  /* IN_tireTempFRM_deg_OvrSts */
  0.0F,                                /* IN_tireTempFRO_deg_OvrVal */
  0U,                                  /* IN_tireTempFRO_deg_OvrSts */
  0.0F,                                /* IN_tireTempRLI_deg_OvrVal */
  0U,                                  /* IN_tireTempRLI_deg_OvrSts */
  0.0F,                                /* IN_tireTempRLM_deg_OvrVal */
  0U,                                  /* IN_tireTempRLM_deg_OvrSts */
  0.0F,                                /* IN_tireTempRLO_deg_OvrVal */
  0U,                                  /* IN_tireTempRLO_deg_OvrSts */
  0.0F,                                /* IN_tireTempRRI_deg_OvrVal */
  0U,                                  /* IN_tireTempRRI_deg_OvrSts */
  0.0F,                                /* IN_tireTempRRM_deg_OvrVal */
  0U,                                  /* IN_tireTempRRM_deg_OvrSts */
  0.0F,                                /* IN_tireTempRRO_deg_OvrVal */
  0U,                                  /* IN_tireTempRRO_deg_OvrSts */
  0U,                                  /* Timer_ooqlV_Steps */
  0U,                                  /* Timer_BGND_G6Wyo_Steps */
  (uint8_T)APPMON_RUN,                 /* AppMonitorState */
  0U,                                  /* EVSR24_step_Steps */
};

#define STOP_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

void initRAMEditVariables(void)
{
  memcpy(&RAMEditVariables, &RAMEditVariables_DEFAULT, sizeof
         (RAMEditVariables_DEFAULT));
}
