/*****************************************************************************
   faultmanager.c
   Generated By:
   Raptor 2023a_2.0.15039 (7682)
   Matlab (R2022b) 9.13

   Copyright (c) 2023 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Tue Oct 17 21:06:40 2023
 *****************************************************************************/

#include "faultmanager.h"
#include "EVSR24.h"
#include "EVSR24_private.h"

typedef void (* FaultActionTrigger) (int16_T faultIdx);
const FaultActionTrigger actionTriggerList[] = {
  NULL,
};

const int16_T persistMap[] = {
  -1,                                  /* IN_appsError_bool */
  -1,                                  /* IN_brakeErrorF_bool */
  -1,                                  /* IN_brakeErrorR_bool */
  -1,                                  /* IN_brakeVHighF_bool */
  -1,                                  /* IN_brakeVHighR_bool */
  -1,                                  /* IN_brakeVLowF_bool */
  -1,                                  /* IN_brakeVLowR_bool */
  -1,                                  /* IN_bspdBrakeError_bool */
  -1,                                  /* IN_bspdStatusError_bool */
  -1,                                  /* IN_coolantTempErrorInverterIn_bool */
  -1,                                  /* IN_coolantTempErrorInverterOut_bool */
  -1,                                  /* IN_coolantTempErrorMotorIn_bool */
  -1,                                  /* IN_coolantTempVHighInverterIn_bool */
  -1,                                  /* IN_coolantTempVHighInverterOut_bool */
  -1,                                  /* IN_coolantTempVHighMotorIn_bool */
  -1,                                  /* IN_coolantTempVLowInverterIn_bool */
  -1,                                  /* IN_coolantTempVLowInverterOut_bool */
  -1,                                  /* IN_coolantTempVLowMotorIn_bool */
  -1,                                  /* IN_hallEffectErrorFL_bool */
  -1,                                  /* IN_hallEffectErrorFR_bool */
  -1,                                  /* IN_hallEffectErrorRL_bool */
  -1,                                  /* IN_hallEffectErrorRR_bool */
  -1,                                  /* IN_hallEffectVHighFL_bool */
  -1,                                  /* IN_hallEffectVHighFR_bool */
  -1,                                  /* IN_hallEffectVHighRL_bool */
  -1,                                  /* IN_hallEffectVHighRR_bool */
  -1,                                  /* IN_hallEffectVLowFL_bool */
  -1,                                  /* IN_hallEffectVLowFR_bool */
  -1,                                  /* IN_hallEffectVLowRL_bool */
  -1,                                  /* IN_hallEffectVLowRR_bool */
  -1,                                  /* IN_rotorTempErrorFL_bool */
  -1,                                  /* IN_rotorTempErrorFR_bool */
  -1,                                  /* IN_rotorTempErrorRL_bool */
  -1,                                  /* IN_rotorTempErrorRR_bool */
  -1,                                  /* IN_rotorTempVHighFL_bool */
  -1,                                  /* IN_rotorTempVHighFR_bool */
  -1,                                  /* IN_rotorTempVHighRL_bool */
  -1,                                  /* IN_rotorTempVHighRR_bool */
  -1,                                  /* IN_rotorTempVLowFL_bool */
  -1,                                  /* IN_rotorTempVLowFR_bool */
  -1,                                  /* IN_rotorTempVLowRL_bool */
  -1,                                  /* IN_rotorTempVLowRR_bool */
  -1,                                  /* IN_throttleError1_bool */
  -1,                                  /* IN_throttleError2_bool */
  -1,                                  /* IN_throttleVHigh1_bool */
  -1,                                  /* IN_throttleVHigh2_bool */
  -1,                                  /* IN_throttleVLow1_bool */
  -1,                                  /* IN_throttleVLow2_bool */
  -1,                                  /* IN_tireTempErrorFLI_bool */
  -1,                                  /* IN_tireTempErrorFLM_bool */
  -1,                                  /* IN_tireTempErrorFLO_bool */
  -1,                                  /* IN_tireTempErrorFRI_bool */
  -1,                                  /* IN_tireTempErrorFRM_bool */
  -1,                                  /* IN_tireTempErrorFRO_bool */
  -1,                                  /* IN_tireTempErrorRLI_bool */
  -1,                                  /* IN_tireTempErrorRLM_bool */
  -1,                                  /* IN_tireTempErrorRLO_bool */
  -1,                                  /* IN_tireTempErrorRRI_bool */
  -1,                                  /* IN_tireTempErrorRRM_bool */
  -1,                                  /* IN_tireTempErrorRRO_bool */
  -1,                                  /* IN_tireTempVHighFLI_bool */
  -1,                                  /* IN_tireTempVHighFLM_bool */
  -1,                                  /* IN_tireTempVHighFLO_bool */
  -1,                                  /* IN_tireTempVHighFRI_bool */
  -1,                                  /* IN_tireTempVHighFRM_bool */
  -1,                                  /* IN_tireTempVHighFRO_bool */
  -1,                                  /* IN_tireTempVHighRLI_bool */
  -1,                                  /* IN_tireTempVHighRLM_bool */
  -1,                                  /* IN_tireTempVHighRLO_bool */
  -1,                                  /* IN_tireTempVHighRRI_bool */
  -1,                                  /* IN_tireTempVHighRRM_bool */
  -1,                                  /* IN_tireTempVHighRRO_bool */
  -1,                                  /* IN_tireTempVLowFLI_bool */
  -1,                                  /* IN_tireTempVLowFLM_bool */
  -1,                                  /* IN_tireTempVLowFLO_bool */
  -1,                                  /* IN_tireTempVLowFRI_bool */
  -1,                                  /* IN_tireTempVLowFRM_bool */
  -1,                                  /* IN_tireTempVLowFRO_bool */
  -1,                                  /* IN_tireTempVLowRLI_bool */
  -1,                                  /* IN_tireTempVLowRLM_bool */
  -1,                                  /* IN_tireTempVLowRLO_bool */
  -1,                                  /* IN_tireTempVLowRRI_bool */
  -1,                                  /* IN_tireTempVLowRRM_bool */
  -1,                                  /* IN_tireTempVLowRRO_bool */
};

const int16_T stickyMap[] = {
  -1,                                  /* IN_appsError_bool */
  -1,                                  /* IN_brakeErrorF_bool */
  -1,                                  /* IN_brakeErrorR_bool */
  -1,                                  /* IN_brakeVHighF_bool */
  -1,                                  /* IN_brakeVHighR_bool */
  -1,                                  /* IN_brakeVLowF_bool */
  -1,                                  /* IN_brakeVLowR_bool */
  -1,                                  /* IN_bspdBrakeError_bool */
  -1,                                  /* IN_bspdStatusError_bool */
  -1,                                  /* IN_coolantTempErrorInverterIn_bool */
  -1,                                  /* IN_coolantTempErrorInverterOut_bool */
  -1,                                  /* IN_coolantTempErrorMotorIn_bool */
  -1,                                  /* IN_coolantTempVHighInverterIn_bool */
  -1,                                  /* IN_coolantTempVHighInverterOut_bool */
  -1,                                  /* IN_coolantTempVHighMotorIn_bool */
  -1,                                  /* IN_coolantTempVLowInverterIn_bool */
  -1,                                  /* IN_coolantTempVLowInverterOut_bool */
  -1,                                  /* IN_coolantTempVLowMotorIn_bool */
  -1,                                  /* IN_hallEffectErrorFL_bool */
  -1,                                  /* IN_hallEffectErrorFR_bool */
  -1,                                  /* IN_hallEffectErrorRL_bool */
  -1,                                  /* IN_hallEffectErrorRR_bool */
  -1,                                  /* IN_hallEffectVHighFL_bool */
  -1,                                  /* IN_hallEffectVHighFR_bool */
  -1,                                  /* IN_hallEffectVHighRL_bool */
  -1,                                  /* IN_hallEffectVHighRR_bool */
  -1,                                  /* IN_hallEffectVLowFL_bool */
  -1,                                  /* IN_hallEffectVLowFR_bool */
  -1,                                  /* IN_hallEffectVLowRL_bool */
  -1,                                  /* IN_hallEffectVLowRR_bool */
  -1,                                  /* IN_rotorTempErrorFL_bool */
  -1,                                  /* IN_rotorTempErrorFR_bool */
  -1,                                  /* IN_rotorTempErrorRL_bool */
  -1,                                  /* IN_rotorTempErrorRR_bool */
  -1,                                  /* IN_rotorTempVHighFL_bool */
  -1,                                  /* IN_rotorTempVHighFR_bool */
  -1,                                  /* IN_rotorTempVHighRL_bool */
  -1,                                  /* IN_rotorTempVHighRR_bool */
  -1,                                  /* IN_rotorTempVLowFL_bool */
  -1,                                  /* IN_rotorTempVLowFR_bool */
  -1,                                  /* IN_rotorTempVLowRL_bool */
  -1,                                  /* IN_rotorTempVLowRR_bool */
  -1,                                  /* IN_throttleError1_bool */
  -1,                                  /* IN_throttleError2_bool */
  -1,                                  /* IN_throttleVHigh1_bool */
  -1,                                  /* IN_throttleVHigh2_bool */
  -1,                                  /* IN_throttleVLow1_bool */
  -1,                                  /* IN_throttleVLow2_bool */
  -1,                                  /* IN_tireTempErrorFLI_bool */
  -1,                                  /* IN_tireTempErrorFLM_bool */
  -1,                                  /* IN_tireTempErrorFLO_bool */
  -1,                                  /* IN_tireTempErrorFRI_bool */
  -1,                                  /* IN_tireTempErrorFRM_bool */
  -1,                                  /* IN_tireTempErrorFRO_bool */
  -1,                                  /* IN_tireTempErrorRLI_bool */
  -1,                                  /* IN_tireTempErrorRLM_bool */
  -1,                                  /* IN_tireTempErrorRLO_bool */
  -1,                                  /* IN_tireTempErrorRRI_bool */
  -1,                                  /* IN_tireTempErrorRRM_bool */
  -1,                                  /* IN_tireTempErrorRRO_bool */
  -1,                                  /* IN_tireTempVHighFLI_bool */
  -1,                                  /* IN_tireTempVHighFLM_bool */
  -1,                                  /* IN_tireTempVHighFLO_bool */
  -1,                                  /* IN_tireTempVHighFRI_bool */
  -1,                                  /* IN_tireTempVHighFRM_bool */
  -1,                                  /* IN_tireTempVHighFRO_bool */
  -1,                                  /* IN_tireTempVHighRLI_bool */
  -1,                                  /* IN_tireTempVHighRLM_bool */
  -1,                                  /* IN_tireTempVHighRLO_bool */
  -1,                                  /* IN_tireTempVHighRRI_bool */
  -1,                                  /* IN_tireTempVHighRRM_bool */
  -1,                                  /* IN_tireTempVHighRRO_bool */
  -1,                                  /* IN_tireTempVLowFLI_bool */
  -1,                                  /* IN_tireTempVLowFLM_bool */
  -1,                                  /* IN_tireTempVLowFLO_bool */
  -1,                                  /* IN_tireTempVLowFRI_bool */
  -1,                                  /* IN_tireTempVLowFRM_bool */
  -1,                                  /* IN_tireTempVLowFRO_bool */
  -1,                                  /* IN_tireTempVLowRLI_bool */
  -1,                                  /* IN_tireTempVLowRLM_bool */
  -1,                                  /* IN_tireTempVLowRLO_bool */
  -1,                                  /* IN_tireTempVLowRRI_bool */
  -1,                                  /* IN_tireTempVLowRRM_bool */
  -1,                                  /* IN_tireTempVLowRRO_bool */
};

void updateFaultInput(int16_T faultIdx, boolean_T inSample, uint32_T xLimit,
                      uint32_T yLimit, boolean_T sticky)
{
  boolean_T input;
  if ((faultIdx > 84) || (faultIdx < 1)) {
    return;
  }

  switch (getFaultOperation(faultIdx))
  {
   case FLTOP_FALSE:
    input = 0;
    break;

   case FLTOP_TRUE:
    input = 1;
    break;

   default:
    input = inSample;
  }

  setSuspectedState(faultIdx, input);
  if (input) {
    raptorFaultCounts_X_Data()[faultIdx-1]++;
  }

  raptorFaultCounts_Y_Data()[faultIdx-1]++;

  // After the window has expired, check to see if the x limit has been exceeded
  if (raptorFaultCounts_Y_Data()[faultIdx-1] >= yLimit) {
    if (raptorFaultCounts_X_Data()[faultIdx-1] < xLimit) {
      if (!sticky) {
        if (getFaultState(faultIdx, FAULT_ACTIVE)) {
          setOccurredState(faultIdx, 1);
        }

        setActiveState(faultIdx, 0);
      }

      setActiveAtShutdownState(faultIdx, 0);
    } else {
      setActiveState(faultIdx, 1);
      setActiveAtShutdownState(faultIdx, 1);
    }

    raptorFaultCounts_X_Data()[faultIdx-1] = 0;
    raptorFaultCounts_Y_Data()[faultIdx-1] = 0;
  } else if (raptorFaultCounts_X_Data()[faultIdx-1] >= xLimit) {
    // If X failures have occurred, finish the window early and report as active
    setActiveState(faultIdx, 1);
    setActiveAtShutdownState(faultIdx, 1);

    // Reset the window now that the active flag is set
    raptorFaultCounts_X_Data()[faultIdx-1] = 0;
    raptorFaultCounts_Y_Data()[faultIdx-1] = 0;
  }
}

void setActiveAtShutdownState(int16_T faultIdx, boolean_T nextValue)
{
  if ((faultIdx > 84) || (faultIdx < 1)) {
    return;
  }

  if (nextValue ) {
    raptorFaultNonVolatileBits_Data()[faultIdx-1] |= FAULT_ACTIVEATSHUTDOWN_MASK;
  } else {
    raptorFaultNonVolatileBits_Data()[faultIdx-1] &= (uint8_T)
      (~(FAULT_ACTIVEATSHUTDOWN_MASK));
  }
}

void setOccurredState(int16_T faultIdx, boolean_T nextValue)
{
  boolean_T curr_occurred_value, curr_notoccurred_value, occurred_changed,
    notoccurred_changed;
  if ((faultIdx > 84) || (faultIdx < 1)) {
    return;
  }

  curr_occurred_value = (boolean_T)((raptorFaultNonVolatileBits_Data()[faultIdx-
    1] & FAULT_OCCURRED_MASK) != 0);
  curr_notoccurred_value = (boolean_T)((raptorFaultNonVolatileBits_Data()
    [faultIdx-1] & FAULT_NOTOCCURRED_MASK) != 0);
  occurred_changed = (curr_occurred_value != nextValue);
  notoccurred_changed = (curr_notoccurred_value != (!nextValue));
  if (occurred_changed) {
    if (nextValue ) {
      raptorFaultNonVolatileBits_Data()[faultIdx-1] |= FAULT_OCCURRED_MASK;
    } else {
      raptorFaultNonVolatileBits_Data()[faultIdx-1] &= (uint8_T)
        (~(FAULT_OCCURRED_MASK));
    }
  }

  if (notoccurred_changed) {
    if (!nextValue ) {
      raptorFaultNonVolatileBits_Data()[faultIdx-1] |= FAULT_NOTOCCURRED_MASK;
    } else {
      raptorFaultNonVolatileBits_Data()[faultIdx-1] &= (uint8_T)
        (~(FAULT_NOTOCCURRED_MASK));
    }
  }
}

void setActiveState(int16_T faultIdx, boolean_T nextValue)
{
  boolean_T curr_value;
  if ((faultIdx > 84) || (faultIdx < 1)) {
    return;
  }

  curr_value = (boolean_T)((raptorFaultNonVolatileBits_Data()[faultIdx-1] &
    FAULT_ACTIVE_MASK) != 0);
  if (curr_value != nextValue) {
    if (nextValue ) {
      raptorFaultNonVolatileBits_Data()[faultIdx-1] |= FAULT_ACTIVE_MASK;
    } else {
      raptorFaultNonVolatileBits_Data()[faultIdx-1] &= (uint8_T)
        (~(FAULT_ACTIVE_MASK));
      setOccurredState(faultIdx, 1);
    }
  }
}

void setSuspectedState(int16_T faultIdx, boolean_T nextValue)
{
  boolean_T curr_value;
  if ((faultIdx > 84) || (faultIdx < 1)) {
    return;
  }

  curr_value = (boolean_T)((raptorFaultNonVolatileBits_Data()[faultIdx-1] &
    FAULT_SUSPECTED_MASK) != 0);
  if (curr_value != nextValue) {
    if (nextValue ) {
      raptorFaultNonVolatileBits_Data()[faultIdx-1] |= FAULT_SUSPECTED_MASK;
    } else {
      raptorFaultNonVolatileBits_Data()[faultIdx-1] &= (uint8_T)
        (~(FAULT_SUSPECTED_MASK));
    }
  }
}

void clearFault(int16_T faultIdx)
{
  if ((faultIdx > 84) || (faultIdx < 1)) {
    return;
  }

  setSuspectedState(faultIdx, 0);
  setActiveState(faultIdx, 0);
  setOccurredState(faultIdx, 0);
  setActiveAtShutdownState(faultIdx, 0);
  raptorFaultCounts_X_Data()[faultIdx-1] = 0;
  raptorFaultCounts_Y_Data()[faultIdx-1] = 0;
}

void clearFaults(void)
{
  int16_T faultIdx;
  for (faultIdx = 1; faultIdx <= 84; faultIdx++) {
    clearFault(faultIdx);
  }
}

boolean_T getFaultState(int16_T faultIdx, E_FaultState state)
{
  if ((faultIdx > 84) || (faultIdx < 1)) {
    return (boolean_T)0;
  }

  return (boolean_T)( (uint8_T)(raptorFaultNonVolatileBits_Data()[faultIdx-1] &
    state) != 0);
}

boolean_T getFaultSticky(int16_T faultIdx)
{
  FM_UNUSED(faultIdx);
  return 0;
}

boolean_T getFaultPersistent(int16_T faultIdx)
{
  FM_UNUSED(faultIdx);
  return 0;
}

E_FaultOperation getFaultOperation(int16_T faultIdx)
{
  if ((faultIdx > 84) || (faultIdx < 1)) {
    return FLTOP_NOTHING;
  }

  return raptorFaultOperation_Data()[faultIdx-1];
}

int16_T getNextFaultByState(E_FaultState state, boolean_T onlyEmissRelated,
  int16_T startIdx)
{
  int16_T faultIdx;
  int16_T nextIdx = startIdx;
  FM_UNUSED(onlyEmissRelated);
  if (nextIdx < 0)
    nextIdx = 0;
  nextIdx++;
  for (faultIdx = nextIdx; faultIdx <= 84; faultIdx++)
    if (getFaultState(faultIdx, state))
      return faultIdx;
  return 0;
}

int16_T getNextFault(int16_T startIdx)
{
  int16_T nextIdx = startIdx;
  if (nextIdx < 0)
    nextIdx = 0;
  nextIdx++;
  if (nextIdx > 84)
    return 0;
  else
    return nextIdx;
}

uint16_T getFaultStateCount(E_FaultState state)
{
  int16_T faultIdx = getNextFaultByState(state, 0, 0);
  uint16_T count = 0;
  while (faultIdx > 0) {
    count ++;
    faultIdx = getNextFaultByState(state, 0, faultIdx);
  }

  return count;
}

void initFaultManager()
{
  int16_T faultIdx;
  for (faultIdx = 1; faultIdx <= 84; faultIdx++) {
    if (getFaultState(faultIdx, FAULT_ACTIVEATSHUTDOWN)) {
      setOccurredState(faultIdx, 1);
    } else {
      setOccurredState(faultIdx, getFaultState(faultIdx, FAULT_OCCURRED));
    }

    setActiveAtShutdownState(faultIdx, 0);
    if (!getFaultPersistent(faultIdx))
      setActiveState(faultIdx, 0);
    setSuspectedState(faultIdx, 0);
  }
}
