/*********************************************************************************************
 *   This is an automatically generated file! D o  n o t   e d i t ! 
 *   
 *   The file is created by the DSM scripts based on the information given by the
 *   MSR modul definition files.
 *  
 *********************************************************************************************/
/* definition of event ids */
#ifndef DSM2AUTOSAR_DEM_INTEVTID_H
#define DSM2AUTOSAR_DEM_INTEVTID_H

/* One event id per DFC Element */
#define DemConf_DemEventParameter_DFC_Cy327SpiCom 1  /* Event Id for DFC_Cy327SpiCom;*/
#define DemConf_DemEventParameter_DFC_MonUMaxSupply1 2  /* Event Id for DFC_MonUMaxSupply1;*/
#define DemConf_DemEventParameter_DFC_MonUMinSupply1 3  /* Event Id for DFC_MonUMinSupply1;*/
#define DemConf_DemEventParameter_DFC_SSpMon1 4  /* Event Id for DFC_SSpMon1;*/
#define DemConf_DemEventParameter_DFC_SSpMon1OV 5  /* Event Id for DFC_SSpMon1OV;*/
#define DemConf_DemEventParameter_DFC_SSpMon1SCG 6  /* Event Id for DFC_SSpMon1SCG;*/
#define DemConf_DemEventParameter_DFC_SSpMon1UV 7  /* Event Id for DFC_SSpMon1UV;*/
#define DemConf_DemEventParameter_DFC_SSpMon2 8  /* Event Id for DFC_SSpMon2;*/
#define DemConf_DemEventParameter_DFC_SSpMon2OV 9  /* Event Id for DFC_SSpMon2OV;*/
#define DemConf_DemEventParameter_DFC_SSpMon2SCG 10  /* Event Id for DFC_SSpMon2SCG;*/
#define DemConf_DemEventParameter_DFC_SSpMon2UV 11  /* Event Id for DFC_SSpMon2UV;*/
#define DemConf_DemEventParameter_DFC_SSpMon3 12  /* Event Id for DFC_SSpMon3;*/
#define DemConf_DemEventParameter_DFC_SSpMon3OV 13  /* Event Id for DFC_SSpMon3OV;*/
#define DemConf_DemEventParameter_DFC_SSpMon3SCG 14  /* Event Id for DFC_SSpMon3SCG;*/
#define DemConf_DemEventParameter_DFC_SSpMon3UV 15  /* Event Id for DFC_SSpMon3UV;*/
#define DemConf_DemEventParameter_DFC_SSpMonOT 16  /* Event Id for DFC_SSpMonOT;*/
#define DemConf_DemEventParameter_DFC_IgnClPsClBenchErr1 4113  /* Event Id for DFC_IgnClPsClBenchErr1;*/
#define DemConf_DemEventParameter_DFC_IgnClPsClBenchErr2 4114  /* Event Id for DFC_IgnClPsClBenchErr2;*/
#define DemConf_DemEventParameter_DFC_IgnClPsDevIdentErr1 4115  /* Event Id for DFC_IgnClPsDevIdentErr1;*/
#define DemConf_DemEventParameter_DFC_IgnClPsDevIdentErr2 4116  /* Event Id for DFC_IgnClPsDevIdentErr2;*/
#define DemConf_DemEventParameter_DFC_IgnClPsDevInitErr1 4117  /* Event Id for DFC_IgnClPsDevInitErr1;*/
#define DemConf_DemEventParameter_DFC_IgnClPsDevInitErr2 4118  /* Event Id for DFC_IgnClPsDevInitErr2;*/
#define DemConf_DemEventParameter_DFC_IgnClPsDevSpiErr1 4119  /* Event Id for DFC_IgnClPsDevSpiErr1;*/
#define DemConf_DemEventParameter_DFC_IgnClPsDevSpiErr2 4120  /* Event Id for DFC_IgnClPsDevSpiErr2;*/
#define DemConf_DemEventParameter_DFC_IgnClPsOpenLoad0 4121  /* Event Id for DFC_IgnClPsOpenLoad0;*/
#define DemConf_DemEventParameter_DFC_IgnClPsOpenLoad1 4122  /* Event Id for DFC_IgnClPsOpenLoad1;*/
#define DemConf_DemEventParameter_DFC_IgnClPsOpenLoad2 4123  /* Event Id for DFC_IgnClPsOpenLoad2;*/
#define DemConf_DemEventParameter_DFC_IgnClPsOpenLoad3 4124  /* Event Id for DFC_IgnClPsOpenLoad3;*/
#define DemConf_DemEventParameter_DFC_IgnClPsOpenLoad4 4125  /* Event Id for DFC_IgnClPsOpenLoad4;*/
#define DemConf_DemEventParameter_DFC_IgnClPsOpenLoad5 4126  /* Event Id for DFC_IgnClPsOpenLoad5;*/
#define DemConf_DemEventParameter_DFC_IgnClPsOpenLoad6 4127  /* Event Id for DFC_IgnClPsOpenLoad6;*/
#define DemConf_DemEventParameter_DFC_IgnClPsOpenLoad7 4128  /* Event Id for DFC_IgnClPsOpenLoad7;*/
#define DemConf_DemEventParameter_DFC_IgnClPsShCirBatt0 4129  /* Event Id for DFC_IgnClPsShCirBatt0;*/
#define DemConf_DemEventParameter_DFC_IgnClPsShCirBatt1 4130  /* Event Id for DFC_IgnClPsShCirBatt1;*/
#define DemConf_DemEventParameter_DFC_IgnClPsShCirBatt2 4131  /* Event Id for DFC_IgnClPsShCirBatt2;*/
#define DemConf_DemEventParameter_DFC_IgnClPsShCirBatt3 4132  /* Event Id for DFC_IgnClPsShCirBatt3;*/
#define DemConf_DemEventParameter_DFC_IgnClPsShCirBatt4 4133  /* Event Id for DFC_IgnClPsShCirBatt4;*/
#define DemConf_DemEventParameter_DFC_IgnClPsShCirBatt5 4134  /* Event Id for DFC_IgnClPsShCirBatt5;*/
#define DemConf_DemEventParameter_DFC_IgnClPsShCirBatt6 4135  /* Event Id for DFC_IgnClPsShCirBatt6;*/
#define DemConf_DemEventParameter_DFC_IgnClPsShCirBatt7 4136  /* Event Id for DFC_IgnClPsShCirBatt7;*/
#define DemConf_DemEventParameter_DFC_IgnClPsShCirGnd0 4137  /* Event Id for DFC_IgnClPsShCirGnd0;*/
#define DemConf_DemEventParameter_DFC_IgnClPsShCirGnd1 4138  /* Event Id for DFC_IgnClPsShCirGnd1;*/
#define DemConf_DemEventParameter_DFC_IgnClPsShCirGnd2 4139  /* Event Id for DFC_IgnClPsShCirGnd2;*/
#define DemConf_DemEventParameter_DFC_IgnClPsShCirGnd3 4140  /* Event Id for DFC_IgnClPsShCirGnd3;*/
#define DemConf_DemEventParameter_DFC_IgnClPsShCirGnd4 4141  /* Event Id for DFC_IgnClPsShCirGnd4;*/
#define DemConf_DemEventParameter_DFC_IgnClPsShCirGnd5 4142  /* Event Id for DFC_IgnClPsShCirGnd5;*/
#define DemConf_DemEventParameter_DFC_IgnClPsShCirGnd6 4143  /* Event Id for DFC_IgnClPsShCirGnd6;*/
#define DemConf_DemEventParameter_DFC_IgnClPsShCirGnd7 4144  /* Event Id for DFC_IgnClPsShCirGnd7;*/
#define DemConf_DemEventParameter_DFC_UEGOASICS1B1 4145  /* Event Id for DFC_UEGOASICS1B1;*/
#define DemConf_DemEventParameter_DFC_UEGOASICS1B2 4146  /* Event Id for DFC_UEGOASICS1B2;*/
#define DemConf_DemEventParameter_DFC_UEGOOLAPES1B1 4147  /* Event Id for DFC_UEGOOLAPES1B1;*/
#define DemConf_DemEventParameter_DFC_UEGOOLAPES1B2 4148  /* Event Id for DFC_UEGOOLAPES1B2;*/
#define DemConf_DemEventParameter_DFC_UEGOOLIPES1B1 4149  /* Event Id for DFC_UEGOOLIPES1B1;*/
#define DemConf_DemEventParameter_DFC_UEGOOLIPES1B2 4150  /* Event Id for DFC_UEGOOLIPES1B2;*/
#define DemConf_DemEventParameter_DFC_UEGOOLMESS1B1 4151  /* Event Id for DFC_UEGOOLMESS1B1;*/
#define DemConf_DemEventParameter_DFC_UEGOOLMESS1B2 4152  /* Event Id for DFC_UEGOOLMESS1B2;*/
#define DemConf_DemEventParameter_DFC_UEGOOLRES1B1 4153  /* Event Id for DFC_UEGOOLRES1B1;*/
#define DemConf_DemEventParameter_DFC_UEGOOLRES1B2 4154  /* Event Id for DFC_UEGOOLRES1B2;*/
#define DemConf_DemEventParameter_DFC_UEGOSCBS1B1 4155  /* Event Id for DFC_UEGOSCBS1B1;*/
#define DemConf_DemEventParameter_DFC_UEGOSCBS1B2 4156  /* Event Id for DFC_UEGOSCBS1B2;*/
#define DemConf_DemEventParameter_DFC_UEGOSCGS1B1 4157  /* Event Id for DFC_UEGOSCGS1B1;*/
#define DemConf_DemEventParameter_DFC_UEGOSCGS1B2 4158  /* Event Id for DFC_UEGOSCGS1B2;*/
#define DemConf_DemEventParameter_DFC_UEGOSPIS1B1 4159  /* Event Id for DFC_UEGOSPIS1B1;*/
#define DemConf_DemEventParameter_DFC_UEGOSPIS1B2 4160  /* Event Id for DFC_UEGOSPIS1B2;*/
#define DemConf_DemEventParameter_DFC_UEGOSnsrS1B1 4161  /* Event Id for DFC_UEGOSnsrS1B1;*/
#define DemConf_DemEventParameter_DFC_UEGOSnsrS1B2 4162  /* Event Id for DFC_UEGOSnsrS1B2;*/
#define DemConf_DemEventParameter_DFC_UEGOSnsrTempS1B1 4163  /* Event Id for DFC_UEGOSnsrTempS1B1;*/
#define DemConf_DemEventParameter_DFC_UEGOSnsrTempS1B2 4164  /* Event Id for DFC_UEGOSnsrTempS1B2;*/
#define DemConf_DemEventParameter_DFC_DevLibBattUHi 8261  /* Event Id for DFC_DevLibBattUHi;*/
#define DemConf_DemEventParameter_DFC_DevLibBattULo 8262  /* Event Id for DFC_DevLibBattULo;*/
#define DemConf_DemEventParameter_DFC_MRlySCG 20551  /* Event Id for DFC_MRlySCG;*/
#define DemConf_DemEventParameter_DFC_KnDetSens1PortAMax 28744  /* Event Id for DFC_KnDetSens1PortAMax;*/
#define DemConf_DemEventParameter_DFC_KnDetSens1PortAMin 28745  /* Event Id for DFC_KnDetSens1PortAMin;*/
#define DemConf_DemEventParameter_DFC_KnDetSens1PortBMax 28746  /* Event Id for DFC_KnDetSens1PortBMax;*/
#define DemConf_DemEventParameter_DFC_KnDetSens1PortBMin 28747  /* Event Id for DFC_KnDetSens1PortBMin;*/
#define DemConf_DemEventParameter_DFC_KnDetSens2PortAMax 28748  /* Event Id for DFC_KnDetSens2PortAMax;*/
#define DemConf_DemEventParameter_DFC_KnDetSens2PortAMin 28749  /* Event Id for DFC_KnDetSens2PortAMin;*/
#define DemConf_DemEventParameter_DFC_KnDetSens2PortBMax 28750  /* Event Id for DFC_KnDetSens2PortBMax;*/
#define DemConf_DemEventParameter_DFC_KnDetSens2PortBMin 28751  /* Event Id for DFC_KnDetSens2PortBMin;*/
#define DemConf_DemEventParameter_DFC_KnDetSens3PortAMax 28752  /* Event Id for DFC_KnDetSens3PortAMax;*/
#define DemConf_DemEventParameter_DFC_KnDetSens3PortAMin 28753  /* Event Id for DFC_KnDetSens3PortAMin;*/
#define DemConf_DemEventParameter_DFC_KnDetSens3PortBMax 28754  /* Event Id for DFC_KnDetSens3PortBMax;*/
#define DemConf_DemEventParameter_DFC_KnDetSens3PortBMin 28755  /* Event Id for DFC_KnDetSens3PortBMin;*/
#define DemConf_DemEventParameter_DFC_KnDetSens4PortAMax 28756  /* Event Id for DFC_KnDetSens4PortAMax;*/
#define DemConf_DemEventParameter_DFC_KnDetSens4PortAMin 28757  /* Event Id for DFC_KnDetSens4PortAMin;*/
#define DemConf_DemEventParameter_DFC_KnDetSens4PortBMax 28758  /* Event Id for DFC_KnDetSens4PortBMax;*/
#define DemConf_DemEventParameter_DFC_KnDetSens4PortBMin 28759  /* Event Id for DFC_KnDetSens4PortBMin;*/
#define DemConf_DemEventParameter_DFC_BstCtlDumpVlvErrShtrp 32856  /* Event Id for DFC_BstCtlDumpVlvErrShtrp;*/
#define DemConf_DemEventParameter_DFC_BstCtlWgErrShtrp 32857  /* Event Id for DFC_BstCtlWgErrShtrp;*/
#define DemConf_DemEventParameter_DFC_CmprnTest 32858  /* Event Id for DFC_CmprnTest;*/
#define DemConf_DemEventParameter_DFC_DMTK 32859  /* Event Id for DFC_DMTK;*/
#define DemConf_DemEventParameter_DFC_DMTLmax 32860  /* Event Id for DFC_DMTLmax;*/
#define DemConf_DemEventParameter_DFC_DMTLmin 32861  /* Event Id for DFC_DMTLmin;*/
#define DemConf_DemEventParameter_DFC_DMTLnpl 32862  /* Event Id for DFC_DMTLnpl;*/
#define DemConf_DemEventParameter_DFC_DMTLsig 32863  /* Event Id for DFC_DMTLsig;*/
#define DemConf_DemEventParameter_DFC_LSV2max 32864  /* Event Id for DFC_LSV2max;*/
#define DemConf_DemEventParameter_DFC_LSVmax 32865  /* Event Id for DFC_LSVmax;*/
#define DemConf_DemEventParameter_DFC_MRlyErlyOpng 32866  /* Event Id for DFC_MRlyErlyOpng;*/
#define DemConf_DemEventParameter_DFC_MRlyStk 32867  /* Event Id for DFC_MRlyStk;*/
#define DemConf_DemEventParameter_DFC_SSpMon1loc 32868  /* Event Id for DFC_SSpMon1loc;*/
#define DemConf_DemEventParameter_DFC_SSpMon2loc 32869  /* Event Id for DFC_SSpMon2loc;*/
#define DemConf_DemEventParameter_DFC_SSpMon3loc 32870  /* Event Id for DFC_SSpMon3loc;*/
#define DemConf_DemEventParameter_DFC_TESG 32871  /* Event Id for DFC_TESG;*/
#define DemConf_DemEventParameter_DFC_TESmax 32872  /* Event Id for DFC_TESmax;*/
#define DemConf_DemEventParameter_DFC_TESmin 32873  /* Event Id for DFC_TESmin;*/
#define DemConf_DemEventParameter_DFC_VehVMax 32874  /* Event Id for DFC_VehVMax;*/
#define DemConf_DemEventParameter_DFC_VehVPlaus 32875  /* Event Id for DFC_VehVPlaus;*/
#define DemConf_DemEventParameter_DFC_VehVSig 32876  /* Event Id for DFC_VehVSig;*/
#define DemConf_DemEventParameter_DFC_EEPRdErr 32877  /* Event Id for DFC_EEPRdErr;*/
#define DemConf_DemEventParameter_DFC_EEPWrErr 32878  /* Event Id for DFC_EEPWrErr;*/
#define DemConf_DemEventParameter_DFC_EV1max 32879  /* Event Id for DFC_EV1max;*/
#define DemConf_DemEventParameter_DFC_EV1min 32880  /* Event Id for DFC_EV1min;*/
#define DemConf_DemEventParameter_DFC_EV1sig 32881  /* Event Id for DFC_EV1sig;*/
#define DemConf_DemEventParameter_DFC_EV2max 32882  /* Event Id for DFC_EV2max;*/
#define DemConf_DemEventParameter_DFC_EV2min 32883  /* Event Id for DFC_EV2min;*/
#define DemConf_DemEventParameter_DFC_EV2sig 32884  /* Event Id for DFC_EV2sig;*/
#define DemConf_DemEventParameter_DFC_EV3max 32885  /* Event Id for DFC_EV3max;*/
#define DemConf_DemEventParameter_DFC_EV3min 32886  /* Event Id for DFC_EV3min;*/
#define DemConf_DemEventParameter_DFC_EV3sig 32887  /* Event Id for DFC_EV3sig;*/
#define DemConf_DemEventParameter_DFC_EV4max 32888  /* Event Id for DFC_EV4max;*/
#define DemConf_DemEventParameter_DFC_EV4min 32889  /* Event Id for DFC_EV4min;*/
#define DemConf_DemEventParameter_DFC_EV4sig 32890  /* Event Id for DFC_EV4sig;*/
#define DemConf_DemEventParameter_DFC_EV5max 32891  /* Event Id for DFC_EV5max;*/
#define DemConf_DemEventParameter_DFC_EV5min 32892  /* Event Id for DFC_EV5min;*/
#define DemConf_DemEventParameter_DFC_EV5sig 32893  /* Event Id for DFC_EV5sig;*/
#define DemConf_DemEventParameter_DFC_EV6max 32894  /* Event Id for DFC_EV6max;*/
#define DemConf_DemEventParameter_DFC_EV6min 32895  /* Event Id for DFC_EV6min;*/
#define DemConf_DemEventParameter_DFC_EV6sig 32896  /* Event Id for DFC_EV6sig;*/
#define DemConf_DemEventParameter_DFC_EV7max 32897  /* Event Id for DFC_EV7max;*/
#define DemConf_DemEventParameter_DFC_EV7min 32898  /* Event Id for DFC_EV7min;*/
#define DemConf_DemEventParameter_DFC_EV7sig 32899  /* Event Id for DFC_EV7sig;*/
#define DemConf_DemEventParameter_DFC_EV8max 32900  /* Event Id for DFC_EV8max;*/
#define DemConf_DemEventParameter_DFC_EV8min 32901  /* Event Id for DFC_EV8min;*/
#define DemConf_DemEventParameter_DFC_EV8sig 32902  /* Event Id for DFC_EV8sig;*/
#define DemConf_DemEventParameter_DFC_EpmCaSI1ErrSig 32903  /* Event Id for DFC_EpmCaSI1ErrSig;*/
#define DemConf_DemEventParameter_DFC_EpmCaSI1MntErr 32904  /* Event Id for DFC_EpmCaSI1MntErr;*/
#define DemConf_DemEventParameter_DFC_EpmCaSI1NoSigMax 32905  /* Event Id for DFC_EpmCaSI1NoSigMax;*/
#define DemConf_DemEventParameter_DFC_EpmCaSI1NoSigMin 32906  /* Event Id for DFC_EpmCaSI1NoSigMin;*/
#define DemConf_DemEventParameter_DFC_EpmCaSI1OfsErr 32907  /* Event Id for DFC_EpmCaSI1OfsErr;*/
#define DemConf_DemEventParameter_DFC_EpmCrSDGI 32908  /* Event Id for DFC_EpmCrSDGI;*/
#define DemConf_DemEventParameter_DFC_EpmCrSErrSig 32909  /* Event Id for DFC_EpmCrSErrSig;*/
#define DemConf_DemEventParameter_DFC_EpmCrSNoSig 32910  /* Event Id for DFC_EpmCrSNoSig;*/
#define DemConf_DemEventParameter_DFC_MoCADCNTP 32911  /* Event Id for DFC_MoCADCNTP;*/
#define DemConf_DemEventParameter_DFC_MoCADCTst 32912  /* Event Id for DFC_MoCADCTst;*/
#define DemConf_DemEventParameter_DFC_MoCComctErrMM 32913  /* Event Id for DFC_MoCComctErrMM;*/
#define DemConf_DemEventParameter_DFC_OCWDAActv 32914  /* Event Id for DFC_OCWDAActv;*/
#define DemConf_DemEventParameter_DFC_OCWDACom 32915  /* Event Id for DFC_OCWDACom;*/
#define DemConf_DemEventParameter_DFC_OCWDAOvrVltg 32916  /* Event Id for DFC_OCWDAOvrVltg;*/
#define DemConf_DemEventParameter_DFC_SWReset_0 32917  /* Event Id for DFC_SWReset_0;*/
#define DemConf_DemEventParameter_DFC_SWReset_1 32918  /* Event Id for DFC_SWReset_1;*/
#define DemConf_DemEventParameter_DFC_SWReset_2 32919  /* Event Id for DFC_SWReset_2;*/
#define DemConf_DemEventParameter_DFC_StopCntTmr 32920  /* Event Id for DFC_StopCntTmr;*/

#endif

