/********************************************************************************
FILE:         esc_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _ESC_MSG_H
#define _ESC_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __EPMCRS_TISEG_EXT__
#define __EPMCRS_TISEG_EXT__
extern sint32 EpmCrS_tiSeg;
#endif /* __EPMCRS_TISEG_EXT__ */

#ifndef __EPMCRS_TISEGCURR_EXT__
#define __EPMCRS_TISEGCURR_EXT__
extern sint32 EpmCrS_tiSegCurr;
#endif /* __EPMCRS_TISEGCURR_EXT__ */

#ifndef __SYC_TIDRV_EXT__
#define __SYC_TIDRV_EXT__
extern uint32 SyC_tiDrv;
#endif /* __SYC_TIDRV_EXT__ */

#ifndef __EPMSEQ_NUMINT_EXT__
#define __EPMSEQ_NUMINT_EXT__
extern uint8                    EpmSeq_numInt;
#endif /* __EPMSEQ_NUMINT_EXT__ */

#ifndef __SYC_STSUB_EXT__
#define __SYC_STSUB_EXT__
extern uint8                    SyC_stSub;
#endif /* __SYC_STSUB_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_EpmSeq_numInt 
#define SET_EpmSeq_numInt (EpmSeq_numInt=TRUE)
#endif
#ifndef CLR_EpmSeq_numInt 
#define CLR_EpmSeq_numInt (EpmSeq_numInt=FALSE)
#endif
#ifndef GET_EpmSeq_numInt 
#define GET_EpmSeq_numInt (EpmSeq_numInt)
#endif
#ifndef PUT_EpmSeq_numInt 
#define PUT_EpmSeq_numInt(val) ((val) ? SET_EpmSeq_numInt : CLR_EpmSeq_numInt)
#endif


#ifndef SET_SyC_stSub 
#define SET_SyC_stSub (SyC_stSub=TRUE)
#endif
#ifndef CLR_SyC_stSub 
#define CLR_SyC_stSub (SyC_stSub=FALSE)
#endif
#ifndef GET_SyC_stSub 
#define GET_SyC_stSub (SyC_stSub)
#endif
#ifndef PUT_SyC_stSub 
#define PUT_SyC_stSub(val) ((val) ? SET_SyC_stSub : CLR_SyC_stSub)
#endif

#endif
