/********************************************************************************
FILE:         execon_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _EXECON_MSG_H
#define _EXECON_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __SYC_TIDRV_EXT__
#define __SYC_TIDRV_EXT__
extern uint32 SyC_tiDrv;
#endif /* __SYC_TIDRV_EXT__ */

#ifndef __SYC_TIPOSTDRV_EXT__
#define __SYC_TIPOSTDRV_EXT__
extern uint32 SyC_tiPostDrv;
#endif /* __SYC_TIPOSTDRV_EXT__ */

#ifndef __SYC_TIPREDRV_EXT__
#define __SYC_TIPREDRV_EXT__
extern uint32 SyC_tiPreDrv;
#endif /* __SYC_TIPREDRV_EXT__ */

#ifndef __SYC_TIFRST10MS_EXT__
#define __SYC_TIFRST10MS_EXT__
extern uint16 SyC_tiFrst10ms;
#endif /* __SYC_TIFRST10MS_EXT__ */

#ifndef __SYC_CTIRRSWOFF_EXT__
#define __SYC_CTIRRSWOFF_EXT__
extern uint8                    SyC_ctIrrSwOff;
#endif /* __SYC_CTIRRSWOFF_EXT__ */

#ifndef __SYC_STMN_EXT__
#define __SYC_STMN_EXT__
extern uint8                    SyC_stMn;
#endif /* __SYC_STMN_EXT__ */

#ifndef __SYC_STMNOLD_EXT__
#define __SYC_STMNOLD_EXT__
extern uint8                    SyC_stMnOld;
#endif /* __SYC_STMNOLD_EXT__ */

#ifndef __SYC_STPOSTDRV_EXT__
#define __SYC_STPOSTDRV_EXT__
extern uint8                    SyC_stPostDrv;
#endif /* __SYC_STPOSTDRV_EXT__ */

#ifndef __SYC_STPREDRV_EXT__
#define __SYC_STPREDRV_EXT__
extern uint8                    SyC_stPreDrv;
#endif /* __SYC_STPREDRV_EXT__ */

#ifndef __SYC_STSUB_EXT__
#define __SYC_STSUB_EXT__
extern uint8                    SyC_stSub;
#endif /* __SYC_STSUB_EXT__ */

#ifndef __SYC_STSUBOLD_EXT__
#define __SYC_STSUBOLD_EXT__
extern uint8                    SyC_stSubOld;
#endif /* __SYC_STSUBOLD_EXT__ */

#ifndef __SYC_STT15_EXT__
#define __SYC_STT15_EXT__
extern bool                     SyC_stT15;
#endif /* __SYC_STT15_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_SyC_ctIrrSwOff 
#define SET_SyC_ctIrrSwOff (SyC_ctIrrSwOff=TRUE)
#endif
#ifndef CLR_SyC_ctIrrSwOff 
#define CLR_SyC_ctIrrSwOff (SyC_ctIrrSwOff=FALSE)
#endif
#ifndef GET_SyC_ctIrrSwOff 
#define GET_SyC_ctIrrSwOff (SyC_ctIrrSwOff)
#endif
#ifndef PUT_SyC_ctIrrSwOff 
#define PUT_SyC_ctIrrSwOff(val) ((val) ? SET_SyC_ctIrrSwOff : CLR_SyC_ctIrrSwOff)
#endif


#ifndef SET_SyC_stMn 
#define SET_SyC_stMn (SyC_stMn=TRUE)
#endif
#ifndef CLR_SyC_stMn 
#define CLR_SyC_stMn (SyC_stMn=FALSE)
#endif
#ifndef GET_SyC_stMn 
#define GET_SyC_stMn (SyC_stMn)
#endif
#ifndef PUT_SyC_stMn 
#define PUT_SyC_stMn(val) ((val) ? SET_SyC_stMn : CLR_SyC_stMn)
#endif


#ifndef SET_SyC_stMnOld 
#define SET_SyC_stMnOld (SyC_stMnOld=TRUE)
#endif
#ifndef CLR_SyC_stMnOld 
#define CLR_SyC_stMnOld (SyC_stMnOld=FALSE)
#endif
#ifndef GET_SyC_stMnOld 
#define GET_SyC_stMnOld (SyC_stMnOld)
#endif
#ifndef PUT_SyC_stMnOld 
#define PUT_SyC_stMnOld(val) ((val) ? SET_SyC_stMnOld : CLR_SyC_stMnOld)
#endif


#ifndef SET_SyC_stPostDrv 
#define SET_SyC_stPostDrv (SyC_stPostDrv=TRUE)
#endif
#ifndef CLR_SyC_stPostDrv 
#define CLR_SyC_stPostDrv (SyC_stPostDrv=FALSE)
#endif
#ifndef GET_SyC_stPostDrv 
#define GET_SyC_stPostDrv (SyC_stPostDrv)
#endif
#ifndef PUT_SyC_stPostDrv 
#define PUT_SyC_stPostDrv(val) ((val) ? SET_SyC_stPostDrv : CLR_SyC_stPostDrv)
#endif


#ifndef SET_SyC_stPreDrv 
#define SET_SyC_stPreDrv (SyC_stPreDrv=TRUE)
#endif
#ifndef CLR_SyC_stPreDrv 
#define CLR_SyC_stPreDrv (SyC_stPreDrv=FALSE)
#endif
#ifndef GET_SyC_stPreDrv 
#define GET_SyC_stPreDrv (SyC_stPreDrv)
#endif
#ifndef PUT_SyC_stPreDrv 
#define PUT_SyC_stPreDrv(val) ((val) ? SET_SyC_stPreDrv : CLR_SyC_stPreDrv)
#endif


#ifndef SET_SyC_stSub 
#define SET_SyC_stSub (SyC_stSub=TRUE)
#endif
#ifndef CLR_SyC_stSub 
#define CLR_SyC_stSub (SyC_stSub=FALSE)
#endif
#ifndef GET_SyC_stSub 
#define GET_SyC_stSub (SyC_stSub)
#endif
#ifndef PUT_SyC_stSub 
#define PUT_SyC_stSub(val) ((val) ? SET_SyC_stSub : CLR_SyC_stSub)
#endif


#ifndef SET_SyC_stSubOld 
#define SET_SyC_stSubOld (SyC_stSubOld=TRUE)
#endif
#ifndef CLR_SyC_stSubOld 
#define CLR_SyC_stSubOld (SyC_stSubOld=FALSE)
#endif
#ifndef GET_SyC_stSubOld 
#define GET_SyC_stSubOld (SyC_stSubOld)
#endif
#ifndef PUT_SyC_stSubOld 
#define PUT_SyC_stSubOld(val) ((val) ? SET_SyC_stSubOld : CLR_SyC_stSubOld)
#endif


#ifndef SET_SyC_stT15 
#define SET_SyC_stT15 (SyC_stT15=TRUE)
#endif
#ifndef CLR_SyC_stT15 
#define CLR_SyC_stT15 (SyC_stT15=FALSE)
#endif
#ifndef GET_SyC_stT15 
#define GET_SyC_stT15 (SyC_stT15)
#endif
#ifndef PUT_SyC_stT15 
#define PUT_SyC_stT15(val) ((val) ? SET_SyC_stT15 : CLR_SyC_stT15)
#endif

#endif
