/********************************************************************************
FILE:         ocwda_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _OCWDA_MSG_H
#define _OCWDA_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __OCWDA_STCHECKSTATE_EXT__
#define __OCWDA_STCHECKSTATE_EXT__
extern uint32 OCWDA_stCheckState;
#endif /* __OCWDA_STCHECKSTATE_EXT__ */

#ifndef __OCWDA_STWDAPTT_EXT__
#define __OCWDA_STWDAPTT_EXT__
extern uint32 OCWDA_stWDAPtt;
#endif /* __OCWDA_STWDAPTT_EXT__ */

#ifndef __OCWDA_CTDEBOVRVLTGON_EXT__
#define __OCWDA_CTDEBOVRVLTGON_EXT__
extern uint16 OCWDA_ctDebOvrVltgOn;
#endif /* __OCWDA_CTDEBOVRVLTGON_EXT__ */

#ifndef __OCWDA_CTTSTCOMERR_EXT__
#define __OCWDA_CTTSTCOMERR_EXT__
extern uint16 OCWDA_ctTstComErr;
#endif /* __OCWDA_CTTSTCOMERR_EXT__ */

#ifndef __OCWDA_CTTSTOVRVLTG_EXT__
#define __OCWDA_CTTSTOVRVLTG_EXT__
extern uint16 OCWDA_ctTstOvrVltg;
#endif /* __OCWDA_CTTSTOVRVLTG_EXT__ */

#ifndef __MOCSOP_STACTMSG_EXT__
#define __MOCSOP_STACTMSG_EXT__
extern uint8 MoCSOP_stActMsg;
#endif /* __MOCSOP_STACTMSG_EXT__ */

#ifndef __MOCSOP_STOVL_EXT__
#define __MOCSOP_STOVL_EXT__
extern uint8 MoCSOP_stOvl;
#endif /* __MOCSOP_STOVL_EXT__ */

#ifndef __OCWDA_BWDAACTV_EXT__
#define __OCWDA_BWDAACTV_EXT__
extern uint8                    OCWDA_bWDAActv;
#endif /* __OCWDA_BWDAACTV_EXT__ */

#ifndef __OCWDA_CTDEBLOWVLTGON_EXT__
#define __OCWDA_CTDEBLOWVLTGON_EXT__
extern uint8                    OCWDA_ctDebLowVltgOn;
#endif /* __OCWDA_CTDEBLOWVLTGON_EXT__ */

#ifndef __OCWDA_CTDEBSOPNOTACTV_EXT__
#define __OCWDA_CTDEBSOPNOTACTV_EXT__
extern uint8                    OCWDA_ctDebSOPNotActv;
#endif /* __OCWDA_CTDEBSOPNOTACTV_EXT__ */

#ifndef __OCWDA_CTDEBWDAACTV_EXT__
#define __OCWDA_CTDEBWDAACTV_EXT__
extern uint8                    OCWDA_ctDebWDAActv;
#endif /* __OCWDA_CTDEBWDAACTV_EXT__ */

#ifndef __OCWDA_CTDEBWDANOTACTV_EXT__
#define __OCWDA_CTDEBWDANOTACTV_EXT__
extern uint8                    OCWDA_ctDebWDANotActv;
#endif /* __OCWDA_CTDEBWDANOTACTV_EXT__ */

#ifndef __OCWDA_CTTSTOCWDA_EXT__
#define __OCWDA_CTTSTOCWDA_EXT__
extern uint8                    OCWDA_ctTstOCWDA;
#endif /* __OCWDA_CTTSTOCWDA_EXT__ */

#ifndef __OCWDA_CTTSTWDAACTV_EXT__
#define __OCWDA_CTTSTWDAACTV_EXT__
extern uint8                    OCWDA_ctTstWDAActv;
#endif /* __OCWDA_CTTSTWDAACTV_EXT__ */

#ifndef __OCWDA_CTUBSQ_EXT__
#define __OCWDA_CTUBSQ_EXT__
extern uint8                    OCWDA_ctUbsq;
#endif /* __OCWDA_CTUBSQ_EXT__ */

#ifndef __OCWDA_ST_EXT__
#define __OCWDA_ST_EXT__
extern uint8                    OCWDA_st;
#endif /* __OCWDA_ST_EXT__ */

#ifndef __SYC_STSUB_EXT__
#define __SYC_STSUB_EXT__
extern uint8                    SyC_stSub;
#endif /* __SYC_STSUB_EXT__ */

#ifndef __MOCCOM_STWDAACTVMSG_EXT__
#define __MOCCOM_STWDAACTVMSG_EXT__
extern bool                     MoCCom_stWDAActvMsg;
#endif /* __MOCCOM_STWDAACTVMSG_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_OCWDA_bWDAActv 
#define SET_OCWDA_bWDAActv (OCWDA_bWDAActv=TRUE)
#endif
#ifndef CLR_OCWDA_bWDAActv 
#define CLR_OCWDA_bWDAActv (OCWDA_bWDAActv=FALSE)
#endif
#ifndef GET_OCWDA_bWDAActv 
#define GET_OCWDA_bWDAActv (OCWDA_bWDAActv)
#endif
#ifndef PUT_OCWDA_bWDAActv 
#define PUT_OCWDA_bWDAActv(val) ((val) ? SET_OCWDA_bWDAActv : CLR_OCWDA_bWDAActv)
#endif


#ifndef SET_OCWDA_ctDebLowVltgOn 
#define SET_OCWDA_ctDebLowVltgOn (OCWDA_ctDebLowVltgOn=TRUE)
#endif
#ifndef CLR_OCWDA_ctDebLowVltgOn 
#define CLR_OCWDA_ctDebLowVltgOn (OCWDA_ctDebLowVltgOn=FALSE)
#endif
#ifndef GET_OCWDA_ctDebLowVltgOn 
#define GET_OCWDA_ctDebLowVltgOn (OCWDA_ctDebLowVltgOn)
#endif
#ifndef PUT_OCWDA_ctDebLowVltgOn 
#define PUT_OCWDA_ctDebLowVltgOn(val) ((val) ? SET_OCWDA_ctDebLowVltgOn : CLR_OCWDA_ctDebLowVltgOn)
#endif


#ifndef SET_OCWDA_ctDebSOPNotActv 
#define SET_OCWDA_ctDebSOPNotActv (OCWDA_ctDebSOPNotActv=TRUE)
#endif
#ifndef CLR_OCWDA_ctDebSOPNotActv 
#define CLR_OCWDA_ctDebSOPNotActv (OCWDA_ctDebSOPNotActv=FALSE)
#endif
#ifndef GET_OCWDA_ctDebSOPNotActv 
#define GET_OCWDA_ctDebSOPNotActv (OCWDA_ctDebSOPNotActv)
#endif
#ifndef PUT_OCWDA_ctDebSOPNotActv 
#define PUT_OCWDA_ctDebSOPNotActv(val) ((val) ? SET_OCWDA_ctDebSOPNotActv : CLR_OCWDA_ctDebSOPNotActv)
#endif


#ifndef SET_OCWDA_ctDebWDAActv 
#define SET_OCWDA_ctDebWDAActv (OCWDA_ctDebWDAActv=TRUE)
#endif
#ifndef CLR_OCWDA_ctDebWDAActv 
#define CLR_OCWDA_ctDebWDAActv (OCWDA_ctDebWDAActv=FALSE)
#endif
#ifndef GET_OCWDA_ctDebWDAActv 
#define GET_OCWDA_ctDebWDAActv (OCWDA_ctDebWDAActv)
#endif
#ifndef PUT_OCWDA_ctDebWDAActv 
#define PUT_OCWDA_ctDebWDAActv(val) ((val) ? SET_OCWDA_ctDebWDAActv : CLR_OCWDA_ctDebWDAActv)
#endif


#ifndef SET_OCWDA_ctDebWDANotActv 
#define SET_OCWDA_ctDebWDANotActv (OCWDA_ctDebWDANotActv=TRUE)
#endif
#ifndef CLR_OCWDA_ctDebWDANotActv 
#define CLR_OCWDA_ctDebWDANotActv (OCWDA_ctDebWDANotActv=FALSE)
#endif
#ifndef GET_OCWDA_ctDebWDANotActv 
#define GET_OCWDA_ctDebWDANotActv (OCWDA_ctDebWDANotActv)
#endif
#ifndef PUT_OCWDA_ctDebWDANotActv 
#define PUT_OCWDA_ctDebWDANotActv(val) ((val) ? SET_OCWDA_ctDebWDANotActv : CLR_OCWDA_ctDebWDANotActv)
#endif


#ifndef SET_OCWDA_ctTstOCWDA 
#define SET_OCWDA_ctTstOCWDA (OCWDA_ctTstOCWDA=TRUE)
#endif
#ifndef CLR_OCWDA_ctTstOCWDA 
#define CLR_OCWDA_ctTstOCWDA (OCWDA_ctTstOCWDA=FALSE)
#endif
#ifndef GET_OCWDA_ctTstOCWDA 
#define GET_OCWDA_ctTstOCWDA (OCWDA_ctTstOCWDA)
#endif
#ifndef PUT_OCWDA_ctTstOCWDA 
#define PUT_OCWDA_ctTstOCWDA(val) ((val) ? SET_OCWDA_ctTstOCWDA : CLR_OCWDA_ctTstOCWDA)
#endif


#ifndef SET_OCWDA_ctTstWDAActv 
#define SET_OCWDA_ctTstWDAActv (OCWDA_ctTstWDAActv=TRUE)
#endif
#ifndef CLR_OCWDA_ctTstWDAActv 
#define CLR_OCWDA_ctTstWDAActv (OCWDA_ctTstWDAActv=FALSE)
#endif
#ifndef GET_OCWDA_ctTstWDAActv 
#define GET_OCWDA_ctTstWDAActv (OCWDA_ctTstWDAActv)
#endif
#ifndef PUT_OCWDA_ctTstWDAActv 
#define PUT_OCWDA_ctTstWDAActv(val) ((val) ? SET_OCWDA_ctTstWDAActv : CLR_OCWDA_ctTstWDAActv)
#endif


#ifndef SET_OCWDA_ctUbsq 
#define SET_OCWDA_ctUbsq (OCWDA_ctUbsq=TRUE)
#endif
#ifndef CLR_OCWDA_ctUbsq 
#define CLR_OCWDA_ctUbsq (OCWDA_ctUbsq=FALSE)
#endif
#ifndef GET_OCWDA_ctUbsq 
#define GET_OCWDA_ctUbsq (OCWDA_ctUbsq)
#endif
#ifndef PUT_OCWDA_ctUbsq 
#define PUT_OCWDA_ctUbsq(val) ((val) ? SET_OCWDA_ctUbsq : CLR_OCWDA_ctUbsq)
#endif


#ifndef SET_OCWDA_st 
#define SET_OCWDA_st (OCWDA_st=TRUE)
#endif
#ifndef CLR_OCWDA_st 
#define CLR_OCWDA_st (OCWDA_st=FALSE)
#endif
#ifndef GET_OCWDA_st 
#define GET_OCWDA_st (OCWDA_st)
#endif
#ifndef PUT_OCWDA_st 
#define PUT_OCWDA_st(val) ((val) ? SET_OCWDA_st : CLR_OCWDA_st)
#endif


#ifndef SET_SyC_stSub 
#define SET_SyC_stSub (SyC_stSub=TRUE)
#endif
#ifndef CLR_SyC_stSub 
#define CLR_SyC_stSub (SyC_stSub=FALSE)
#endif
#ifndef GET_SyC_stSub 
#define GET_SyC_stSub (SyC_stSub)
#endif
#ifndef PUT_SyC_stSub 
#define PUT_SyC_stSub(val) ((val) ? SET_SyC_stSub : CLR_SyC_stSub)
#endif


#ifndef SET_MoCCom_stWDAActvMsg 
#define SET_MoCCom_stWDAActvMsg (MoCCom_stWDAActvMsg=TRUE)
#endif
#ifndef CLR_MoCCom_stWDAActvMsg 
#define CLR_MoCCom_stWDAActvMsg (MoCCom_stWDAActvMsg=FALSE)
#endif
#ifndef GET_MoCCom_stWDAActvMsg 
#define GET_MoCCom_stWDAActvMsg (MoCCom_stWDAActvMsg)
#endif
#ifndef PUT_MoCCom_stWDAActvMsg 
#define PUT_MoCCom_stWDAActvMsg(val) ((val) ? SET_MoCCom_stWDAActvMsg : CLR_MoCCom_stWDAActvMsg)
#endif

#endif
