/********************************************************************************
FILE:         syc_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _SYC_MSG_H
#define _SYC_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __SYC_TIECUOFF_EXT__
#define __SYC_TIECUOFF_EXT__
extern sint32 SyC_tiEcuOff;
#endif /* __SYC_TIECUOFF_EXT__ */

#ifndef __SYC_TIDRV_EXT__
#define __SYC_TIDRV_EXT__
extern uint32 SyC_tiDrv;
#endif /* __SYC_TIDRV_EXT__ */

#ifndef __SYC_TIPOSTDRV_EXT__
#define __SYC_TIPOSTDRV_EXT__
extern uint32 SyC_tiPostDrv;
#endif /* __SYC_TIPOSTDRV_EXT__ */

#ifndef __SYC_TIPREDRV_EXT__
#define __SYC_TIPREDRV_EXT__
extern uint32 SyC_tiPreDrv;
#endif /* __SYC_TIPREDRV_EXT__ */

#ifndef __EPM_NENG_EXT__
#define __EPM_NENG_EXT__
extern sint16 Epm_nEng;
#endif /* __EPM_NENG_EXT__ */

#ifndef __MRLY_STACT_EXT__
#define __MRLY_STACT_EXT__
extern uint16 MRly_stAct;
#endif /* __MRLY_STACT_EXT__ */

#ifndef __SYC_TIFRST10MS_EXT__
#define __SYC_TIFRST10MS_EXT__
extern uint16 SyC_tiFrst10ms;
#endif /* __SYC_TIFRST10MS_EXT__ */

#ifndef __MOCCOM_CTERRMMMSG_EXT__
#define __MOCCOM_CTERRMMMSG_EXT__
extern uint8 MoCCom_ctErrMMMsg;
#endif /* __MOCCOM_CTERRMMMSG_EXT__ */

#ifndef __MO_STIRVERRREACMSG_EXT__
#define __MO_STIRVERRREACMSG_EXT__
extern uint8 Mo_stIrvErrReacMsg;
#endif /* __MO_STIRVERRREACMSG_EXT__ */

#ifndef __SYC_CTIRRSWOFF_EXT__
#define __SYC_CTIRRSWOFF_EXT__
extern uint8                    SyC_ctIrrSwOff;
#endif /* __SYC_CTIRRSWOFF_EXT__ */

#ifndef __SYC_STMN_EXT__
#define __SYC_STMN_EXT__
extern uint8                    SyC_stMn;
#endif /* __SYC_STMN_EXT__ */

#ifndef __SYC_STMNOLD_EXT__
#define __SYC_STMNOLD_EXT__
extern uint8                    SyC_stMnOld;
#endif /* __SYC_STMNOLD_EXT__ */

#ifndef __SYC_STPOSTDRV_EXT__
#define __SYC_STPOSTDRV_EXT__
extern uint8                    SyC_stPostDrv;
#endif /* __SYC_STPOSTDRV_EXT__ */

#ifndef __SYC_STPREDRV_EXT__
#define __SYC_STPREDRV_EXT__
extern uint8                    SyC_stPreDrv;
#endif /* __SYC_STPREDRV_EXT__ */

#ifndef __SYC_STSUB_EXT__
#define __SYC_STSUB_EXT__
extern uint8                    SyC_stSub;
#endif /* __SYC_STSUB_EXT__ */

#ifndef __SYC_STSUBOLD_EXT__
#define __SYC_STSUBOLD_EXT__
extern uint8                    SyC_stSubOld;
#endif /* __SYC_STSUBOLD_EXT__ */

#ifndef __MRLY_ST_EXT__
#define __MRLY_ST_EXT__
extern bool                     MRly_st;
#endif /* __MRLY_ST_EXT__ */

#ifndef __MOCCOM_STWDAACTVMSG_EXT__
#define __MOCCOM_STWDAACTVMSG_EXT__
extern bool                     MoCCom_stWDAActvMsg;
#endif /* __MOCCOM_STWDAACTVMSG_EXT__ */

#ifndef __SYC_STT15_EXT__
#define __SYC_STT15_EXT__
extern bool                     SyC_stT15;
#endif /* __SYC_STT15_EXT__ */

#ifndef __SYC_STVLDTIECUOFF_EXT__
#define __SYC_STVLDTIECUOFF_EXT__
extern bool                     SyC_stVldTiEcuOff;
#endif /* __SYC_STVLDTIECUOFF_EXT__ */

#ifndef __T15_ST_EXT__
#define __T15_ST_EXT__
extern bool                     T15_st;
#endif /* __T15_ST_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_SyC_ctIrrSwOff 
#define SET_SyC_ctIrrSwOff (SyC_ctIrrSwOff=TRUE)
#endif
#ifndef CLR_SyC_ctIrrSwOff 
#define CLR_SyC_ctIrrSwOff (SyC_ctIrrSwOff=FALSE)
#endif
#ifndef GET_SyC_ctIrrSwOff 
#define GET_SyC_ctIrrSwOff (SyC_ctIrrSwOff)
#endif
#ifndef PUT_SyC_ctIrrSwOff 
#define PUT_SyC_ctIrrSwOff(val) ((val) ? SET_SyC_ctIrrSwOff : CLR_SyC_ctIrrSwOff)
#endif


#ifndef SET_SyC_stMn 
#define SET_SyC_stMn (SyC_stMn=TRUE)
#endif
#ifndef CLR_SyC_stMn 
#define CLR_SyC_stMn (SyC_stMn=FALSE)
#endif
#ifndef GET_SyC_stMn 
#define GET_SyC_stMn (SyC_stMn)
#endif
#ifndef PUT_SyC_stMn 
#define PUT_SyC_stMn(val) ((val) ? SET_SyC_stMn : CLR_SyC_stMn)
#endif


#ifndef SET_SyC_stMnOld 
#define SET_SyC_stMnOld (SyC_stMnOld=TRUE)
#endif
#ifndef CLR_SyC_stMnOld 
#define CLR_SyC_stMnOld (SyC_stMnOld=FALSE)
#endif
#ifndef GET_SyC_stMnOld 
#define GET_SyC_stMnOld (SyC_stMnOld)
#endif
#ifndef PUT_SyC_stMnOld 
#define PUT_SyC_stMnOld(val) ((val) ? SET_SyC_stMnOld : CLR_SyC_stMnOld)
#endif


#ifndef SET_SyC_stPostDrv 
#define SET_SyC_stPostDrv (SyC_stPostDrv=TRUE)
#endif
#ifndef CLR_SyC_stPostDrv 
#define CLR_SyC_stPostDrv (SyC_stPostDrv=FALSE)
#endif
#ifndef GET_SyC_stPostDrv 
#define GET_SyC_stPostDrv (SyC_stPostDrv)
#endif
#ifndef PUT_SyC_stPostDrv 
#define PUT_SyC_stPostDrv(val) ((val) ? SET_SyC_stPostDrv : CLR_SyC_stPostDrv)
#endif


#ifndef SET_SyC_stPreDrv 
#define SET_SyC_stPreDrv (SyC_stPreDrv=TRUE)
#endif
#ifndef CLR_SyC_stPreDrv 
#define CLR_SyC_stPreDrv (SyC_stPreDrv=FALSE)
#endif
#ifndef GET_SyC_stPreDrv 
#define GET_SyC_stPreDrv (SyC_stPreDrv)
#endif
#ifndef PUT_SyC_stPreDrv 
#define PUT_SyC_stPreDrv(val) ((val) ? SET_SyC_stPreDrv : CLR_SyC_stPreDrv)
#endif


#ifndef SET_SyC_stSub 
#define SET_SyC_stSub (SyC_stSub=TRUE)
#endif
#ifndef CLR_SyC_stSub 
#define CLR_SyC_stSub (SyC_stSub=FALSE)
#endif
#ifndef GET_SyC_stSub 
#define GET_SyC_stSub (SyC_stSub)
#endif
#ifndef PUT_SyC_stSub 
#define PUT_SyC_stSub(val) ((val) ? SET_SyC_stSub : CLR_SyC_stSub)
#endif


#ifndef SET_SyC_stSubOld 
#define SET_SyC_stSubOld (SyC_stSubOld=TRUE)
#endif
#ifndef CLR_SyC_stSubOld 
#define CLR_SyC_stSubOld (SyC_stSubOld=FALSE)
#endif
#ifndef GET_SyC_stSubOld 
#define GET_SyC_stSubOld (SyC_stSubOld)
#endif
#ifndef PUT_SyC_stSubOld 
#define PUT_SyC_stSubOld(val) ((val) ? SET_SyC_stSubOld : CLR_SyC_stSubOld)
#endif


#ifndef SET_MRly_st 
#define SET_MRly_st (MRly_st=TRUE)
#endif
#ifndef CLR_MRly_st 
#define CLR_MRly_st (MRly_st=FALSE)
#endif
#ifndef GET_MRly_st 
#define GET_MRly_st (MRly_st)
#endif
#ifndef PUT_MRly_st 
#define PUT_MRly_st(val) ((val) ? SET_MRly_st : CLR_MRly_st)
#endif


#ifndef SET_MoCCom_stWDAActvMsg 
#define SET_MoCCom_stWDAActvMsg (MoCCom_stWDAActvMsg=TRUE)
#endif
#ifndef CLR_MoCCom_stWDAActvMsg 
#define CLR_MoCCom_stWDAActvMsg (MoCCom_stWDAActvMsg=FALSE)
#endif
#ifndef GET_MoCCom_stWDAActvMsg 
#define GET_MoCCom_stWDAActvMsg (MoCCom_stWDAActvMsg)
#endif
#ifndef PUT_MoCCom_stWDAActvMsg 
#define PUT_MoCCom_stWDAActvMsg(val) ((val) ? SET_MoCCom_stWDAActvMsg : CLR_MoCCom_stWDAActvMsg)
#endif


#ifndef SET_SyC_stT15 
#define SET_SyC_stT15 (SyC_stT15=TRUE)
#endif
#ifndef CLR_SyC_stT15 
#define CLR_SyC_stT15 (SyC_stT15=FALSE)
#endif
#ifndef GET_SyC_stT15 
#define GET_SyC_stT15 (SyC_stT15)
#endif
#ifndef PUT_SyC_stT15 
#define PUT_SyC_stT15(val) ((val) ? SET_SyC_stT15 : CLR_SyC_stT15)
#endif


#ifndef SET_SyC_stVldTiEcuOff 
#define SET_SyC_stVldTiEcuOff (SyC_stVldTiEcuOff=TRUE)
#endif
#ifndef CLR_SyC_stVldTiEcuOff 
#define CLR_SyC_stVldTiEcuOff (SyC_stVldTiEcuOff=FALSE)
#endif
#ifndef GET_SyC_stVldTiEcuOff 
#define GET_SyC_stVldTiEcuOff (SyC_stVldTiEcuOff)
#endif
#ifndef PUT_SyC_stVldTiEcuOff 
#define PUT_SyC_stVldTiEcuOff(val) ((val) ? SET_SyC_stVldTiEcuOff : CLR_SyC_stVldTiEcuOff)
#endif


#ifndef SET_T15_st 
#define SET_T15_st (T15_st=TRUE)
#endif
#ifndef CLR_T15_st 
#define CLR_T15_st (T15_st=FALSE)
#endif
#ifndef GET_T15_st 
#define GET_T15_st (T15_st)
#endif
#ifndef PUT_T15_st 
#define PUT_T15_st(val) ((val) ? SET_T15_st : CLR_T15_st)
#endif

#endif
