/********************************************************************************
FILE:         t15_msg.h
DESCRIPTION:  Component wise header file for Copy process.
              DAMOS V5.8.3 WinServer 2008 R2
              Format N_MsgH
              Message Concept Version V2.3.1
              Do not edit this file

COPYRIGHT:    All rights reserved by ROBERT BOSCH GMBH, STUTTGART


*********************************************************************************/
#ifndef _T15_MSG_H
#define _T15_MSG_H
/* --------------extern Declaration of Original Messages--------------------*/


#ifndef __T15_STRAW_EXT__
#define __T15_STRAW_EXT__
extern uint8                    T15_stRaw;
#endif /* __T15_STRAW_EXT__ */

#ifndef __T15_ST_EXT__
#define __T15_ST_EXT__
extern bool                     T15_st;
#endif /* __T15_ST_EXT__ */

#ifndef __T15_FLGON_EXT__
#define __T15_FLGON_EXT__
extern _bit                     T15_flgOn;
#endif /* __T15_FLGON_EXT__ */

/* -------------- macro defintion of messages --------------------*/


#ifndef SET_T15_stRaw 
#define SET_T15_stRaw (T15_stRaw=TRUE)
#endif
#ifndef CLR_T15_stRaw 
#define CLR_T15_stRaw (T15_stRaw=FALSE)
#endif
#ifndef GET_T15_stRaw 
#define GET_T15_stRaw (T15_stRaw)
#endif
#ifndef PUT_T15_stRaw 
#define PUT_T15_stRaw(val) ((val) ? SET_T15_stRaw : CLR_T15_stRaw)
#endif


#ifndef SET_T15_st 
#define SET_T15_st (T15_st=TRUE)
#endif
#ifndef CLR_T15_st 
#define CLR_T15_st (T15_st=FALSE)
#endif
#ifndef GET_T15_st 
#define GET_T15_st (T15_st)
#endif
#ifndef PUT_T15_st 
#define PUT_T15_st(val) ((val) ? SET_T15_st : CLR_T15_st)
#endif


#ifndef SET_T15_flgOn 
#define SET_T15_flgOn (T15_flgOn=TRUE)
#endif
#ifndef CLR_T15_flgOn 
#define CLR_T15_flgOn (T15_flgOn=FALSE)
#endif
#ifndef GET_T15_flgOn 
#define GET_T15_flgOn (T15_flgOn)
#endif
#ifndef PUT_T15_flgOn 
#define PUT_T15_flgOn(val) ((val) ? SET_T15_flgOn : CLR_T15_flgOn)
#endif

#endif
